### ISSUE TITLE
consider new github check API

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1002]
Following https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/, maybe replace

https://github.com/iterative/cml/blob/67b6a6f877c8cc59dfa3fa8d0c46e11bc4a5078c/src/drivers/github.js#L182-L190

with `@actions/core.summary` à la the example

```js
import * as core from '@actions/core' 
  await core.summary
  .addHeading('Test Results')
  .addCodeBlock(generateTestResults(), "js")
  .addTable([
    [{data: 'File', header: true}, {data: 'Result', header: true}],
    ['foo.js', 'Pass ✅'],
    ['bar.js', 'Fail ❌'],
    ['test.js', 'Pass ✅']
  ])
  .addLink('View staging deployment!', 'https://github.com/')
  .write()
```

... or is it not worth it?

**Comment by dacbd** [comment]
We can revisit this upon a user request.
