### ISSUE TITLE
Bitbucket Server support estimated to arrive by mid 2021

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#1012]
Can be read on README.
Not sure what do we need to support

**Comment by 0x2b3bfa0** [comment]
Duplicate of https://github.com/iterative/cml/issues/140?

**Comment by DavidGOrtega** [comment]
We support Bitbucket Cloud not server. 
We should discuss to support BB server and in any case we are not planning right now to support it.

**Comment by 0x2b3bfa0** [comment]
This is a documentation issue; Bitbucket Server compatibility is tracked at #140

**Comment by DavidGOrtega** [comment]
Why is this issue closed?
I still can see `Bitbucket Server support estimated to arrive by mid 2021.`
The biggest issue is the announcement for the last year

**Comment by DavidGOrtega** [comment]
I see the PR now 🙏
