### ISSUE TITLE
`runner` restartWorkflow is not working in GH

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#1013]
We pinned the rest api in the past because they broken the restart workflow API.
GH rest api has been updated to 18 the version that broke that functionality before.

**Comment by 0x2b3bfa0** [comment]
Works on my computer™
```console
cml rerun-workflow --repo ... --id ...
```

**Comment by DavidGOrtega** [comment]
Yep! I opened an issue confirming that the restart works

**Comment by DavidGOrtega** [comment]
We need the job.id

**Comment by 0x2b3bfa0** [comment]
> _after [987ada4](https://github.com/iterative/cml/commit/987ada4fad90a06a66c379dc204bb0fb926c6258) is missing the job.id_

_Mea culpa!_ 🤦🏼‍♂️
