### ISSUE TITLE
`runner` `-single` restarts the workflows 

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#1025]
I have stated that when --single param is used the we restart the workflow if 'no-retry' is set due to lost communication with the runner

**Comment by DavidGOrtega** [comment]
Seems to be happening in GH only due to:

 1.- We have some code to control the GH parsing logs adding the jobs that are still in progress
 2.- Those jobs despite being searched with `on_progress` comes with status already `completed`, `in_progress` is not working

```js
[
  [
    {
      id: 6611495077,
      run_id: 2390767078,
      run_url: 'https://api.github.com/repos/DavidGOrtega/fashion_mnist/actions/runs/2390767078',
      run_attempt: 16,
      node_id: 'CR_kwDOFpv6-s8AAAABihNopQ',
      head_sha: '1ea79b838635928375cf459b978b6e1116cf13cd',
      url: 'https://api.github.com/repos/DavidGOrtega/fashion_mnist/actions/jobs/6611495077',
      html_url: 'https://github.com/DavidGOrtega/fashion_mnist/runs/6611495077?check_suite_focus=true',
      status: 'completed',
      conclusion: 'success',
      started_at: '2022-05-26T14:55:51Z',
      completed_at: '2022-05-26T14:56:16Z',
      name: 'train',
      steps: [Array],
      check_run_url: 'https://api.github.com/repos/DavidGOrtega/fashion_mnist/check-runs/6611495077',
      labels: [Array],
      runner_id: 708,
      runner_name: 'cml-xdvqt43qfm',
      runner_group_id: 1,
      runner_group_name: 'Default'
    }
  ]
]
```

**Comment by dacbd** [comment]
I'm confused and not sure what you mean? Are you talking about trying to re-run a job on a `cml runner` that was created with `--single`?

**Comment by casperdcl** [comment]
​no, I mean:

- a job is submitted & launches a runner (no `--single`)
- job finishes, runner waits for more jobs (upto `idle_timeout`)
- 10 jobs are submitted before `idle_timeout` is triggered. 1 job gets assigned the existing runner above, the remaining 9 jobs launch their own runners

**Comment by dacbd** [comment]
> ​no, I mean:
> 
> 1. a job is submitted & launches a runner (no `--single`)
> 2. job finishes, runner waits for more jobs (upto `idle_timeout`)
> 3. 10 jobs are submitted before `idle_timeout` is triggered. 1 job gets assigned the existing runner above, the remaining 9 jobs launch their own runners

Seems very reasonable, so `cml runner` should try to check for an existing one if present exit successfully so the dependant job can get picked up.  Though this is dangerous territory for a race condition.

I could see: 10 jobs get rapidly spawned, and there is 1 runner idle. The 10 jobs all do their check for idle runner and see one, so no new runner is created, a few seconds later, our existing runner has its new job but we have 9 waiting in the queue for that same runner.

**Comment by casperdcl** [comment]
I think we were meant to have this conversation in #575 instead @dacbd :sweat_smile:
