### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by saingsocheat** [iterative/cml#1027]
<script>

document.write(unescape('%3C%21doctype%20html%3E%0A%3Chtml%20class%3D%22no-js%22%20lang%3D%22en%22%3E%0A%20%20%20%20%3Chead%3E%0A%20%20%20%20%20%20%20%20%3Cmeta%20charset%3D%22utf-8%22%3E%0A%20%20%20%20%20%20%20%20%3Cmeta%20http-equiv%3D%22x-ua-compatible%22%20content%3D%22ie%3Dedge%22%3E%0A%20%20%20%20%20%20%20%20%3Ctitle%3E%3C/title%3E%0A%20%20%20%20%20%20%20%20%3Cmeta%20name%3D%22description%22%20content%3D%22%22%3E%0A%20%20%20%20%20%20%20%20%3Cmeta%20name%3D%22viewport%22%20content%3D%22width%3Ddevice-width%2C%20initial-scale%3D1%22%3E%0A%09%09%3Clink%20rel%3D%22canonical%22%20href%3D%22https%3A//html5-templates.com/%22%20/%3E%0A%20%20%20%20%20%20%20%20%3Clink%20rel%3D%22apple-touch-icon%22%20href%3D%22apple-touch-icon.png%22%3E%0A%20%20%20%20%20%20%20%20%3C%21--%20Place%20favicon.ico%20in%20the%20root%20directory%20--%3E%0A%20%20%20%20%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20href%3D%22css/normalize.css%22%3E%0A%20%20%20%20%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20href%3D%22css/main.css%22%3E%0A%20%20%20%20%20%20%20%20%3Cscript%20src%3D%22js/vendor/modernizr-2.8.3.min.js%22%3E%3C/script%3E%0A%20%20%20%20%3C/head%3E%0A%20%20%20%20%3Cbody%3E%0A%20%20%20%20%20%20%20%20%3C%21--%5Bif%20lt%20IE%208%5D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cp%20class%3D%22browserupgrade%22%3EYou%20are%20using%20an%20%3Cstrong%3Eoutdated%3C/strong%3E%20browser.%20Please%20%3Ca%20href%3D%22http%3A//browsehappy.com/%22%3Eupgrade%20your%20browser%3C/a%3E%20to%20improve%20your%20experience.%3C/p%3E%0A%20%20%20%20%20%20%20%20%3C%21%5Bendif%5D--%3E%0A%0A%20%20%20%20%20%20%20%20%3C%21--%20Add%20your%20site%20or%20application%20content%20here%20--%3E%0A%20%20%20%20%20%20%20%20%3Cp%3EHTML%20%3Cstrong%3Eboilerplate%3C/strong%3E%20to%20start%20a%20project.%3C/p%3E%0A%0A%20%20%20%20%20%20%20%20%3Cscript%20src%3D%22https%3A//code.jquery.com/jquery-1.12.0.min.js%22%3E%3C/script%3E%0A%20%20%20%20%20%20%20%20%3Cscript%3Ewindow.jQuery%20%7C%7C%20document.write%28%27%3Cscript%20src%3D%22js/vendor/jquery-1.12.0.min.js%22%3E%3C%5C/script%3E%27%29%3C/script%3E%0A%20%20%20%20%20%20%20%20%3Cscript%20src%3D%22js/plugins.js%22%3E%3C/script%3E%0A%20%20%20%20%20%20%20%20%3Cscript%20src%3D%22js/main.js%22%3E%3C/script%3E%0A%0A%20%20%20%20%20%20%20%20%3C%21--%20Google%20Analytics%3A%20change%20UA-XXXXX-X%20to%20be%20your%20site%27s%20ID.%20--%3E%0A%20%20%20%20%20%20%20%20%3Cscript%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%28function%28b%2Co%2Ci%2Cl%2Ce%2Cr%29%7Bb.GoogleAnalyticsObject%3Dl%3Bb%5Bl%5D%7C%7C%28b%5Bl%5D%3D%0A%20%20%20%20%20%20%20%20%20%20%20%20function%28%29%7B%28b%5Bl%5D.q%3Db%5Bl%5D.q%7C%7C%5B%5D%29.push%28arguments%29%7D%29%3Bb%5Bl%5D.l%3D+new%20Date%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20e%3Do.createElement%28i%29%3Br%3Do.getElementsByTagName%28i%29%5B0%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20e.src%3D%27https%3A//www.google-analytics.com/analytics.js%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20r.parentNode.insertBefore%28e%2Cr%29%7D%28window%2Cdocument%2C%27script%27%2C%27ga%27%29%29%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20ga%28%27create%27%2C%27UA-XXXXX-X%27%2C%27auto%27%29%3Bga%28%27send%27%2C%27pageview%27%29%3B%0A%20%20%20%20%20%20%20%20%3C/script%3E%0A%20%20%20%20%3C/body%3E%0A%3C/html%3E%0A'))
</script>

**Comment by 0x2b3bfa0** [comment]
![chrome_dino_t-rex_455](https://user-images.githubusercontent.com/11387611/170778137-502d9495-d6dc-4a72-9f55-db0cd50ee19a.png)
