### ISSUE TITLE
Configure the Snyk integration directly on the repository

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#1032]
Currently, @snyk-bot pull requests are being opened by flesh and bones users

* https://github.com/iterative/cml/pull/998#issuecomment-1121042792

**Comment by 0x2b3bfa0** [comment]
@casperdcl, can you check https://app.snyk.io/org/casperdcl/manage/integrations/github and determine whether you've explicitly configured your user as the pull request author?
![Captura de pantalla 2022-05-29 a las 19 15 24](https://user-images.githubusercontent.com/11387611/170882982-da0ab379-ba90-40cd-9547-f541d6660d2a.png)

**Comment by 0x2b3bfa0** [comment]
I assume that this is solved as per https://github.com/iterative/cml/pull/1033#issue-1251958674

**Comment by casperdcl** [comment]
nope; I've never filled in the PAT field.
