### ISSUE TITLE
logs: show terraform errors on runner failure

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#1039]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/414967/171191152-dc4ba51f-d1bd-48c4-b9bd-39254566f44b.png">

**Comment by dacbd** [comment]
related? https://github.com/iterative/cml/issues/938

**Comment by casperdcl** [comment]
- document `env: TF_LOG_PROVIDER: DEBUG` & `INFO`
- switch to `tpi_task` or add logging to `tpi_runner`

**Comment by dacbd** [comment]
> switch to `tpi_task`

I'm not a fan of yet, I would consider that very much a breaking change.

> add logging to `tpi_runner`

yes

**Comment by DavidGOrtega** [comment]
Not yet fixed. I can reproduce it when the runner is terminated abruptly
