### ISSUE TITLE
Repository address always uses HTTPS

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#1042]
### [From Discord](https://discord.com/channels/485586884165107732/728693131557732403/981910013788422184)
https://github.com/iterative/cml/blob/8d3a5741ec0c4f109441e151901c9af6e791b680/src/cml.js#L33

**Comment by DavidGOrtega** [comment]
Is this a bug? It's a safe assumption. 
The work around if to provide the `--repo` right?

**Comment by 0x2b3bfa0** [comment]
> _Is this a bug? It's a safe assumption._

If the repository remote is plain HTTP, there is no reason to believe that API calls should be HTTPS. 🤔
