### ISSUE TITLE
Migrate to ECMAScript modules

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#1051]
We're using [CommonJS modules](https://nodejs.org/api/modules.html#modules-commonjs-modules) instead of [ECMAScript modules](https://nodejs.org/api/esm.html#modules-ecmascript-modules), but most of our dependencies are already using the latter. Let's consider migrating and then transpile our code back to CommonJS when needed, e.g. when using `pkg` to produce standalone binaries.

### Dependents
* https://github.com/iterative/cml/pull/1003
* ~https://github.com/iterative/cml/pull/1026~ not anymore

### Related
* https://github.com/iterative/cml/issues/597

### Blockers

* https://github.com/vercel/pkg/pull/1323

**Comment by 0x2b3bfa0** [comment]
After several[^1] hours of research, I've come to the conclusion that the easiest “solution” for #1026 is downgrading dependencies to the latest CommonJS version available. 🙈 

[^1]: Undisclosed quantity

**Comment by 0x2b3bfa0** [comment]
Mid-term solutions
* Wait for https://github.com/vercel/pkg/pull/1323
* Wait for https://github.com/nodejs/node/pull/38905.

**Comment by 0x2b3bfa0** [comment]
#### https://github.com/nodejs/single-executable
> [_This team aims to advance the state of the art in packaging Node.js applications as single standalone executables on all supported operating systems._](https://github.com/nodejs/single-executable/blob/main/blog/2022-08-05-an-overview-of-the-current-state.md)

**Comment by dacbd** [comment]
also related: https://github.com/iterative/terraform-provider-iterative/pull/458

**Comment by 0x2b3bfa0** [comment]
* Related: https://github.com/iterative/cml/pull/1003 (to be revisited after the migration)

**Comment by dacbd** [comment]
@0x2b3bfa0 should we keep this around after the latest comments: https://github.com/vercel/pkg/pull/1323#issuecomment-1411571075

This feels like an `icebox` item to me

**Comment by 0x2b3bfa0** [comment]
Vercel's `pkg` is no longer relevant after https://github.com/iterative/cml/issues/1051#issuecomment-1238754107. I'd consider revisiting this eventually, but <kbd>icebox</kbd> is fine for now. 👍🏼
