### ISSUE TITLE
Allow setting of commit message in cml pr

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [iterative/cml#1055]
It would be great if we could set the commit message instead of `CML PR for ...`.
Actually, since my main motivation for this is so that I can append `[skip ci]` an alternative would be an option not to run CI/CD on the new commits.

**Comment by 0x2b3bfa0** [comment]
**Related**
* #815
* #1041

**Comment by casperdcl** [comment]
Closing in favour of #1017 :)
