### ISSUE TITLE
runner/github: increase self-hosted timeout to 35days

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1064]
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#usage-limits now shows 35d (not 72h).

- [ ] increase timeout #1067
- [ ] test?
- [ ] update docs https://github.com/iterative/cml.dev/pull/262

(original thread https://github.com/iterative/cml/issues/1054#issuecomment-1152856884)

**Comment by danieljimeneznz** [comment]
I have opened the PR for this change - I also question whether or not the change is actually necessary based on the Github documentation - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

I guess it is a good backup to ensure the runner is always shutdown after a predetermined amount of time, maybe we do 35 days + 5 minutes instead?
