### ISSUE TITLE
Google Compute Engine VM with V100 doesn't use the GPU (NVIDIA driver issue?)

### ISSUE THREAD

**Issue by carlthome** [iterative/cml#1065]
This _might_ be a user error but it looks like provisioning a V100 on GCP doesn't work as intended. I noticed that my TensorFlow job took a long time, SSH:ed into the CML runner VM and found the following:

```
carl_thome@cml-rnob6v0ezu:~$ nvidia-smi dmon
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

```
carl_thome@cml-rnob6v0ezu:~$ lspci
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371AB/EB/MB PIIX4 ISA (rev 03)
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:03.0 Non-VGA unclassified device: Red Hat, Inc. Virtio SCSI
00:04.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 SXM2 16GB] (rev a1)
00:05.0 Ethernet controller: Red Hat, Inc. Virtio network device
00:06.0 Unclassified device [00ff]: Red Hat, Inc. Virtio RNG
```
Note that the V100 exists on the VM.

GitLab CI job that created the above VM is:
```
create-instance:
  stage: reproduce
  needs:
    - test
  image: iterativeai/cml:0-dvc2-base1
  script:
    - cml runner
      --cloud=gcp
      --cloud-region=europe-west4-a
      --cloud-type=n1-standard-8
      --cloud-gpu=v100
      --cloud-hdd-size=256
      --labels=cml-runner-gpu
```

**Comment by carlthome** [comment]
And as an additional GCP/TensorFlow frustration, I only noticed this by seeing a long running time in the GitLab CI dashboard.

Should probably assert that GPU computation is functional within application code, but it would have been nice if there was a VM metric to alert on for low GPU utilization.

More a GCP thing than a CML thing though, of course, but part of the user journey anyway.

**Comment by 0x2b3bfa0** [comment]
It's caused by the eternal kernel version mismatch mentioned at https://github.com/iterative/cml/issues/860#issuecomment-1108575994; manually rebooting the instance fixes the issue. 🙈

**Comment by 0x2b3bfa0** [comment]
Surprisingly, [our reboot mechanism](https://github.com/iterative/terraform-provider-iterative/blob/27d0daa84e786f0da9ba8cef6d0afd163a6c0b55/iterative/resource_runner.go#L378) doesn't seem to run as intended. 🙃

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, assigned you because it's the same issue as in Discord.
