### ISSUE TITLE
GCP K80 GPU  is not working 

### ISSUE THREAD

**Issue by mehadi92** [iterative/cml#1069]
I'm facing the bellow issue, 

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.

**Comment by DavidGOrtega** [comment]
👋 @mehadi92 fixed by https://github.com/iterative/terraform-provider-iterative/pull/607

We just only have to wait the release

**Comment by dacbd** [comment]
the update has been published and I have successfully tested Nvidia GPUs on GCP, @mehadi92 if anything else comes up let us.
