### ISSUE TITLE
Improve the comment watermark format

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#1076]
Watermarks are invisible strings inserted on CML comments[^1] so they can be differentiated from comments created by users. Our current watermark format is all but uniquely identifiable, and should probably be updated.

https://github.com/iterative/cml/blob/7bd925718ca2f1abb8d484fdd551a38683eb5cd3/src/cml.js#L181

Note that watermarks use a blank image instead of an HTML comment, because not all forges support the latter in their respective flavours of Markdown.

### Proposal

Use the [image description](https://spec.commonmark.org/0.30/#image-description) to store arbitrary data encoded as Base64 (e.g. useful for live metrics) and the [image link](https://spec.commonmark.org/0.30/#images) to point to an invisible, tiny image in a static host of our choice.

```md
![eyJrZXkiOiAidmFsdWUifQ==](https://cml.dev/9b0e332381649d87112c181dae1568640ea055b3100e5253d86410d276db8af9/pixel.gif) 
```

### Precursors
* https://github.com/iterative/cml/pull/1026#discussion_r898745329

[^1]: E.g. created by running `cml send-comment`

**Comment by casperdcl** [comment]
> Use the [image description](https://spec.commonmark.org/0.30/#image-description) to store arbitrary data encoded as Base64

:nauseated_face:

**Comment by 0x2b3bfa0** [comment]
We can also use Unicode zero-width watermarks: 🤔 
* https://doi.org/10.1109/iThings-GreenCom-CPSCom-SmartData-Cybermatics50389.2020.00116
* https://github.com/offdev/zwsp-steg-js & https://github.com/enodari/zwsp-steg-py
* https://mayadevbe.me/posts/zw_steg

**Comment by tasdomas** [comment]
Looks like there are several ways to do this:
* Add a base64 string to the image alt text: `![CML watermark <base64 snipped>](https://raw.githubusercontent.com/iterative/cml/master/assets/watermark.svg)`
* Add a base64 string to the image title: `![CML watermark](https://raw.githubusercontent.com/iterative/cml/master/assets/watermark.svg "base64")`
* Add a CML logo with a link to https://cml.dev/ and the link title being base64 encoded data: `[![CML](https://cml.dev/logo.png)](https://cml.dev "base64")`
* There's also the option of using zero-width unicode characters, but this feels a tad hacky

Also, I think it looks a bit amateurish to include resources hosted by github ([the watermark svg](https://github.com/iterative/cml/issues/1076)) - we should at least host it ourselves.

**Comment by tasdomas** [comment]
> Playing devil's advocate: hosting it on GitHub is a good guarantee it can't be used for tracking. 🤷🏼‍♂️
That's putting a lot of faith in github :)

**Comment by 0x2b3bfa0** [comment]
> _There's also the option of using zero-width unicode characters, but this feels a tad hacky_

I proposed this because as David Ortega pointed out a few days ago, the current image-based watermarks are visible at the bottom of mail notifications. Yes, it's “a little bit” more hacky. 😄 

![Captura de pantalla 2022-09-26 a las 13 46 31](https://user-images.githubusercontent.com/11387611/192268683-037d589c-6fde-47f1-abbb-856407468824.png)

**Comment by tasdomas** [comment]
**Option 1**
![CML watermark cnVuLWlkPTMwOTgzODIwNzQ=](https://raw.githubusercontent.com/iterative/cml/master/assets/watermark.svg)

**Option 2**
![CML watermark](https://raw.githubusercontent.com/iterative/cml/master/assets/watermark.svg "cnVuLWlkPTMwOTgzODIwNzQ=")

**Option 3**
[![CML](https://iterative.ai/static/47f435cb7088cb14da0b4435e86a2372/3d840/logo-cml.png)](https://cml.dev "cnVuLWlkPTMwOTgzODIwNzQ=") (obviously the logo would need to be smaller)

**Comment by 0x2b3bfa0** [comment]
**Option $e$**[^1]
![](https://raw.githubusercontent.com/iterative/cml/master/assets/watermark.svg "cnVuLWlkPTMwOTgzODIwNzQ=")

[^1]: https://en.wikipedia.org/wiki/E_(mathematical_constant)

**Comment by 0x2b3bfa0** [comment]
How it looks in email notifications:

![Captura de pantalla 2022-09-26 a las 13 56 53](https://user-images.githubusercontent.com/11387611/192270334-13f575be-0bab-40e8-b604-be85e34f9679.png)

**Comment by tasdomas** [comment]
Option $e$ and 3 appear to be most viable

**Comment by casperdcl** [comment]
1. [poor rendering](https://github.com/iterative/cml/issues/1076#issuecomment-1257910629): could this be fixed by using PNG instead of SVG?
2. poor URL: I'd be fine with replacing `raw.githubusercontent.com/iterative/cml/master/assets` -> `static.iterative.ai/cml`
3. guaranteeing no [hidden tracking](https://github.com/iterative/cml/issues/1076#issuecomment-1257907514): the above is open source at `https://github.com/iterative/static` to prove no nefarious activity
4. base64: why? what is the use case? What metadata do we actually need to inject? If it's just a comment ID then plaintext | `urllib.parse.quote` is enough?

**Comment by 0x2b3bfa0** [comment]
> 4\. _`urllib.parse.quote`_

`hashlib` 🤺

**Comment by tasdomas** [comment]
>     4. base64: why? what is the use case? What metadata do we actually need to inject? If it's just a comment ID then plaintext | `urllib.parse.quote` is enough?

`base64` is not strictly necessary - my [current thinking](https://github.com/iterative/cml/pull/1173/files#diff-509933ea8efc212e9e460c2b844fcbd03061d80cef264781b632118f971e4584R173) is to store the watermark scope with the watermark.

**Comment by dacbd** [comment]
completed
#1173 
#1309
