### ISSUE TITLE
Spot termination detection

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#1087]
We had a mechanism in place based on `SIGTERM`  having included even a SpotNotifier, however it's seems that some users including me have suffered a bit of flakiness terminating the instance. Last addition of ACPI check seems to be fixing the non termination issue that what was utterly proved  by myself in GCP and AWS until it started to work again as expected 🤦 

This issue is a reminder to continue investigating if the ACPI listener is worth or should be removed as indeed it should.

**Comment by 0x2b3bfa0** [comment]
* https://github.com/iterative/cml/issues/663#issuecomment-1159374581
* https://github.com/iterative/terraform-provider-iterative/issues/90#issuecomment-875712365

**Comment by dacbd** [comment]
completed
