### ISSUE TITLE
Missing key/value separator on `cml runner --cloud-metadata`

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#1099]
From https://discord.com/channels/485586884165107732/728693131557732403/997065340724973608, found by running `cml runner --cloud-metadata "Key With Spaces=Value"`

```
│ On main.tf line 30: Expected an equals sign ("=") to mark the beginning of
│ the attribute value. If you intended to given an attribute name containing
│ periods or spaces, write the name in quotes to create a string literal.
```

Proposed workaroud: `cml runner --cloud-metadata '"Key With Spaces"="Value"'`

**Comment by dacbd** [comment]
relevant code chunks:
https://github.com/iterative/cml/blob/2acfde589f4b435c5b9adf3010ef773e71a060af/bin/cml/runner.js#L532-L538
Perhaps this could be as simple as wrapping `${key}` in `""` below?:
https://github.com/iterative/cml/blob/2acfde589f4b435c5b9adf3010ef773e71a060af/src/terraform.js#L66-L67

https://github.com/iterative/cml/blob/2acfde589f4b435c5b9adf3010ef773e71a060af/src/terraform.js#L130-L134

**Comment by 0x2b3bfa0** [comment]
The current approach is prone to all kinds of escaping issues, and #1100 is an easier and safer alternative. Worth the hassle of testing, methinks.
