### ISSUE TITLE
artifact registry docker image for cml runner

### ISSUE THREAD

**Issue by shortcipher3** [iterative/cml#1136]
I'm trying out a `cml runner` on `GCP` using `Gitlab`.  I have a working file that starts up an instance with `dvcorg/cml:latest` docker image.

Now I want to change the docker image for my own that adds in some helper utilities specific to my team.  I'm hosting the image on artifact registry in Google cloud and I have granted the `cloud-permission-set` access to the container registry.

However my job fails with the error:

```
ERROR: Job failed: failed to pull image "us-west3-docker.pkg.dev/<myproject>/containers/cml:latest" with specified policies [always]: Error response from daemon: Head "https://us-west3-docker.pkg.dev/v2/<myproject>/containers/cml/manifests/latest": denied: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/<myproject>/locations/us-west3/repositories/containers" (or it may not exist) (manager.go:235:0s)
```

@dacbd confirmed he was able to reproduce and has a workaround for `github`.

**Comment by dacbd** [comment]
related: https://github.com/iterative/terraform-provider-iterative/issues/627

**Comment by dacbd** [comment]
Will close after the next release of our terraform provider.

**Comment by dacbd** [comment]
@shortcipher3 did you add the repository variable `DOCKER_AUTH_CONFIG` as `{"credHelpers": { "us-west1-docker.pkg.dev": "gcr"}}` ? (using the correct regional domain for your usecase)

**Comment by shortcipher3** [comment]
@dacbd Not initially, so I just tried and reran and had the same error.

I noticed my `~/.docker/config.json` includes this line:
```
cat ~/.docker/config.json
{
  "credHelpers": {
    "us-west3-docker.pkg.dev": "gcloud"
  }
}
```

So I also replaced `gcr` with `gcloud`, but saw the same result.

**Comment by dacbd** [comment]
@shortcipher3 what roles or permissions are assgined to the service account you are using?

examples:
either in a custom role?
<img width="353" alt="Screen Shot 2022-08-31 at 21 05 50" src="https://user-images.githubusercontent.com/1105843/187829529-3bd73e7b-f4ae-49f1-9898-6d9edc2c6dc1.png">

or a GCP managed one?
<img width="679" alt="Screen Shot 2022-08-31 at 21 07 57" src="https://user-images.githubusercontent.com/1105843/187829628-e78ffa4a-f22a-4e3e-8874-46111098f063.png">

if it's not on a service account permission error can you try and get the instances `cml.service` logs?  I'll have to try some more experimenting.

**Comment by dacbd** [comment]
@shortcipher3 I double checked this again, and It does work for me:
![Screenshot from 2022-09-05 11-16-19](https://user-images.githubusercontent.com/1105843/188499636-26297c14-6254-46c1-a8db-70c53d8a8087.png)
![Screenshot from 2022-09-05 11-15-28](https://user-images.githubusercontent.com/1105843/188499675-079e036d-2d57-4a4a-9bba-bba86971375a.png)

**Comment by shortcipher3** [comment]
I'm missing line 8 of your output, instead my goes straight to the next line

```
Running with gitlab-runner 15.3.0 (bbcb5aba)
  on cml-22idn839d2 kx2ys98k
Resolving secrets
00:00
Preparing the "docker" executor
00:05
Using Docker executor with image us-west3-docker.pkg.dev/google-project-12345/containers/company_cml:latest ...
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-bbcb5aba ...
Using docker image sha256:eb09578c512493961df34d9fcea26ec9beba73f6888b35dfe36858c36accf8fa for registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-bbcb5aba with digest registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper@sha256:24641a70251a846357ccb5866ae834e9907eb1d1e52f2dcaa02cf5e88e6481b3 ...
Pulling docker image us-west3-docker.pkg.dev/google-project-12345/containers/company_cml:latest ...
WARNING: Failed to pull image with policy "always": Error response from daemon: Head "https://us-west3-docker.pkg.dev/v2/google-project-12345/containers/company_cml/manifests/latest": denied: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/google-project-12345/locations/us-west3/repositories/containers" (or it may not exist) (manager.go:235:0s)
ERROR: Job failed: failed to pull image "us-west3-docker.pkg.dev/google-project-12345/containers/company_cml:latest" with specified policies [always]: Error response from daemon: Head "https://us-west3-docker.pkg.dev/v2/google-project-12345/containers/company_cml/manifests/latest": denied: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/google-project-12345/locations/us-west3/repositories/containers" (or it may not exist) (manager.go:235:0s)
```

I wonder if it is using a cached version and I need to force it to pull the latest.  Any ideas?

**Comment by shortcipher3** [comment]
In my deploy runner stage I ran `cml --version` and I got `0.17.3`.  I noticed your `gitlab-runner` is version `15.3.0` whereas mine is `13.11.0` - maybe you are using a feature not available in the older `gitlab-runner` versions?

**Comment by shortcipher3** [comment]
Found my problem, I was missing the scopes on this line:
```
--cloud-permission-set=<my_account>@<my_project>.iam.gserviceaccount.com
```

The working version is:
```
--cloud-permission-set=<my_account>@<my_project>.iam.gserviceaccount.com,scopes=storage-rw,datastore
```

I thought my service account permissions would be sufficient.

Thanks for your help!

**Comment by 0x2b3bfa0** [comment]
## Example[^1]

_Loosely based on the pertaining [official documentation](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#use-credential-helpers)_

### CI/CD Environment Variables
| Name | Value |
| -- | -- |
| `DOCKER_AUTH_CONFIG` | `{"credHelpers": {"ZONE-docker.pkg.dev": "gcr"}}` |
| `GOOGLE_APPLICATION_CREDENTIALS_DATA` | [Contents of a Google Cloud service account JSON key file](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating) |
| `REPO_TOKEN` | [GitLab Personal Access Token](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) | 

### `.gitlab-ci.yml`
```yaml
runner:
  when: always
  image: iterativeai/cml
  script:
  - cml runner --labels=cml --cloud=gcp --cloud-permission-set=$(printenv GOOGLE_APPLICATION_CREDENTIALS_DATA | jq .client_email),scopes=storage-ro,datastore

job:
  tags: [cml]
  needs: [runner]
  image: LOCATION-docker.pkg.dev/PROJECT/REPOSITORY/IMAGE:TAG
  script:
  - echo succeeded
```

> **Note**
> Replace the [`LOCATION`](https://cloud.google.com/artifact-registry/docs/repositories/repo-locations), `PROJECT`, `REPOSITORY`, `IMAGE` and `TAG` placeholders with appropriate values.

> **Warning**
> This example uses the new [Artifact Registry](https://cloud.google.com/artifact-registry) (i.e. a `LOCATION-docker.pkg.dev` domain) instead of the old Container Registry (i.e. the `gcr.io` domain) but instructions are similar for both.

[^1]: Based on https://github.com/iterative/terraform-provider-iterative/issues/627#issuecomment-1190893987

**Comment by dacbd** [comment]
> Found my problem, I was missing the scopes on this line:
> 
> ```
> --cloud-permission-set=<my_account>@<my_project>.iam.gserviceaccount.com
> ```
> 
> The working version is:
> 
> ```
> --cloud-permission-set=<my_account>@<my_project>.iam.gserviceaccount.com,scopes=storage-rw,datastore
> ```
> 
> I thought my service account permissions would be sufficient.
> 
> Thanks for your help!

Dang, I should have seen that with what you had shared... 👓
