### ISSUE TITLE
CML runner is terminated after connecting to BB

### ISSUE THREAD

**Issue by mahletA** [iterative/cml#1137]
Running CML does not work using the `iterativeai/cml:0-dvc2-base1-gpu` image as bitbucket's implementation also requites running docker.
I tried to fix that by extending `iterativeai/cml:0-dvc2-base1-gpu` with dind. I changed the base image to start from `teracy/ubuntu:20.04-dind-latest`.
Running CML runner from inside this container terminates and shows the following error.

```
info: Preparing workdir /home/runner...
info: Launching bitbucket runner
warn: Bitbucket runner is working under /tmp folder and not under /home/runner as expected
warn: Error connecting to ACPI socket: connect ENOENT /var/run/acpid.socket. The acpid.service helps with instance termination detection.
error: Error: runner closed with exit code 125
    at ChildProcess.<anonymous> (/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner.js:297:37)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {"status":"terminated"}
info: Unregistering runner cml-h3ewaj0nwa...
error:  Failed: docker stop cml-h3ewaj0nwa

        Error response from daemon: No such container: cml-h3ewaj0nwa
```

My guess is that something goes wrong with the secondary docker container instance spinned up by BB.

**Comment by dacbd** [comment]
can you describe in more detail what you are trying to achieve?

**Comment by DavidGOrtega** [comment]
> can you describe in more detail what you are trying to achieve?

Coming from [here](https://discord.com/channels/485586884165107732/728693131557732403/1012344317974687886) @dacbd

**Comment by dacbd** [comment]
So to run `cml runner --driver=bitbucket` but from a container?

**Comment by mahletA** [comment]
@dacbd I keep running into this error when running `cml runner --driver=bitbucket` from a container.

**Comment by DavidGOrtega** [comment]
@mahletA just to clarify. You are running docker in docker what its telling you the error is that it does not know the container `cml-h3ewaj0nwa` thats (I think) because docker is not installed in your docker container to run another docker container.
Take into account the bb runner is a docker container

**Comment by DavidGOrtega** [comment]
@mahletA I assume that you were able to fix this. Please open the ticket again if was not the case
