### ISSUE TITLE
custom watermark ID

### ISSUE THREAD

**Issue by dacbd** [iterative/cml#1144]
So that when cml goes to update a comment it can determine which comment to update.

For cases where multiple comments are made or when multiple workflows run against a single PR each with a cml comment, they can better distinguish which comment to update.

**Comment by 0x2b3bfa0** [comment]
Potential duplicate of / related to https://github.com/iterative/cml/issues/1076?

**Comment by dacbd** [comment]
related but different enough

**Comment by tasdomas** [comment]
It could be a lot simpler and less race-prone if we limited `comment update` to updating comments created by this action run only. Would that be too limiting?

**Comment by dacbd** [comment]
> It could be a lot simpler and less race-prone if we limited `comment update` to updating comments created by this action run only. Would that be too limiting?

If there were multiple `comment create`'s in a single workflow this would make sense. Where this causes issues is with `pull_request` type events. Where there might be several runs of a workflow for a single PR either via multiple workflows or the user pushes additional commits retriggering the event. For this case in order to prevent extra bash scripting a single `create_or_update` type function is needed.

**Comment by DavidGOrtega** [comment]
How different s going to be the wartermark? Studio needs the CML waterrmarks to be able to extract the CML report.
