### ISSUE TITLE
How to select Python version for docker Images of CML

### ISSUE THREAD

**Issue by DataPsycho** [iterative/cml#1146]
Hi, 
Is there a way to choose docker images for different minor version of python 3. For example I might need python 3.8 and I locked my requirements with some package version which need python 3.8. In such case how can I choose a docker image. The general docker image looks like cml-py3:runner . Do you have python version specific dvc containers for example: cml-py38:runner , py39:runner etc.

**Comment by dacbd** [comment]
the `cml-py3` is no longer updated. You can look at our images on github and our dockerfile. If they don't have the version you need, I'd recommend installing one of the [cml binaries found in the releases](https://github.com/iterative/cml/releases/tag/v0.17.3) into your custom docker image or just using the plain github actions to control the running environment, like the [`setup-python`](https://github.com/actions/setup-python) and [`setup-cml`](https://github.com/iterative/setup-cml) actions.
