### ISSUE TITLE
Instance diversification [esp. spot & gpu] - Mixing instances by using  instance attributes (cpu/mem/gpu/gpu-mem)

### ISSUE THREAD

**Issue by omesser** [iterative/cml#1174]
When using spot instances - only being able to select 1 instance type can make the user very susceptible to availability issues of spot instances of that type.
Similarly - there are often capacity or availability issues of specific instance types in an account+region.
A common and good practice to get around this is to defined a set of cpu/mem/gpu/other-attributes ranges to filter multiple instance type that are all compatible with the compute demands of the user - mixing instances

We can define this when defining a launch template for ASGs, to overcome capacity limitations (also available for ec2 fleet, probably not interesting for us).

## example

Below is an example from launch template configuration (clickops) and some resource ranges and the resulting instances
<img width="732" alt="Screen Shot 2022-09-20 at 16 46 20" src="https://user-images.githubusercontent.com/18181802/191274786-a4df1561-f5e0-4aca-83b3-55a0a6a257e4.png">

**Comment by omesser** [comment]
fyi @iterative/cml  - would be happy for your notes / thoughts on if/how to incorporate this

**Comment by dacbd** [comment]
Kind of a duplicate for: https://github.com/iterative/cml/issues/1101

**Comment by omesser** [comment]
@dacbd yes, I am seeing it now. Originally looked for similar issues but couldn't find anything that matched.
I believe this should be possible for non spot as well, otherwise the same
I will close this then, cont in #1101

**Comment by dacbd** [comment]
agreed that something like this should exist for non-spot as well :+1:
