### ISSUE TITLE
Feature Requests: expand `cml-runner --cloud gcp` options

### ISSUE THREAD

**Issue by djmmoss** [iterative/cml#1175]
Hi there,

I have two feature requests for specifically `cml-runner --cloud gcp`:

1. Add an option to choose the type of persistent disk, currently it always defaults to `pd-balanced`, you can see the different options here: https://cloud.google.com/compute/docs/disks#disk-types
2. Add an option to specify the accelerator count. For example if I want to use a VM with 16 vCPUs (`n1-standard-16` or `n1-highmem-16`) the minimum number of GPUs that need to be provisioned is 2. As far as I know there is currently no way to provision more than 1 GPU. You can see the different vCPUs per GPU brackets here (for the V100): https://cloud.google.com/compute/docs/gpus#nvidia_v100_gpus

Thanks,
Duncan

**Comment by 0x2b3bfa0** [comment]
@djmmoss, can you please split this issue into two separate feature requests?

**Comment by 0x2b3bfa0** [comment]
> _Add an option to specify the accelerator count. For example if I want to use a VM with 16 vCPUs (n1-standard-16 or n1-highmem-16) the minimum number of GPUs that need to be provisioned is 2. As far as I know there is currently no way to provision more than 1 GPU. You can see the different vCPUs per GPU brackets here (for the V100): https://cloud.google.com/compute/docs/gpus#nvidia_v100_gpus_

I believe you can use the following `{machine}+{accelerator}*{count}` syntax:
```console
cml runner --cloud=gcp --cloud-type=custom-64-524288-ext+nvidia-tesla-v100*8
```

**Comment by dacbd** [comment]
https://github.com/iterative/cml/issues/1176
