### ISSUE TITLE
linter: update yaml formatting

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1177]
The pre-commit hooks/linter insists on odd wrapping (particularly for `.github/workflows/*`)
Would be happy if anyone wants to mod `.eslintrc.js`/`prettier.config.js`/`.restyled.yaml`

**Comment by magdapoppins** [comment]
Is this issue still relevant? Could you give an example of what the odd wrapping contra what we'd want to have? I could pick this up.
