### ISSUE TITLE
`TB_CREDENTIALS` aren't properly detected

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#1243]
Setting `TB_CREDENTIALS` is not enough as credentials is now a required parameter.

cml.dev examples are fundamentally broken due to this.

**Comment by 0x2b3bfa0** [comment]
cml.dev examples are no longer the source of truth; please refer to workflows on cml-examples-dev

**Comment by DavidGOrtega** [comment]
> cml.dev examples are no longer the source of truth and shall be updated; please refer to workflows on cml-examples-dev

Not sure what do you mean here. Both cases are broken due to this bug

**Comment by DavidGOrtega** [comment]
The PR #1244 does not seems to fix the issue

**Comment by dacbd** [comment]
maybe since its marked as required yargs isn't properly detecting our injection for the env var.

**Comment by DavidGOrtega** [comment]
Yes, probably as I stated in the PR.

**Comment by 0x2b3bfa0** [comment]
Then all the legacy environment variables are broken?

**Comment by dacbd** [comment]
> Then all the legacy environment variables are broken?

I don't think that is the case, they could be populated properly but only after yargs performs its `required: true` validation?

**Comment by 0x2b3bfa0** [comment]
Then, should we run the environment variable aliasing code before calling `yargs.parse` to prevent this issue?

**Comment by dacbd** [comment]
> Then, should we run the environment variable aliasing code before calling `yargs.parse` to prevent this issue?

to me, it looks like that is already the [case](https://github.com/iterative/cml/blob/17a045e9dd8121dc4b7e155d6c647813db1e6345/bin/cml.js#L156-L170)? but you are the resident yargs expert 😇 can we make that tweak?
