### ISSUE TITLE
ci: safe.directory

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1250]
from https://github.com/iterative/stale-model-example/pull/4#pullrequestreview-1160645257:

should `cml ci` run `git config --global --add safe.directory .`?

**Comment by casperdcl** [comment]
Actually seems duplicate of #970

**Comment by 0x2b3bfa0** [comment]
Unless proven otherwise, this functionality is already implemented for every `cml` command, including `cml ci`

https://github.com/iterative/cml/blob/fc9e235679ff850a646d977da016a4ad2d682634/src/cml.js#L84-L121

**Comment by 0x2b3bfa0** [comment]
Closed with #974
