### ISSUE TITLE
CML and Kubernetes

### ISSUE THREAD

**Issue by rickvanveen** [iterative/cml#1285]
Hi! I'm following the documentation [here](https://cml.dev/doc/self-hosted-runners#allocating-cloud-compute-resources-with-cml) about how to setup a self-hosted runner. Instead AWS we use a self hosted kubernetes setup. 

I got the `launch-runner` job working (although I needed to add setup steps for node, kubectl (+ plugin), and terraform to get it to work). And my understanding of this at the moment is: This job creates a, in kubernetes terminology, pod that runs a container which registers itself as `self-hosted` github/cml runner. 

The second job `train-and-report` in the documentation uses a container image again. However, when I try to use my simple training job using this same option (` container: image: docker://iterativeai/cml:0-dvc2-base1-gpu options: --gpus all`, but then with correct whitespace). I get an error. Namely, `Error: docker: command not found`. 

My confusion is now: How to set up CML/Github/kubernetes in the intended and appropriate way. I can imagine I need to customize the container that registers itself as the github/cml runner to include docker? Am I missing something from the documentation. 

Any explanation and help is appreciated!

**Comment by 0x2b3bfa0** [comment]
Hello @rickvanveen!

As per https://github.com/iterative/terraform-provider-iterative/issues/146#issuecomment-931308916, using `container` in your workflow jobs isn't supported when the runner itself is containerized (e.g. on Kubernetes)

**Comment by rick-van-veen** [comment]
Okay I get it I think. Does this also mean that when I go from my simple models to more complex ones I will need to setup all the requirement to train those complex models through Github actions and I cannot use the provided containers?

**Comment by 0x2b3bfa0** [comment]
Currently there is no way of specifying a custom container image, sorry. Still — partially due to [this related use case](https://discord.com/channels/485586884165107732/728693131557732403/1057160051904753704) — it may be implemented relatively soon.

**Comment by 0x2b3bfa0** [comment]
#1302 may help you achieve what you want, although any images you specify will have to use one of our images[^1] as base.

[^1]: E.g. `FROM iterativeai/cml:0-dvc2-base1-gpu` in your `Dockerfile`

**Comment by rickvanveen** [comment]
Great! I will look into it as soon as possible. I think it will help.
