### ISSUE TITLE
No Module name 'sklearn'

### ISSUE THREAD

**Issue by hlin863** [iterative/cml#1298]
When I forked the [example repository](https://github.com/iterative-test/cml-example-base) and followed the tutorial for running the workflow. I receive an error message in the workflow that:

```
Traceback (most recent call last):
  File "/home/runner/work/cml-example-base/cml-example-base/train.py", line 1, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
```

Thank you in advance for checking my error. I tried to implement a CI system with CML on other repositories but I encounter the same error as aforementioned.

**Comment by DavidGOrtega** [comment]
👋 @hlin863 
Would you mind to share your workflow file?

**Comment by hlin863** [comment]
I'm excited to share the [GitHub Repo for the files](https://github.com/hlin863/ML-Integration-OFFICIAL) .

**Comment by hlin863** [comment]
Would you like to take a look at the repository to identify the errors?

**Comment by DavidGOrtega** [comment]
Let me try your workflow

**Comment by hlin863** [comment]
Thank you for taking a look at the workflow.

**Comment by DavidGOrtega** [comment]
Hi @hlin863 the issue is that the example is trying to setup `sklearn` as requirement instead of `scikit-learn`

Where did you find this repo?
I recommend you to use the ones listed on cml.dev

https://github.com/iterative/cml_base_case

**Comment by hlin863** [comment]
I updated the link with the repo forked from the [cml-example-base](https://github.com/hlin863/cml-example-base)

**Comment by hlin863** [comment]
I'm currently using the tutorial from [Youtube](https://www.youtube.com/watch?v=9BgIDqAzfuA&t=310s) for building up the ML CI system.

**Comment by DavidGOrtega** [comment]
I opened the ticket https://github.com/iterative-test/cml-example-base/issues/3

Thanks for reporting!!

**Comment by DavidGOrtega** [comment]
@hlin863 its fixed. Please feel free to open the issue if you find it again 🙏
