### ISSUE TITLE
cml comment create raises BAD CREDENTIALS

### ISSUE THREAD

**Issue by nshahpazov** [iterative/cml#1306]

**Comment by 0x2b3bfa0** [comment]
@nshahpazov, it looks like you’ve edited the issue body and now it’s empty; this comment is based on the original issue body.

This error probably happened because there was a duplicate `$` character in the `REPO_TOKEN` environment variable value.

```diff
- REPO_TOKEN: $${{ secrets.GITHUB_TOKEN }}
+ REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by dacbd** [comment]
you may need to edit actions permission settings for a forked repo as well.
see here: 
<img width="1105" alt="Screenshot 2023-01-05 at 07 24 32" src="https://user-images.githubusercontent.com/1105843/210816378-3cfb856c-b7f9-4055-91c0-22d34ff3d22a.png">

**Comment by nshahpazov** [comment]
Thank you! I managed to fix it!
