### ISSUE TITLE
`commit create`

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#1308]
With similar convenience options as `cml pr create`.

```
cml commit create [--skip-ci] [--message=<...>] [--user-<name|email>=<...>]
```

Example use case:

```
cml ci
git commit -a -m "CML commit [skip ci]"
while ! git push; do
  git fetch origin $BRANCH
  git rebase origin/$BRANCH
done
```

to push a new commit without infinite CI recursion or [overwriting simultaneous pushes](https://stackoverflow.com/a/70205896)

**Comment by 0x2b3bfa0** [comment]
How is this better or more reliable than pull reuqests?

**Comment by casperdcl** [comment]
Because a PR is more heavyweight/overkill, and also might have some other side-effects (trigger different workflows).

**Comment by 0x2b3bfa0** [comment]
It's indeed a bit more heavyweight, but also more idiomatic: otherwise we'd be reinventing automatic conflict resolution.
