### ISSUE TITLE
cml comment create in jenkinsfile and bitbucket

### ISSUE THREAD

**Issue by dexterarmy** [iterative/cml#1358]
I am using bitbucket to store my code and i am using my virtual machine hosted on google cloud provider to store data and DVC to track it .  
I want to run jenkinsfile and in that jenkinsfile i am using "cml comment create " command. But it is giving me error : resource not found.
How can i use cml comands in my jenkinsfile like cml comment create and use jenkinsfile and bitbucket seamlessly with CML.
I am not finding any solution on the Internet too .
Does CML even supports Jenkinsfile ? or i am wasting my time ?
Like when i run github actions pipeline cml comment creatre is working . But why it is not working in jenkinsfile ????

**Comment by 0x2b3bfa0** [comment]
Hello, @dexterarmy! Can you please provide a minimal example of your Jenkinsfile and the full output of the `cml comment create` command? Even though your use case deviates a bit from our official examples, it should work as well.

Note that your Jenkins code should have access to a `REPO_TOKEN` environment variable containing your Bitbucket [personal access token](https://cml.dev/doc/self-hosted-runners?tab=Bitbucket#personal-access-token).

**Comment by dexterarmy** [comment]
MY JENKINSFILE -> 
pipeline {
    agent any
    
     environment{
            REPO_TOKEN = 'xyz'
            }
     
 	  stages {
        

                stage('module install') {
            steps {
    
                sh "pip3 install -r requirements.txt"
            }
        }
		
		        stage('data remote') {
            steps {
                sh "dvc pull -r local"
            }
        }
        
        	stage('modal trained') {
            steps {
                sh "python3 src/code.py"
                 sh "echo '# CML report' >> report.md"
                  sh" cat metrics.txt >> report.md" 
                  sh " echo '![](./model_1.png 'crim vs medv linear regression in blue')' >> report.md"
                   sh " echo '![](./model_2.png 'lstat vs medv linear regression in red')' >> report.md" 
            }
        }
        
       
     		  stage('run cml cmd') {
            steps {
         //  withCredentials([gitUsernamePassword(credentialsId: 'mohit', gitToolName: 'bit_bucket')]) {
           //     sh 'export $CML_GITHUB_TOKEN=$bit_bucket && cml comment create report.md '
   
                sh "export REPO_TOKEN=$REPO_TOKEN && cml comment create report.md" 
                sh "cat report.md"

            }
        }
        
        }
}

ERROR -> 

![Screenshot from 2023-02-18 17-30-15](https://user-images.githubusercontent.com/99288398/219866612-7d375a61-d08f-4bee-9fed-968b5043466f.png)

**Comment by 0x2b3bfa0** [comment]
@dexterarmy, maybe you have to [enable the Pull Request Commit Links application](https://cml.dev/doc/ref/comment#bitbucket) first. 🤔

**Comment by dexterarmy** [comment]
This app is already installed. 
Jenkins is running on my local VM and it is taking code from my bitbucket. 
Now in the end cml comment create is not running and is saying resource not found. Why it is not working ?

![Screenshot from 2023-02-18 22-56-07](https://user-images.githubusercontent.com/99288398/219879692-9e1e5dae-efa4-4c14-83de-4d14b3130856.png)

**Comment by 0x2b3bfa0** [comment]
Thanks! Can you run `cml --log=debug comment create ...` and also set the `NODE_DEBUG` environment variable to `http,net,stream` to get more information about the request?

**Comment by dexterarmy** [comment]
thanks ! Now it is working, when i created a seperate branch in bitbucket and created a pull request manually then cml created the comment.
But now a different issue is arising that that in comment in bitbucket image is not being showed in markdown file but ok it is a different issue. 
Thanks for helping me

**Comment by dacbd** [comment]
@dexterarmy check the format of the markdown you are adding to your comment for the image to upload/and linked into your comment which is being sent.

```
echo '![](./plot.png)' >> report.md
cml comment create report.md
```

I'm going to close this issue since you said that the original issue has been resolved, If you have further problems with images not being displayed please open another issue or ask us questions in our discord.
