### ISSUE TITLE
Terraform error when setting cloud-type with K8s cluster

### ISSUE THREAD

**Issue by rickvanveen** [iterative/cml#1361]
I am trying to launch a cml runner and limit it's resources on our k8s cluster using the following parameters:

```
cml runner launch \
  --repo="${{ github.server_url }}/${{ github.repository }}.git" \
  --token=${{ secrets.PERSONAL_ACCESS_TOKEN }} \
  --log=debug \
  --driver=github \
  --labels=cml \
  --name=trainer \
  --idle-timeout=-1 \
  --single \
  --cloud=kubernetes \
  --cloud-type=8-16000+nvidia-a100*1
```

This results in the following log with errors:

```json
{"level":"error","message":"terraform error: Error: Failed creating the machine: invalid instance type"}
```

Repetition of some info/debug messages

```json
{"level":"error","message":"terraform apply error","stack":"Error: terraform apply error\n    at Object.apply (/usr/lib/node_modules/@dvcorg/cml/src/terraform.js:55:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async runTerraform (/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner/launch.js:182:5)\n    at async runCloud (/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner/launch.js:191:19)\n    at async run (/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner/launch.js:432:14)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner/launch.js:445:5)"}
```

Am I understanding the [https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#machine-type](documentation) wrong or what is the problem? 

I also tried setting the `--cloud-type` with `m` and use the `--cloud-gpu` option in addition. This does not give me an error and actually launches a runner successfully on the cluster, but when I describe it it has not limits set to the gpu. How would I set them in this case?

Using `--cloud-type` that is anything different from the predefined machine types also results in provided error.

**Comment by 0x2b3bfa0** [comment]
Note that `task` machine types are different from `runner` machine types; the latter ~do~did not support arbitrary code/memory amounts. We'll probably fix it with https://github.com/iterative/terraform-provider-iterative/pull/742.

**Comment by rickvanveen** [comment]
So my assumptions about how to use it (and what it does) are correct, but it's currently not working?

**Comment by dacbd** [comment]
I think your assumption is natural and we took it as a feature request to add that logic to `cml runner`
