### ISSUE TITLE
How can I use CML with Github actions that run for more than 24 hours?

### ISSUE THREAD

**Issue by haimat** [iterative/cml#1362]
We use CML with Github CI actions that can sometimes run longer than 24 hours. However, [according to the Github docs][1] after 24 hours the `GITHUB_TOKEN` expires. In the Github workflow run log I get the error message *"Unable to extend GITHUB_TOKEN expiration time due to: GITHUB_TOKEN has expired."* This is a bummer because we need this token at the end of this lengthy CI action for CML, i.e. after these 24 hours.

Is there a way to extend the lifetime of the `GITHUB_TOKEN` for a CI workflow?  
Or if not, what other options do I have for such CI actions with CML?

  [1]: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Comment by 0x2b3bfa0** [comment]
Related to discord#cml/1077932928761335899

**Comment by 0x2b3bfa0** [comment]
@haimat, as suggested by @dacbd on Discord, you can use a [personal access token](https://cml.dev/doc/self-hosted-runners#personal-access-token) instead of the default `GITHUB_TOKEN` for authentication.

**Comment by 0x2b3bfa0** [comment]
I believe that, instead of https://github.com/iterative/cml/issues/1362#issuecomment-1450397043, the solution to this problem would rather pass the token to CML: 🤔 

```yaml
- uses: iterative/setup-cml@v1
- run: cml comment create # or whatever
  env:
    CML_TOKEN: ${{ secrets.GH_PAT }}
```

**Comment by dacbd** [comment]
depends on what action is being prevented `cml comment` vs say `git commit`? doesn't really matter the solution is still to use a personal access token and not the default runner one.

**Comment by haimat** [comment]
Hello again and thanks for your reply. I am happy to use a PAT, however, I don't to allow too much for it.
Could you please tell me what permissions I need to give it, whem using a *New fine-grained personal access token*?

**Comment by dacbd** [comment]
@haimat sorry for the late reply, without knowing what your workflow needs to do I don't think we can exactly answer this.

In general, it needs:
- `Administration` for registering a runner via `cml runner`
- `Content` to clone and create commits
- `Pull requests` for `cml pr`

You might need another one or less again depending on the workflow.
