### ISSUE TITLE
libcudnn files not found on GCP linux worker

### ISSUE THREAD

**Issue by evamaxfield** [iterative/cml#1367]
Hey all!

I have been using GCP runners spun up with CML for the last little bit and have made a ton a progress. Yesterday, things started to fail to a new error I have never seen before:

`libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory`

Link to logs: https://github.com/CouncilDataProject/seattle/actions/runs/4442633425/jobs/7799134087#step:9:865

I checked for a new CML release but didn't see anything. Could this be on Nvidias / GCPs side of things?

I remember from a prior issue thread that libcudnn is installed as a part of CML worker creation.

**Comment by evamaxfield** [comment]
Started a new run after your PR: https://github.com/CouncilDataProject/seattle/actions/runs/4443618738/jobs/7801139879#step:4:14

CUDA v12 might be the issue? I feel like it used to be CUDA v11.8

**Comment by evamaxfield** [comment]
Workflow is still running, we will see if it fails with same error though

**Comment by evamaxfield** [comment]
Workflow failed with same error after the pip upgrade

**Comment by evamaxfield** [comment]
Sorry to bother, any idea as to what might be happening?

**Comment by evamaxfield** [comment]
While I assume the problem is still happening, this pushed me to actually use a docker container as the base so I have resolved it on my end.

**Comment by dacbd** [comment]
Sorry for not responding sooner, I think the specifics of this would
require a decent amount of time to debug and find a solution, and may also
cause issues for other users.

It's good to hear that using a docker image resolved the problem, we also
have a hidden flag `--cloud-image` you can change the base image with, and
any debian or Ubuntu based distro should work fine.

**Comment by evamaxfield** [comment]
Ahhh cool good to know. No worries at all. I should have tried docker first.
