### ISSUE TITLE
BitBucket DataCenter/Server support

### ISSUE THREAD

**Issue by barseghyanartur** [iterative/cml#140]
It would be good to see BitBucket (software, self hosted) supported as well.

**Comment by tbugfinder** [comment]
Which pipeline engine should be raised after?
Jenkins?

**Comment by barseghyanartur** [comment]
Preferably it should be configurable. I use bamboo.

**Comment by dmpetrov** [comment]
@tbugfinder it is a great question! We are trying figure out the priorities. Please create an issue for Jenkins if it is important for you.

@barseghyanartur is right - it should be configurable and we need to support many of the pipeline engines.

**Comment by davislf2** [comment]
Same here. I'd love to see Bitbucket + Jenkins as well. Thanks.

**Comment by elleobrien** [comment]
Update @barseghyanartur: we've just added [Bitbucket Cloud support](https://github.com/iterative/cml/wiki/CML-with-Bitbucket-Cloud) and Bitbucket Server w/configurable CI systems (Jenkins or Bamboo) is currently in the works!

**Comment by dmpetrov** [comment]
@elleobrien should we close this issue?

**Comment by elleobrien** [comment]
Nope, not till we have Bitbucket Server support done

**Comment by 0x2b3bfa0** [comment]
https://community.atlassian.com/t5/Bitbucket-Pipelines-articles/Bitbucket-Pipelines-Runners-is-now-in-open-beta/ba-p/1691022

**Comment by 0x2b3bfa0** [comment]
See also: https://snake-ci.com

**Comment by weidenka** [comment]
Could you give an estimate when we could expect an integration of BitBucket Server + Bamboo?

**Comment by casperdcl** [comment]
We've just released support for Bitbucket Cloud Pipelines (#798, #646) in [CMLv0.16.0](https://github.com/iterative/cml/releases/tag/v0.16.0)!

Docs are at https://cml.dev/doc/self-hosted-runners?tab=Bitbucket.

**Comment by weidenka** [comment]
The issue was about BitBucket Server. Is this now supported? I though the last post was related to BitBucket Could Pipelines.

**Comment by 0x2b3bfa0** [comment]
Bitbucket Server is not supported yet

**Comment by casperdcl** [comment]
- "Bitbucket DataCenter/Server" is not supported yet (this issue).
- "Bitbucket Cloud Pipelines" is supported (related issue, may make this one redundant for some but not all users?).
