### ISSUE TITLE
Feature request: Azure DevOps Pipelines support

### ISSUE THREAD

**Issue by n-a-sz** [iterative/cml#142]

**Comment by DavidGOrtega** [comment]
@n-a-sz thanks for the request! I' looking into this. Do you setup your ML workflows with this CI/CD?

**Comment by vanderGoes** [comment]
@DavidGOrtega Any ideas how to add this feature? Just like @n-a-sz I'd like to use cml in Azure DevOps pipelines. We use these pipelines to ci/cd them to Azure ML studio. Happy to contribute to this feature.

**Comment by DavidGOrtega** [comment]
@vanderGoes Azure DevOps is definitely in our Pipeline, we have announced the 0.3.0 prerelase where we have been focused on the runner. 
We are going to do a quick recap on whats needed in you are willing to help with a PR.

**Comment by vanderGoes** [comment]
@DavidGOrtega Great to hear that, let me know when you want to jump into this feature.
