### ISSUE TITLE
How to setup multiple GPU for CML runner in GCP

### ISSUE THREAD

**Issue by RTae** [iterative/cml#1430]
## Summary / Background

I would like to use multiple GPU to training my model using CML runner but I could't find a method to set number of GPU. Moreover, when I select a instance with 2 GPU the TPI will rise error about should set number of accelerator to two, but it does't have a argument to set it

## Scope
- Create CML runner with multiple GPU instance

**Comment by CptCaptain** [comment]
In case you haven't solved it yet, I create my runners like this:
```
          cml runner launch \
              --cloud=gcp \
              --cloud-type=n1-highmem-2+nvidia-tesla-t4*2 \
              --labels=cml-gpu
```
That allows for specifiyng any viable number of GPUs.

**Comment by RTae** [comment]
@CptCaptain  Thank you, it work !!
