### ISSUE TITLE
Change RUNNER_REPO in provisioning examples

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#145]
Repo name can be guessed in the workflow

Gitlab
```yaml
RUNNER_REPO=$CI_PROJECT_URL
```

Github
```
RUNNER_REPO="https://github.com/${GITHUB_REPOSITORY}"
```

Both changes in cml.dev and readme.md

**Comment by andronovhopf** [comment]
Awesome I think this is going to save us a lot of help tickets down the road

**Comment by andronovhopf** [comment]
Fixed on site & readme.
