### ISSUE TITLE
Make it possible to use CML runner with Ubuntu 24.04

### ISSUE THREAD

**Issue by iirekm** [iterative/cml#1475]
My scripts are tested with Ubuntu 24.04 and work great with plain GitHub Actions.

Then I wanted to switch to CML-created runners. Unfortunately CML AWS instance uses Ubuntu 18, CML Docker image uses Ubuntu 20. All of them are too old, with old software, probably with security issues, not even worth backporting :-(

Is there at least a workaround, e.g. a Docker image with Ubuntu 24.04 with all required dev tools installed? Or a way to pass AMI ID to `cml runner launch`?

**Comment by 0x2b3bfa0** [comment]
Use something like `cml runner launch --cloud-image='ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-*'`
https://github.com/iterative/cml/blob/5e9fcd26e9683db26a429eb5f34b989134694d4b/bin/cml/runner/launch.js#L603

**Comment by 0x2b3bfa0** [comment]
It's not part of our publicly documented API but... it works! ™️
