### ISSUE TITLE
Support for notebooks diff

### ISSUE THREAD

**Issue by dmpetrov** [iterative/cml#148]
A user asked for reviewnb support. Further investigation is needed.

**Comment by dmpetrov** [comment]
I bit more context. I'm not 100% sure we need to support reviewing (it looks like it is proprietary).
What we actually need - to understand Jupiter user's workflow better and solve some of the issues in the CI part. **Any ideas are welcome!**

**Comment by dmpetrov** [comment]
Note - take a look at:
1. https://github.com/nteract/papermill - parametrize notebooks
2. https://github.com/jupyter/nbdime - diff and merge notebooks

**Comment by DavidGOrtega** [comment]
> https://github.com/jupyter/nbdime - diff and merge notebooks

Thats the tool Im evaluating

**Comment by casperdcl** [comment]
Can this be closed?

```bash
pip install nbdime
echo '```diff' >> report.md
nbdiff <old_sha> <new_sha> <file.ipynb> >> report.md
echo '```' >> report.md
cml send-comment report.md
```

Not sure if @iterative/studio wants to render `nbdiff-web` output though?
