### ISSUE TITLE
cml.dev Gitlab's Cloud computing is missing tags

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#153]
While the [project demo](https://gitlab.com/iterative.ai/cml-cloud-case/-/blob/master/.gitlab-ci.yml) seems to be fine the sample code seems to be missing the tags

![image](https://user-images.githubusercontent.com/414967/87241831-23b42a80-c427-11ea-8be4-040aff9d9bec.png)

**Comment by andronovhopf** [comment]
@DavidGOrtega correct- are tags necessary for the example?

**Comment by DavidGOrtega** [comment]
@andronovhopf yes, if not the cloud runner wont pick the job

**Comment by andronovhopf** [comment]
Have just merged change to website, should be live in a few min

https://github.com/iterative/cml-website/pull/26
