### ISSUE TITLE
Feature request: Jenkins Pipeline support

### ISSUE THREAD

**Issue by tbugfinder** [iterative/cml#154]
It would be good to have an integration with Jenkins pipelines

**Comment by PuneethaPai** [comment]
we can use docker image [`dvcorg/cml-py3:latest`](https://hub.docker.com/r/dvcorg/cml-py3) as Jenkins Agent. To understand more on using Docker with Jenkins check out their [documentation](https://www.jenkins.io/doc/book/pipeline/docker/).


You can run your usual stages and then finally use `cml-container` to run cml-specific commands. 

**Inside CML Container you can use all `cml-<cmd>`**.

For example I have used cml-send-comment command here. 

Your pipeline syntax can look something like this:
```groovy
pipeline {
    agent any
    stages {
        stage('Your stages ...') {
                // Define all your stages here
        }
        stage('Inside CML Container') {
            agent {
                docker {
                    image 'dvcorg/cml-py3:latest'
                    args '-v $WORKSPACE:/home/runner'
                }
            }
            stages {
                stage('CML send Reort') {
                    steps {
                        withCredentials(
                            [
                                ... // Export env variable `REPO_TOKEN`
                            ]
                        ) {
                            sh '''
                                date >> report.md
                                dvc metrics diff --show-md --precision 2 master >> report.md
                                cml-send-comment report.md
                            '''
                        }
                    }
                }
            }
        }
    }
}
```

More details you can check this example file in my demo repo [here](https://github.com/PuneethaPai/RPPP/blob/cml/Jenkinsfile.cml#L33).

**Comment by dacbd** [comment]
CML has stand-alone binaries that can be installed on the Jenkins server now.
The dvcorg/cml-py3 image is deprecated users should use the docker images from ghcr.io / in the `Packages` side panel on GitHub. 

Feel free to open a new issue if any specific issues arise in relation to uses from jenkins.

**Comment by casperdcl** [comment]
Should add docs to https://cml.dev/doc before resolving?

**Comment by dacbd** [comment]
Please feel free to contribute, but we don't foresee us adding this feature anytime soon.
