### ISSUE TITLE
Suppress triggering for the pushes that don't affect the result

### ISSUE THREAD

**Issue by sarikayamerts** [iterative/cml#157]
Is there a way of triggering on not all the pushes but the ones that only affect the result of the model. Like if I fixed some typo, there is no need to generate the report etc., or in my environment, there are some modules that are responsible for ml models (call it ml module) and the others (call it non-ml). I am assuming that the commits in non-ml modules will not affect the result in the ml module. In cases like these, I might want to suppress triggering. Can we currently do this, if so, how? If not, will it be useful to add this feature?

**Comment by DavidGOrtega** [comment]
Hi @sarikayamerts normally all the CI vendors can skip the build adding ```[ci skip]``` or ```[skip ci]``` in your commit comment, [here a list](https://github.com/srz-zumix/ci-skip). 
If you are setting Gitlab, congrats, you don't have to go further, however in Github you will have to add small change in your workflow.

```yaml
jobs:
  train:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
```

Hopefully this trick works for you 😃

**Comment by DavidGOrtega** [comment]
@sarikayamerts Feel free to reopen if you still have any issue.

**Comment by dmpetrov** [comment]
@sarikayamerts could you please clarify what is the problem with multiple triggering?
1. Is it about computation heavy\slow operations or
2. Is it about multiple similar commits in the PR?

**Comment by DavidGOrtega** [comment]
@dmpetrov I far as I understood he just want to commit in the repo without having to train.

**Comment by sarikayamerts** [comment]
@dmpetrov Yes, my first concerns were related with time-consuming operations, not the similar commits. But that might be a different use-case for that obviously. Thanks for the explanation @DavidGOrtega
