### ISSUE TITLE
self-hosted CML Runner executor not supported

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#169]
Launching the gpu runner in the logs appears executor not supported

```sh
`{"job":644109193,"level":"info","msg":"executor not supported","project":20009146,"referee":"metrics","runner":"LGtng_o9","time":"2020-07-17T12:54:05Z"}`
```

### How to reproduce

Setup a workflow with self-hosted runner in GL, launch the runner and do a commit to run the CI. 

```sh
docker run --name runnerg --rm \
    -e RUNNER_IDLE_TIMEOUT=1800 \
    -e RUNNER_LABELS=cml \
    -e RUNNER_REPO=$REPO \
    -e repo_token=$TOKEN \
    dvcorg/cml-gpu-py3-cloud-runner
```

Its probably because the $RUNNER_EXECUTOR is empty or invalid

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, is this issue still relevant after the migration to Terraform?

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 yes, its the executor in gl (docker, etc...) but I think its fixed now since we are always doing docker in docker inside GL

**Comment by DavidGOrtega** [comment]
Docker in docker as stated
