### ISSUE TITLE
Tests fail within external PRs

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#183]
External PRs does not pass the tests due to token autentication

```
 ● CML e2e › cml-send-comment

    Command failed: node ./bin/cml-send-comment.js comment.md
    Resource not accessible by integration
```
[log here](https://github.com/iterative/cml/pull/181/checks?check_run_id=922046907)

**Comment by 0x2b3bfa0** [comment]
This looks like a good use case for [GitHub Environments](https://docs.github.com/es/actions/reference/environments), and a logic continuation to the changes required by #217.
