### ISSUE TITLE
Rewrite to typescript

### ISSUE THREAD

**Issue by lipovsek** [iterative/cml#187]
Hy, I think it is great idea to use typescript instead of javascript for maintainability and better code. I can rewrite this to typescript in near future, is anyone agreeing with me?

**Comment by DavidGOrtega** [comment]
@lipovsek thanks for your support. Ts VS ES6 is something that we have been discussing internally before starting the project and we thought ES6 would suffice. 

But we are open to discussion 🙂

**Comment by DavidGOrtega** [comment]
Closed due to inactivity
