### ISSUE TITLE
generic driver examples

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#191]
This is a request for feasibility tests & documentation/examples.

Using `docker-machine --driver=generic` would allow connecting to a self-hosted server via ssh.
This would, for example, allow institutions to make use of their own GPU clusters.

Note that this is not the same as a self-hosted [runner](https://docs.github.com/en/actions/hosting-your-own-runners). Runners are actively discouraged by GitHub for public repos due to security.

Using `cml` with `docker-machine --driver=generic`, on the other hand, only requires ssh access (using `id_rsa` injected via secrets) to a server with docker installed. The idea would be to run CI/CD in isolated containers on the server, without needing an IT department to support and monitor a private runner.

Possible issues to be addressed:

- ssh tunneling via an intermediate host
- potential need to forward more than just the ssh port

**Comment by DavidGOrtega** [comment]
Hi @casperdcl 

> Note that this is not the same as a self-hosted runner. Runners are actively discouraged by GitHub for public repos due to security. 

You mean self-hosted runners are discouraged? Could you please elaborate more?

**Comment by casperdcl** [comment]
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories

**Comment by casperdcl** [comment]
> At the very end... you would run a self-hosted runner right? I mean, that a self-hosted runner needs to be attached to the workflow.

That's not good for public repos

**Comment by DavidGOrtega** [comment]
Ah! I see.

If you run the self-hosted runner with CML image (as I enforce to do) you will be safe since its being run inside a docker container.

```
docker run --name runner --rm
-e RUNNER_IDLE_TIMEOUT=1800
-e RUNNER_LABELS=gpu
-e RUNNER_REPO=$myrepo
-e repo_token=$mytoken
dvcorg/cml-py3
```

**Comment by DavidGOrtega** [comment]
You always need a runner hosted by GH or by you. There is no other way to execute pickup the jobs from the workflow. 

Main reasons  to use the CML image is to:
 - Ensure experiment reproducibility
 - Prevent this GH vulnerability

**Comment by casperdcl** [comment]
Runners hosted by GH are "safe" in the sense they are already clean containers.
Anyway apart from security there are other reasons to consider `--driver=generic`

To be clear main point of this issue is to add a `--driver=generic` example to https://github.com/iterative/cml#allocating-cloud-resources-with-cml (rather than `--driver=amazonec2`).

**Comment by DavidGOrtega** [comment]
> Runners hosted by GH are "safe" in the sense they are already clean, isolated containers which PRs could execute malicious code on without you caring.

starting your runner with CML image is isolating the environment like GH images do. Am i Missing something?

**Comment by DavidGOrtega** [comment]
@casperdcl I think I got you. Your concern is someone using i.e. your gpus, machines... right? Yeah, the problem with ```docker-machine --driver=generic``` is making those machine public. I worked on a project to be able to deploy a model served by gpus in private networks using a tunnel ala ngrok, joining a public api with consul.

A tunnel would work... As far as I remember there is even a wrapper for ngrok in nodejs... but maybe this is beyond this scope...

@dmpetrov ?

**Comment by casperdcl** [comment]
There's more than security to talk about. Really all of the reasons someone may want to use `--driver google` instead of `--driver amazonec2` would also apply. Maybe `--driver generic` would allow access to local data which can't (won't) be uploaded to the cloud.

**Comment by DavidGOrtega** [comment]
I see, but the self-hosted runner is not giving you that issue... is it? I can attach in my workflow that external storage with a secret and just forking the public repo wont give you access to the attached storage even if you are able to use the runner

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, is this issue still relevant after migrating away from `docker-machine` _et alii_?

**Comment by 0x2b3bfa0** [comment]
Carbon copy to @casperdcl

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 @casperdcl we should deprecate this now. I think is pretty safe.
This ticket is not valid anymore.
