### ISSUE TITLE
Image pull takes a bit

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#211]
It takes > 1min to initialize containers (pull).
Is there a way to cache or may be GH already using some caching?

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, as far as I know there isn't any possible optimization on that side, apart from using `ghcr.io` images from #267.

**Comment by 0x2b3bfa0** [comment]
We've facilitated caching of existing layers through #530 and GitHub already keeps a copy of the latest Ubuntu image in some kind of cache. Apart from that, there isn't anything we can do. Feel free to reopen if you have in mind any other potential optimization.
