### ISSUE TITLE
 Unable to verify the first certificate error in cml-send-comment

### ISSUE THREAD

**Issue by JLC7** [iterative/cml#218]
Thanks for creating this tool!

We currently have our shared gitlab runners configured to use docker on our own linux servers. I am trying to run the cml-base-case example. I keep encountering an error with `cml-send-comment` line in the cml-base-case code in gitlab. Is there a way to pass in the path of the the ssl certificate like `/etc/ssl/certs/`?

Here is a screen shot of when it fails.
![image](https://user-images.githubusercontent.com/17368281/90294071-6ad47780-de3a-11ea-81eb-82d5f6436171.png)

I tried creating my own runner manually and edited the /etc/gitlab-runners/config.toml file to point to the paths but not having luck. For example I tried setting:

```
volumes = ["/cache",
               "/etc/gitlab-runner/certs:/etc/gitlab-runner/certs",
	       "/etc/ssl/certs:/etc/ssl/certs"
    ]

```

Nothing I tried work so far. Any guidance on what I can try?

Thanks

**Comment by DavidGOrtega** [comment]
@JLC7 
take into account that CML is actually a docker image. What you are doing is adding the certs to your runners however CML is still running inside a container. So you should expose it to them.

A easy and effective way would be adding a small code in the workflow to setup the cert from a secret like we use to do with google credentials. Fr that you have to save your SSL as a settings->CI/CD env variable 

![image](https://user-images.githubusercontent.com/414967/90385392-5cc56780-e083-11ea-9e60-36c40588a32e.png)


the in the ci.yaml file setup it with a simple command. 

```
echo $SSL_CERT > $MY_PATH
```

with this setup you don't have to change your runners or anything else.

**Comment by DavidGOrtega** [comment]
@JLC7 did you solved your issue?

**Comment by JLC7** [comment]
It led me to a solution. I updated the dockerfile by copying the cert into it and added the following line to the yml

`- export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/ca-cert.crt`

But trying...

```
`- echo $SSL_CERT > $MY_PATH
 - export NODE_EXTRA_CA_CERTS=$MY_PATH
```

ended up passing the actual contents of the certificate instead of a _path_ to the certificate to NODE_EXTRA_CA_CERTS and I wasn't sure how to get around that.

Let me know if there would've been a simpler way. Thanks for your help!

**Comment by DavidGOrtega** [comment]
> ended up passing the actual contents of the certificate instead of a path to the certificate to NODE_EXTRA_CA_CERTS 

@JLC7 How that can be possible?
```
MY_PATH='mycert.crt'
echo 'HELLO CERT' > $MY_PATH
export NODE_EXTRA_CA_CERTS=$MY_PATH

echo $NODE_EXTRA_CA_CERTS
cat $MY_PATH
```
the output
```
mycert.crt

HELLO CERT
```

as expected. At this point the cert exists at $MY_PATH and NODE_EXTRA_CA_CERTS contains $MY_PATH

**Comment by DavidGOrtega** [comment]
> I updated the dockerfile by copying the cert into it 

Take care with that, if your image is public you are exposing your keys.

**Comment by DavidGOrtega** [comment]
> Let me know if there would've been a simpler way

Another option would be make accesible the file with the ```container.volumes``` option

```yaml
jobs:
  cml_run:
    container:
      image: dvcorg/cml:latest
      volumes: ['path_to_my_cert:/my_cert.crt']
   env:
      NODE_EXTRA_CA_CERTS: '/my_cert.crt'
```

**Comment by JLC7** [comment]
I resolved the issue. Setting the gitlab variable type to File rather than Variable helped. All I needed then was 
`- export NODE_EXTRA_CA_CERTS=$SSL_CERT`
Thanks for the help.
