### ISSUE TITLE
GitLab partnership - submit a change in GL partner page.

### ISSUE THREAD

**Issue by dmpetrov** [iterative/cml#226]

**Comment by DavidGOrtega** [comment]
@dmpetrov should we close this?

**Comment by 0x2b3bfa0** [comment]
I don't have enough context on this issue, but having presence in the [GitLab Technology Partners](https://about.gitlab.com/partners/technology-partners) page could be really nice.

**Comment by 0x2b3bfa0** [comment]
Anyhow, it looks like it's not <kbd><b>In-progress</b></kbd> right now and we should, at least, relocate it.

**Comment by casperdcl** [comment]
done
