### ISSUE TITLE
cml-publish could support artifacts

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#233]
Coming from [discord](https://discord.com/channels/485586884165107732/728693131557732403/751012718856634398)

We could add a flag to be able to publish artefacts. Major benefits:
 - Not dealing with privacy
 - Bigger files

Drawbacks:
 - In GH artefacts will expire after 90 days opposed to GL where they can be set to never expire.

**Comment by DavidGOrtega** [comment]
@dmpetrov @elleobrien

**Comment by elleobrien** [comment]
This seems fine, as long as folks are aware of the GH expiration no problem. 

What would the syntax look like? `cml-publish <file> --artifact`?

**Comment by DavidGOrtega** [comment]
> What would the syntax look like? cml-publish <file> --artifact?

That sounds good to me

**Comment by DavidGOrtega** [comment]
We have an issue regarding vendor alignment.
In Gitlab we don't have a way to upload the artifacts, however we always had the [uploads API](https://docs.gitlab.com/ee/api/projects.html#upload-a-file).

In GH we can actually use the artifacts using the @actions/artifacts lib, however there is a big limitation of 90 days expiration (we knew this).

So one solution would be instead of ```--artifact``` I would propose  ```--native``` where we would use the upload capabilities that we have in every vendor logging possible undesired effects like expiration.

Let me know your thoughts @dmpetrov @elleobrien

**Comment by dmpetrov** [comment]
@DavidGOrtega it looks like the APIs are different. It might be fine to have two separate methods for GH and GL.

Also, it looks like GL API similar to our `cml-publish`. It might be part of it with some option like `--gitlab-upload`.
