### ISSUE TITLE
What would be the best high level API to cloud resources

### ISSUE THREAD

**Issue by dmpetrov** [iterative/cml#244]
Right now the API is AWS specific (expected for today). From PR https://github.com/iterative/cml/pull/230:

```
          test-cml-cloud-runner \
            --instance_ami ami-03ba3948f6c37a4b0 \
            --instance_type t2.micro \
            --region us-west-1 \
            --repo_token ${repo_token} \
            --runner_repo ${RUNNER_REPO} \
            --runner_labels ${RUNNER_LABELS} \
            --runner_idle_timeout=120 \
            --gpus all
```

What would be the best API to abstract out all the cloud providers? What should be in our TF-provider and what not? Do we need any high-level templates like `cpu`, `gpu`, `gpu-large` instead of using AMI-s?

@DavidGOrtega @elleobrien it would be great to hear your opinions.

**Comment by DavidGOrtega** [comment]
In paperspace networking is only for business

![image](https://user-images.githubusercontent.com/414967/93056498-c9c12280-f66c-11ea-90f3-0d0e34f9d6ae.png)

**Comment by DavidGOrtega** [comment]
Up to 2TB hardisk

![image](https://user-images.githubusercontent.com/414967/93056681-0d1b9100-f66d-11ea-8497-89c6300d9412.png)

**Comment by DavidGOrtega** [comment]
5 GPU machines, all the same only changes the GPU and 10 without GPU. 

![image](https://user-images.githubusercontent.com/414967/93056840-4a801e80-f66d-11ea-96a7-fcd99864db91.png)

![image](https://user-images.githubusercontent.com/414967/93056881-566be080-f66d-11ea-8d70-25bf53871994.png)


I would make like 5 where you can add GPU or not.

 - micro (no gpu available)
 - small (no gpu available)
 - medium (no gpu available)
 - large
 - x large

**Comment by DavidGOrtega** [comment]
There is actually no need to specify the ami, the ami only needs to have nvidia and docker to run the runner image so we can generate amis with that so the real image is the docker image that the user would like to use

**Comment by DavidGOrtega** [comment]
--repo_token ${repo_token} \
--runner_repo ${RUNNER_REPO} \
--runner_labels ${RUNNER_LABELS} \
--runner_idle_timeout=120 \

changed to

--repo-token
--repo
--labels
--idle-timeout
--name

we have - vs _ in all the other commands

**Comment by DavidGOrtega** [comment]
--region is fine to me

**Comment by DavidGOrtega** [comment]
So for me would be 
--image default:default:dvcorg/cml:latest
--repo-token default: can be read from workflow
--repo default:can be read from worflow
--labels comma delimited list default:
--idle-timeout default:5min
--name default:random

**Comment by DavidGOrtega** [comment]
this is how the first mapping looks for regions and instance types:

```go
func getRegion(d *schema.ResourceData) string {
	instanceRegions := make(map[string]string)
	instanceRegions["us-east"] = "us-east-1"
	instanceRegions["us-west"] = "us-west-1"
	instanceRegions["eu-north"] = "eu-north-1"
	instanceRegions["eu-west"] = "eu-west-1"

	region := d.Get("region").(string)
	if val, ok := instanceRegions[region]; ok {
		region = val
	}

	return region
}

func getInstanceType(d *schema.ResourceData) string {
	instanceTypes := make(map[string]string)
	instanceTypes["m"] = "m5.2xlarge"
	instanceTypes["l"] = "m5.8xlarge"
	instanceTypes["xl"] = "m5.16xlarge"
	instanceTypes["mk80"] = "p2.xlarge"
	instanceTypes["lk80"] = "p2.8xlarge"
	instanceTypes["xlk80"] = "p2.16xlarge"
	instanceTypes["mtesla"] = "p3.xlarge"
	instanceTypes["ltesla"] = "p3.8xlarge"
	instanceTypes["xltesla"] = "p3.16xlarge"

	instanceType := d.Get("instance_type").(string)
	if val, ok := instanceTypes[instanceType+d.Get("instance_gpu").(string)]; ok {
		instanceType = val
	}

	return instanceType
}
```

setting the instance type and gpu type:
```tf
resource "iterative_machine" "machine" {
  region = "us-west"
  instance_type = "xl"
  instance_gpu = "tesla"
}
```

As you might have noted if the key does not exist takes the one given so you can still choose an instance type and region from AWS

**Comment by DavidGOrtega** [comment]
@dmpetrov @elleobrien lets move this to [terraform-provider-iterative](https://github.com/iterative/terraform-provider-iterative)
