### ISSUE TITLE
support organisation-level runners

### ISSUE THREAD

**Issue by JamesMowatt** [iterative/cml#271]
Github allows runners to be set up at an organization level.

On a youtube tutorial from DVCorg, I had asked if it was possible to set up a runner at the organisation level and was told to drop a feature suggestion here.

- [x] GitHub (#277)
- [ ] GitLab
- [ ] Bitbucket

**Comment by JamesMowatt** [comment]
Github support added with #277 Gitlab to follow

**Comment by dacbd** [comment]
Please feel free to contribute, but we don't foresee us adding this feature anytime soon.
