### ISSUE TITLE
Destroy panic error handling

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#278]
If runner can not be destroyed by tf the runner could send back a comment to the repo with a link to the machine to be disposed.

Your [machine](https://us-west-1.console.aws.amazon.com/ec2/v2/home?region=us-west-1#InstanceDetails:instanceId=i-075XXXXXXXX) could not be removed!!! You have to do it manually to prevent further charges.

**Comment by dacbd** [comment]
perhaps some c/p actions/(gitlab -eq) that users can run a schedule is a better solution? 

- https://github.com/iterative/cml/issues/973#issuecomment-1146149999
- https://github.com/dacbd/gcpcc#usage
- https://discord.com/channels/485586884165107732/728693131557732403/984180090114019368

**Comment by omesser** [comment]
my 2 cents is that this is probably p1 feature - notifying when a machine stays up is an important failure.
doing "GC" on the user level is great design, but the tool needs to be "responsible" and "friendly" with failures to be feature-complete
