### ISSUE TITLE
oauth for bitbucket cloud

### ISSUE THREAD

**Issue by elleobrien** [iterative/cml#289]
Hey @DavidGOrtega, here's where I wanted to get your opinion-

Most of the APIs we've worked with so far use simple authentication with a Personal Access Token (PAT). However, the BitBucket Cloud interface doesn't provide a way to get PATs, and the API uses oauth:

https://developer.atlassian.com/cloud/bitbucket/oauth-2/

What would you say is the right way to authenticate so users can do POST operations with the API?

**Comment by DavidGOrtega** [comment]
Hey @elleobrien looks like bitbucket server and cloud supports  a basic auth schema:

https://developer.atlassian.com/server/bitbucket/how-tos/example-basic-authentication/
https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/

**Comment by elleobrien** [comment]
I see! Thanks for finding this- 

are there any security risks with setting your password as a secret?

**Comment by elleobrien** [comment]
Also this link: https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/

Seems to be for Jira, not BitBucket Cloud. Are you sure this works for BitBucket?

**Comment by DavidGOrtega** [comment]
@elleobrien docs says it works. Let me do a test in my bitbucket cloud account

> are there any security risks with setting your password as a secret?

No, its a secret in the CI, like the AWS credentials. Its fine.

**Comment by elleobrien** [comment]
Yep it worked with password. Weirdly not with [Atlassian API token](https://confluence.atlassian.com/cloud/api-tokens-938839638.html), but with password it's good. 

Works:
```
curl https://api.bitbucket.org/2.0/repositories/elleobrien/elle-repo/commit/c912a75b9ce8eb4e2b953343f94a9f8a2e5874d9/comments/ \
  -X POST -u elleobrien:<pw> \
  -H 'Content-Type: application/json' \
  -d '{"content": {"raw": "Made with API ;P!"}}'
```
<img width="242" alt="Screen Shot 2020-10-06 at 12 39 39 PM" src="https://user-images.githubusercontent.com/29716724/95252245-94be7080-07d1-11eb-8a14-47fa12a31b82.png">

Interestingly doesn't work (also tried `-u <my email>:$API_TOKEN`):
```
curl https://api.bitbucket.org/2.0/repositories/elleobrien/elle-repo/commit/c912a75b9ce8eb4e2b953343f94a9f8a2e5874d9/comments/ \
  -X POST -u elleobrien:$API_TOKEN \
  -H 'Content-Type: application/json' \
  -d '{"content": {"raw": "Made with API ;P!"}}'
```
