### ISSUE TITLE
GitLab: Alternative approach to cml-send-comment and cml-publish

### ISSUE THREAD

**Issue by tmaier** [iterative/cml#298]
- CML currently posts its results as a comment to a merge request

## This raises multiple concerns

- One user must expose a PRIVATE_TOKEN as secret variable in the project. There is the danger of leaking the credentials and thus, access rights
- cml-publish stores images on an external server, which is again a security validation in certain scenarios. (see #291)

## Proposed solution

- Embed the images as [base64 encoded string in Markdown](https://superuser.com/questions/1199393/is-it-possible-to-directly-embed-an-image-into-a-markdown-document) instead of uploading them to an external server
- Create an HTML report from the markdown report
- Store the HTML report as [GitLab CI artifact](https://docs.gitlab.com/ee/ci/yaml/#artifacts)
- Use the [artifacts:expose_as](https://docs.gitlab.com/ee/ci/yaml/#artifactsexpose_as) feature to expose it in the the Merge Request UI with a proper name

**Comment by DavidGOrtega** [comment]
@tmaier this proposal is for GL mostly right?

The thing is that we have to provide the same API for any scm vendor. Said that I really like the base64 images idea but its not supported in GH however I might find good to offer an base64 output in cml-publish

> One user must expose a PRIVATE_TOKEN as secret variable in the project. There is the danger of leaking the credentials and thus, access rights

I don't see the issue here, its a secret inside your scm. They already know it and there is not way to retrieve it because its a secret.

**Comment by fkjogu** [comment]
An additional base64 option wouldn't hurt scm agnosticism, so I do not see a downside. Or to put it differently, I like the idea 👍 

This could partly also solve the issues with proxies #336, or if I am not allowed to share pictures/plots with external providers.

**Comment by fkjogu** [comment]
For people navigating here through search, I'd like to point out the now possibility to use Gitlabs Artifact system within CML with something like
```
vl2png vega.json | cml-publish --md --gitlab-uploads >> report.md
```

**Comment by DavidGOrtega** [comment]
![Hello World](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEYAAAAUCAAAAAAVAxSkAAABrUlEQVQ4y+3TPUvDQBgH8OdDOGa+oUMgk2MpdHIIgpSUiqC0OKirgxYX8QVFRQRpBRF8KShqLbgIYkUEteCgFVuqUEVxEIkvJFhae3m8S2KbSkcFBw9yHP88+eXucgH8kQZ/jSm4VDaIy9RKCpKac9NKgU4uEJNwhHhK3qvPBVO8rxRWmFXPF+NSM1KVMbwriAMwhDgVcrxeMZm85GR0PhvGJAAmyozJsbsxgNEir4iEjIK0SYqGd8sOR3rJAGN2BCEkOxhxMhpd8Mk0CXtZacxi1hr20mI/rzgnxayoidevcGuHXTC/q6QuYSMt1jC+gBIiMg12v2vb5NlklChiWnhmFZpwvxDGzuUzV8kOg+N8UUvNBp64vy9q3UN7gDXhwWLY2nMC3zRDibfsY7wjEkY79CdMZhrxSqqzxf4ZRPXwzWJirMicDa5KwiPeARygHXKNMQHEy3rMopDR20XNZGbJzUtrwDC/KshlLDWyqdmhxZzCsdYmf2fWZPoxCEDyfIvdtNQH0PRkH6Q51g8rFO3Qzxh2LbItcDCOpmuOsV7ntNaERe3v/lP/zO8yn4N+yNPrekmPAAAAAElFTkSuQmCC)

**Comment by dacbd** [comment]
I feel this is closable? If not let's reopen with a clear change that needs to happen? @iterative/cml

**Comment by casperdcl** [comment]
seems to be closable in favour of #291
