### ISSUE TITLE
Metrics of experiments with different tech implementation

### ISSUE THREAD

**Issue by elleobrien** [iterative/cml#34]
This is a discussion point, not really an issue. I'm thinking about how metrics are displayed:

<img width="559" alt="Screen Shot 2020-03-26 at 3 28 14 PM" src="https://user-images.githubusercontent.com/29716724/77702830-9aabdd00-6f76-11ea-9e44-09002443cdd3.png">

I definitely want to know that I'm comparing two experiments in which hyperparameters of my model (here, the maximum depth of a random forest classifier `max_depth`) changed. But, whereas it makes sense to have a "diff" presented for the accuracy metric, I'm not so sure it matters to have a diff present for the hyperparameters. It's not a number we're trying to optimize (unlike accuracy diffs) and visually, it makes the display more cluttered.

I might suggest having a separate table for comparing hyperparameters that doesn't present diffs, just a side-by-side comparison. And then a table for comparing the output metrics, where I do care about the diff. Would this be challenging to implement? Maybe, for each distinct metric file, its own table? And then somewhere in project preferences a user could specify if we want diffs. 

Another way of thinking about this is that if I had a spreadsheet of experiments I was trying to compare, I would lay it out this way:

| experiment id |  parameterA |  parameterB | parameterC | accuracy |
|-------------- |------------- | ------------- | ------------ | ---------- |
| 1bac226  | 24 | 5 | 140 | 0.899 |
| f90k153 | 24 | 2 | 140 | 0.9111 |

And then perhaps highlight the row containing the best experiment (assuming that we can specify somehwere if we want + or - for the metric). If you want the diff explicitly calculated, maybe put it in its own field below the table.

**Comment by DavidGOrtega** [comment]
Closed this is not relevant anymore. Belongs to the CML-DVC incarnation of CML
