### ISSUE TITLE
Q: How does RUNNER_IDLE_TIMEOUT exactly work / How to shutdown runners?

### ISSUE THREAD

**Issue by tholor** [iterative/cml#345]
Thanks for providing this excellent project! We currently try to integrate it into the pipelines of our open-source project. 

**Problem:** 
We are using custom runners on AWS and if the job succeeds, they just keep running forever. 

**Question:** 
How does RUNNER_IDLE_TIMEOUT work exactly? I suppose it's defined in seconds? How is the "idle status" being defined? Is it somehow based on CPU utilization?  

**Additional Context**
See the [workflow definition file ](https://github.com/deepset-ai/haystack/blob/4ed95f9f3fd58ff572c64e06539c2e51e6799785/.github/workflows/cml.yaml#L61)

**Comment by DavidGOrtega** [comment]
@tholor 👋 

RUNNER_IDLE_TIMEOUT is in seconds, when the runner is idle it will disconnect from the repo and will dispose the machine via docker machine.

There must be an error clearing the machine. One easy way to see it is not detaching the container 

```
docker run --name runner \
```

instead of 

```
docker run --name runner -d \
```

you can try this workflow for a quick test:

```yaml
name: benchmarks

on: [push]

jobs:
  deploy-cloud-runner:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml

    steps:
      - name: deploy
        env:
          repo_token: ${{ secrets.HAYSTACK_BOT_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
          VPC: ${{ secrets.AWS_CI_VPC }}
        run: |
          echo "Deploying..."
          RUNNER_LABELS="cml,aws"
          RUNNER_REPO="https://github.com/${GITHUB_REPOSITORY}"
          MACHINE="cml$(date +%s)"
          docker-machine create \
            --driver amazonec2 \
            --amazonec2-instance-type p3.2xlarge \
            --amazonec2-vpc-id $VPC \
            --amazonec2-region us-east-1 \
            --amazonec2-zone c \
            --amazonec2-ssh-user ubuntu \
            --amazonec2-ami ami-06a25ee8966373068 \
            --amazonec2-root-size 150 \
            $MACHINE
          eval "$(docker-machine env --shell sh $MACHINE)"
          (
          docker-machine ssh $MACHINE "sudo mkdir -p \
            /docker_machine && \
          sudo chmod 777 /docker_machine" && \
          docker-machine scp -r -q ~/.docker/machine/ \
          $MACHINE:/docker_machine && \
          docker run --name runner \
            --gpus all \
            -v /docker_machine/machine:/root/.docker/machine \
            --net host \
            -e DOCKER_MACHINE=$MACHINE \
            -e repo_token=$repo_token \
            -e RUNNER_LABELS=$RUNNER_LABELS \
            -e RUNNER_REPO=$RUNNER_REPO \
            -e RUNNER_IDLE_TIMEOUT=60 \
            dvcorg/cml-py3:latest && \
          sleep 20 && echo "Deployed $MACHINE"
          ) || (echo "Shut down machine" && docker-machine rm -y -f $MACHINE && exit 1)
```

You should see why docker machine is not able to get rid of the machine.

Im going to investigate it also.

Good news is that soon we are releasing a new and very simple way to manage this! 😉

**Comment by tholor** [comment]
Thanks a lot for the fast and detailed reply @DavidGOrtega !

I will try the workflow and check for errors.

**Comment by tholor** [comment]
I see an error in the logs for the above test workflow, but the ec2 machine got shutdown correctly this time :thinking:  

```
Unregistering runner
Shutting down docker machine
An error occurred: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.

Failed shutting down docker machine: Command failed: echo y | docker-machine rm cml1605636015
Error removing host "cml1605636015": UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: 5iQoEho7jxGj4PhXcFwMWLnCjAZoR9BD_gXqD8_-i8iWL6qPAq9xDikfqWkLum4AUSgGd7zbyt53OS_yUpbr4htHGacrUFIePVYol3-q2ksoxK6okgeJZWVYVSan-CPzZdoZ30-DgxtlHsQ3T2hmxlWOu0J-0WI82jKo5hMTCBRM_jyHLQwE2bG18M_JHOWpVQmhqSBgSkDK6pYb7b6w3oqsWZxuQtCE62XQKeEpI83gvBx3VPjy0m8_XjHreObtNSeJiYOk4TG9LQoAogTSGn9sN_8RALeOESZ3IialDuwzPn8mtqRV8Qn9UKmptH-8dCNJ8j9x88SCC1iykSkAhDX422g6ghO7FBKcmy8IRkkfll_oakMvOTkGl2wosNViR71wBs-Aqkb0xz9h65DX5_LKnPA9qctynaabyyIYku-qGU3C8K_GknO4-vP_T7gRxz1yArFh2mVMU69OVix2Llnd2rrzmNRIjLEMtZHR3NqtqPb01QQeFbMyGh1OH9sZuLdThc00PtykuZlsACVWtRZF0CEpmvHlJb16Mrc
	status code: 403, request id: 053cf7ac-66d1-442e-ace4-452a59ece1cc


Terraform destroy...
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.

Destroy complete! Resources: 0 destroyed.
Deployed cml1605636015 ```

See full logs [here](https://github.com/deepset-ai/haystack/pull/518/checks?check_run_id=1413840354)

**Comment by DavidGOrtega** [comment]
@tholor looks like a permissions issue. You will have to decode the error to know exactly what it is.
you have to run 

```
aws sts decode-authorization-message --encoded-message $msg | jq ".DecodedMessage | fromjson"
```

to see what it is.
You can run it locally with your AWS credentials

**Comment by DavidGOrtega** [comment]
My best bet is something related to the sub region.

**Comment by tholor** [comment]
Ok, it was missing permissions for "ec2:DeleteKeyPair". Will fix this, but I am still not sure if that's really related to the original problem of not shutting down the machine as in the above test I got the error, but the machine shut down correctly.
I will report back if the problem persists...

**Comment by DavidGOrtega** [comment]
@tholor thanks for checking. The issue might be sub regions, sometimes permissions are aligned between them.

**Comment by tholor** [comment]
Closing this one since the problem did not pop up anymore in the latest runs. 
However, I would still be glad to explore the new functionality that you mentioned here, once it's published: 

> Good news is that soon we are releasing a new and very simple way to manage this! wink
