### ISSUE TITLE
Setup cml without Docker using cml nodejs

### ISSUE THREAD

**Issue by khursani8** [iterative/cml#355]
How to setup cml w/o Docker, I cannot find tutorial how to use it

**Comment by khursani8** [comment]
I'm trying to follow this installation step https://github.com/iterative/cml/blob/c9ee8c2966761b8ca530606de9859125ef7034cf/docker/Dockerfile

![Screenshot from 2020-11-30 02-11-19](https://user-images.githubusercontent.com/5404903/100548791-14d4f400-32b2-11eb-9910-b6bd668a4f63.png)

Running at google colab instance

**Comment by dmpetrov** [comment]
I guess it is related to Colab comment in youtube ​https://www.youtube.com/watch?v=rVq-SCNyxVc&lc=Ugwar7w2bdz7wERTf0h4AaABAg.9FPR_VyF-um9Ge5OxOKzD2&feature=em-comments

`@DVCorg I think it will not work since Colab cannot install Docker(or more like can install Docker but cannot start the service)`

**Comment by khursani8** [comment]
Ohhh, I'm the one who comment that.

I'm trying to setup cml without Docker by following Dockerfile script since Docker cannot be run inside Google Colab.
Wondering if you guys can help me debug the problem

**Comment by DavidGOrtega** [comment]
@khursani8 two things:

 - Can you review that your repo_token has workflow permissions?
 - Have you installed the GH runner as seen in the Dockerfile?

```dockerfile
wget https://github.com/actions/runner/releases/download/v2.267.1/actions-runner-linux-x64-2.267.1.tar.gz && \
    tar xzf actions-runner-linux-x64-2.267.1.tar.gz && \
    ./bin/installdependencies.sh && \
```

**Comment by khursani8** [comment]
* Can you review that your repo_token has workflow permissions?
Yes, I'm following this step https://youtu.be/rVq-SCNyxVc?t=373, tick at repo & workflow permission

* Have you installed the GH runner as seen in the Dockerfile?
Yes, The only script I skip is installing tensorflow,nvidia and docker

**Comment by khursani8** [comment]
@DavidGOrtega 
You can use this notebook for reproducing the error
https://colab.research.google.com/drive/17okXPW4ccECokEGHL8MD0HTnb8qvFZuz?usp=sharing

need to fill your own:
RUNNER_REPO and repo_token

**Comment by DavidGOrtega** [comment]
👋  @khursani8 
is missing the RUNNER_PATH, thats the path where your GH runner lives after the installation and where the runner will create the CI env

**Comment by khursani8** [comment]
Hi @DavidGOrtega,

It works, thanks
