### ISSUE TITLE
prevent dockers from unregistered from github repo

### ISSUE THREAD

**Issue by gungui98** [iterative/cml#359]
Hi,
I am using a self-hosted machine to run but when finish the test, the container unregistered from the Github repo. How can I keep the container rather than unregistered it?

**Comment by DavidGOrtega** [comment]
👋 @gungui98 Im guessing that you are using our CML image to start the runner. Setting a ```RUNNER_IDLE_TIMEOUT=0``` will do the trick

**Comment by DavidGOrtega** [comment]
@gungui98 did it help?

**Comment by gungui98** [comment]
Sorry for my late response. Since then I had to add some linux packages so I decided to rewrite your Dockerfile and replaced your implement with original github action command, it works like a charm. :)
