### ISSUE TITLE
Integration with AWS

### ISSUE THREAD

**Issue by THEMrinaal** [iterative/cml#377]
Hi there,
I was wondering if we can integrate our workflows with AWS containers using ECS. If yes, then can you make a tutorial on that or can you provide me any useful link?
Best,
Mrinal

**Comment by DavidGOrtega** [comment]
👋 @THEMrinaal 
You can use our CML image in ECS you launch a runner.
Are you looking on how to do this inside the workflow with a deploy job like our cloud example?

**Comment by DavidGOrtega** [comment]
@THEMrinaal did you find a solution?

**Comment by THEMrinaal** [comment]
Not yet @DavidGOrtega

**Comment by DavidGOrtega** [comment]
Can you please specify what do you want to achieve? I guess that your problem is start  a self hosted runner using ECS?
Do you want that runner to be started inside your workflow as our cloud example at cml.dev?

**Comment by DavidGOrtega** [comment]
closed by inactivity
