### ISSUE TITLE
docker: tags and org

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#383]
We are publishing some images that might not be used anymore:

 - [x] dvcorg/cml-cloud-runner
 - [x] dvcorg/cml-py3-cloud-runner
 - [x] dvcorg/cml-gpu-cloud-runner
 - [x] dvcorg/cml-gpu-py3-cloud-runner

@elleobrien do you use anyone of these in our docs/videos?

**Comment by elleobrien** [comment]
Nope, by the time I made my video with the GPU we had already consolidate the `gpu` into base cml container! Thanks for thinking of this, though.

**Comment by elleobrien** [comment]
To me, it's okay to deprecate all of them.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, it looks like these repositories aren't being used anymore, and the number of pulls (~200 in total) hasn't increased in a while. Should we remove them directly, or should they be soft-deprecated with a message? In the former case, they should be removed manually through the Docker Hub web interface, because the API doesn't support this operation for token-authenticated users.

**Comment by 0x2b3bfa0** [comment]
🔔  @iterative/cml, I'm deleting them unless any of you states otherwise.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 lgtm

**Comment by casperdcl** [comment]
I guess you've checked download counts aren't increasing? https://hub.docker.com/u/dvcorg

**Comment by 0x2b3bfa0** [comment]
> _the number of pulls (~200 in total) hasn't increased in a while_

I checked it a few weeks ago and there weren't any new downloads in 5 days. Does this timespan sound reasonable?

**Comment by casperdcl** [comment]
You should also be able to tell when each tag was last pulled.

I would say it's fine to stop *updating* them but not necessarily *delete* them from the hub yet.

**Comment by 0x2b3bfa0** [comment]
> _You should also be able to tell when each tag was last pulled._

I have been unable to find how to gat that information after a cursory search. 🤔  Does Docker Hub store that information?

> _I would say it's fine to stop updating them but not necessarily delete them from the hub yet._

After a deeper investigation, I noticed that these image names were being used in the [cml.dev](https://cml.dev) documentation prior to 0.3.0.

While I only have written data for 5 days, the numbers are the same as 45 days ago if my brain didn't mix the digits. 😄  Nevertheless, caution doesn't hurt and we can leave them there just in case.

**Comment by shcheklein** [comment]
<img width="1269" alt="Screen Shot 2021-05-03 at 7 01 51 PM" src="https://user-images.githubusercontent.com/3659196/116953449-1f6d2e00-ac42-11eb-8047-bbc09886e78e.png">
<img width="1288" alt="Screen Shot 2021-05-03 at 7 02 08 PM" src="https://user-images.githubusercontent.com/3659196/116953453-2136f180-ac42-11eb-8acf-06bdf86d302b.png">
<img width="1285" alt="Screen Shot 2021-05-03 at 7 02 13 PM" src="https://user-images.githubusercontent.com/3659196/116953456-22681e80-ac42-11eb-86f7-580a209f7e16.png">
<img width="1294" alt="Screen Shot 2021-05-03 at 7 02 18 PM" src="https://user-images.githubusercontent.com/3659196/116953458-2300b500-ac42-11eb-9124-d6bfb9098100.png">

**Comment by casperdcl** [comment]
*120* inactive images and these ain't part of 'em hah

**Comment by 0x2b3bfa0** [comment]
🤔  Let's leave this running for a while before taking any decision: https://github.com/0x2b3bfa0/cml-docker-statistics

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, do you mean that some of these [_120 inactive images_](https://github.com/iterative/cml/issues/383#issuecomment-831643818) could be just stale testing images?

**Comment by 0x2b3bfa0** [comment]
## Activity in the last 30 days

* `cml-cloud-runner` had two pulls: one at 2021-05-12 08:06:29 UTC, and the other ~58 minutes later.
* `cml-gpu-cloud-runner` had zero pulls
* `cml-gpu-py3-cloud-runner` had zero pulls
* `cml-py3-cloud-runner` had zero pulls

Source: https://github.com/0x2b3bfa0/cml-docker-statistics

**Comment by 0x2b3bfa0** [comment]
🔔  @iterative/cml, 👍🏼  upvote to delete these container repositories or 👎🏼  downvote to soft-deprecate them by putting a big, red warning sign somewhere.

### Reasons to delete

We only have two good and updated container repositories: `cml` for end users and `cml-test` for internal testing. The others don't serve other purpose than confusing users, and we have a dozen of them still published on Docker Hub; most of them aren't documented anywhere.

### Reasons to keep

As a local saying states, _you can measure a hundred times, but cut only once_ (approximate translation); potentially destructive actions should be only taken after a healthy amount of warnings, just in case we have some user that started to use these containers but decided not to pull them but on leap years to make us think that there are zero users.

**Comment by DavidGOrtega** [comment]
> cml-cloud-runner had two pulls: one at 2021-05-12 08:06:29 UTC, and the other ~58 minutes later.
🤔

**Comment by 0x2b3bfa0** [comment]
Same results for the 45 days sliding window. Shall we take a decision?

**Comment by 0x2b3bfa0** [comment]
Also, we need to soft-deprecate the `dvcorg/cml:latest` tag; it's also stale and causes random issues, like #622 and some others on Discord.

**Comment by casperdcl** [comment]
action points:

- [ ] make `latest` point to `0-dvc2-base1-gpu`
  + may break some user workflows but that's their fault for not pinning. `latest` is a "user beware" flag
- [x] don't bother deleting old images/tags
  + we removed them from all documentation, and they show as not updated for months in the hub's tag list
- [ ] also push active tags to `@iterativeai/cml` (soft-deprecate `@dvcorg/cml`)
  + check credentials - ideally one bot user with push access to both orgs
  + solves problem with `dvcorg` having lots of outdated images/tags. `itertativeai` will be "clean"

**Comment by 0x2b3bfa0** [comment]
> [_I would say it's fine to stop updating them but not necessarily delete them from the hub yet._](https://github.com/iterative/cml/issues/383#issuecomment-830709182)

:bell: @casperdcl, 10 months and 6 pulls later... 🤔

**Comment by 0x2b3bfa0** [comment]
> _[don't update them so they show as not updated for months in the hub's tag list](https://github.com/iterative/cml/issues/383#issuecomment-870834591)_

@casperdcl, given that we don't control third–party blog posts and other resources, I wonder if we should revisit that decision and update `cml-py3` to display a deprecation warning on every run. 🤔
