### ISSUE TITLE
Question: Recommendations or suggestions on using DVC/CML as a model registry?

### ISSUE THREAD

**Issue by theelderbeever** [iterative/cml#385]
As I have begun to use DVC/CML I have been very pleased with its usability so kudos. This is somewhat of an open ended question but, has any thought been given to broadening the scope of these tools to use as a model registry? From what I have seen the capability/foundation exists to leverage DVC/CML for that purpose. Do you have any recommendations on how to go about implementing them as such? Sorry for the nebulous question.

**Comment by DavidGOrtega** [comment]
👋 @theelderbeever 
 > the scope of these tools to use as a model registry 
 CML is a CI/CD tool. To achieve a model registry you would need DVC strictly speaking and a particular tool called summon.
https://dvc.org/blog/gsoc-ideas-2020

**Comment by DavidGOrtega** [comment]
@theelderbeever did it help you?

**Comment by theelderbeever** [comment]
@DavidGOrtega yes that did. Thank you for the help!
