### ISSUE TITLE
cml-runner - Better idle mechanism in GH

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#407]
GH runners sometimes hangs when you cancel the job staying idle and not destroying themselves.
Probably for not finishing the current job not allowing idle to come back.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, how often were you able to reproduce this? Could this have anything to do with #399?

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 not related, however this can be reproduced with a micro instance installing tensorflow. I believe that the SCM runner crashes and our runner does not get the log so it stays forever. 
The interesting part is that our runner also listens for the child process crashes, but seems not to be working?
Not sure what could be

**Comment by DavidGOrtega** [comment]
metioned [here](https://discord.com/channels/485586884165107732/728693131557732403/818836498815909944)?
