### ISSUE TITLE
cml-image - Image build is failing

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#414]
Image build is failing [here](https://github.com/iterative/cml/runs/1963411862?check_suite_focus=true)
```sh
go: downloading github.com/iterative/machine v0.16.2
mv: cannot stat '/root/go/src/github.com/iterative': No such file or directory
The command '/bin/bash -c curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh &&     go get github.com/iterative/machine &&     mv $(go env GOPATH)/src/github.com/iterative $(go env GOPATH)/src/github.com/docker &&     cd $(go env GOPATH)/src/github.com/docker/machine && make build &&     ln -s $(go env GOPATH)/src/github.com/docker/machine/bin/docker-machine /usr/local/bin/docker-machine &&     apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

**Comment by 0x2b3bfa0** [comment]
That's the perfect place for a long rant about the awesomeness of Go modules, but rest assured that I'll refrain myself. 😉 

1. The container specification is instaling Go from the [`longsleep/golang-backports`](https://launchpad.net/~longsleep/+archive/ubuntu/golang-backports) unofficial [PPA](https://en.wikipedia.org/wiki/Ubuntu#Package_Archives):
https://github.com/iterative/cml/blob/73e2c96adab1e27b6528bdf9ae2b38dbd9ac4474/docker/Dockerfile#L33

2. We are not pinning the install to a specific Go version, so it will use the latest version it finds:
https://github.com/iterative/cml/blob/73e2c96adab1e27b6528bdf9ae2b38dbd9ac4474/docker/Dockerfile#L39

3. [As per the workflow logs](https://github.com/iterative/cml/runs/1963411862?check_suite_focus=true#step:3:1044), the latest version is Go 1.16, which [was published yesterday](https://launchpad.net/~longsleep/+archive/ubuntu/golang-backports/+sourcepub/12160015/+listing-archive-extra) on the repository we're using. What an adversity! 🙃 

4. Go 1.16 introduces some really important changes; among them, [using modules by default](https://blog.golang.org/go116-module-changes). Apart from the expected benefits, this also implies that `go get` won't use `~/go` anymore for storing the packages, leaving them on the current working directory instead.

***

I guess that the easier short-term solution will be pinning the Go version to anything below 0.16, but I would rather fix the commands to be forwards-compatible, be either as suggested in the official blog `cd && go get ···` or by simplifying all these commands to build the binaries in place.

Would you want me to submit a pull request with one of the latter options?

**Comment by 0x2b3bfa0** [comment]
😳  I commited (that's the exact word) a huge mistake and sent the commit that fixes this to the `master` branch directly because I mindlessly pressed the green button thinking that I had the triage permissions I had requested instead of full write permissions. Sorry! 🤦
