### ISSUE TITLE
Tagging of instances on AWS

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [iterative/cml#430]
Is it possible to apply tags to instances created on AWS? I've tried the `--label` option, but I can't see where this is propagated into instances in AWS.

**Comment by DavidGOrtega** [comment]
👋 @ivyleavedtoadflax very good suggestion. Indeed Im changing the title to make it more assertive

**Comment by ivyleavedtoadflax** [comment]
Is there any update on this on? My use case is the following:

I need to be able to see which resources relate to which project so that I can bill clients appropriately.

Since we use tags for other AWS resources, it would make sense if we could use tags in this case, but in the interim I can use the instance labels. This adds an extra manual step for each client, so it would be good if I could avoid it!

**Comment by DanielBarnes** [comment]
@DavidGOrtega @0x2b3bfa0 

I am not sure of the status of this issue.

I plan to attempt to implement this functionality unless a team member is actively developing it.

In my use case, I need to add several tags 3-5 to all AWS resources for tracking/billing; If you can provide an example of how you would see this best passed to the cml-runner, I am willing to submit a PR here and [upstream](https://github.com/iterative/terraform-provider-iterative). I saw a previous upstream [PR](https://github.com/iterative/terraform-provider-iterative/pull/3), but it looked like this only added specific tags and didn't allow users to add their own tags arbitrarily.

**Comment by 0x2b3bfa0** [comment]
Proposed syntax: `--metadata "key=value" --metadata "key=value" ···` with [`yargs.array()`](https://yargs.js.org/docs/#array)

**Comment by 0x2b3bfa0** [comment]
Depends on #703 as any other command-line interface API change, to avoid gigantic rebases.

**Comment by 0x2b3bfa0** [comment]
See https://github.com/iterative/terraform-provider-iterative/issues/185 for the provider part.

**Comment by 0x2b3bfa0** [comment]
Depends on iterative/terraform-provider-iterative#185 and, probably, on #703 to avoid rebasing commits.

**Comment by 0x2b3bfa0** [comment]
🔔  Carbon copy to @DanielBarnes to avoid effort duplication.

**Comment by 0x2b3bfa0** [comment]
Glad you found the snippet above useful. It has been hidden as a comment in the edit history of https://github.com/iterative/cml/issues/430#issuecomment-913098542 for a long time, just as a note to my future self. [XKCD 1421](https://xkcd.com/1421).
