### ISSUE TITLE
Whitelist the monitoring IP address to self-hosted runners

### ISSUE THREAD

**Issue by mattlbeck** [iterative/cml#436]
[From a discord query](https://discordapp.com/channels/485586884165107732/728693131557732403/818836901842255964)

**Can the self-hosted runner be whitelisted to allow only inbound ssh traffic from the monitoring address?**

Copying from the linked discussion:

> having your machines targeted by a bruteforce botnet is not nice, and being able to allow only a trusted source address would be a good way of keeping the instances armored, as long as that address is stable along the job run lifecycle.

> The only way of allowing traffic only from the monitoring address would be knowing it in advance: that would be the address of the non-self-hosted GitHub/GitLab runners that trigger the jobs.

> The only sensible option I could imagine would be obtaining the GitHub/GitLab-hosted runner address and passing it to CML when setting up the security group.

> if you are whitelisting it would probably be cleaner and more transparent to have a security group per runner, each with the single monitoring IP whitelisted

**Comment by 0x2b3bfa0** [comment]
> [_how do I specify security in AWS like inbound (Deny)/outbound rules (443) or which roles / policies to associate with the access key hosting user in order to use the minimum permissions best practice_](https://discord.com/channels/485586884165107732/728693131557732403/845893130187702293) (Discord comment)
***
>[_Using AWS default ACLs, VPCs, and Subnets worked for the networking security, but that isn't good for an enterprise_](https://discord.com/channels/485586884165107732/728693131557732403/845935553819312128) (Discord comment)

**Comment by DavidGOrtega** [comment]
duplicated of https://github.com/iterative/terraform-provider-iterative/issues/107

**Comment by mattlbeck** [comment]
@DavidGOrtega I am not convinced that iterative/terraform-provider-iterative#107 covers the issue of IP whitelisting? The cml runner still requires internet visibility to be monitored by GitHub or GitLabs servers.

**Comment by DavidGOrtega** [comment]
@mattlbeck sorry I do not follow you.

iterative/terraform-provider-iterative#107
Its about creating a network resource that the user will be able to specify it from end2end. User would be able to create such a network controlling the ingress, hosts...

What are you missing that could not be supported by it?

**Comment by mattlbeck** [comment]
@DavidGOrtega it may be that I don't understand the full picture, but as I understood it supplying any sort of ingress restriction was tricky because it was hard to figure out the GitHub (in my case) IP that would be monitoring the self-hosted runner, reporting back logging etc. to the GitHub workflow. Does deploying the self-hosted runner in a new VPC change this situation?

**Comment by DavidGOrtega** [comment]
The runner communicates via API mostly or RPC, allowing egress traffic restricting ingress will close your runner but still be able to communicate with the SCM.

**Comment by DavidGOrtega** [comment]
If you still feel that the Network resource wont fix you issue please reopen it 🙏

**Comment by mattlbeck** [comment]
Interesting to know, thanks @DavidGOrtega I will be following these enhancements with interest
