### ISSUE TITLE
Support for AWS cloud region ap-southeast-1

### ISSUE THREAD

**Issue by mapattacker** [iterative/cml#437]
Hi, I tried to create an AWS instance in **gitlab-ci** for a job but realised that it does not support my region of ap-southeast-1.

Is this something the development team will be working on in the pipeline?

```
cml-runner --cloud aws --cloud-region $AWS_DEFAULT_REGION --cloud-type t2.micro --labels=cml-runner-gpu
Preparing workdir /home/runner...
Deploying cloud runner plan...
Terraform apply...
Error: terraform -chdir='/home/runner' apply -auto-approve
	iterative_cml_runner.runner: Creating...
	
Error: Failed creating the machine: iterative-cml ami not found in region
```

**Comment by 0x2b3bfa0** [comment]
:wave: Welcome, @mapattacker! Can you please try to run again that command? We've added a fallback mechanism for missing regions.

**Comment by mapattacker** [comment]
hi @0x2b3bfa0, I presume this is the fallback mechanism? I.e. to purchase a server from US region?

```
Error: Failed creating the machine: Not able to decode: OptInRequired: 
In order to use this AWS Marketplace product you need to accept terms and subscribe. 
To do so please visit https://aws.amazon.com/marketplace/pp?sku=3iplms73etrdhxdepv72l6ywj
	status code: 401, request id: 9d0718a6-538c-4044-9e32-80085ce35646
```

It's kinda a pity as I can only work on ML training with the server in my region. Hope this will be supported in the future. Great work you guys are doing though!

**Comment by DavidGOrtega** [comment]
@mapattacker If you follow the link you will see an agreement to be able to use Ubuntu 18.04 AMI. You have to do that every single time you want to use a third party AMI, if you are using the console AWS is doing it implicitly for you.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 lets review all the regions to upload the cml image

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, do you mean _all_ the regions, or just a curated list?

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 all

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, as far as I know, this is the full list of regions for EC2:  

- us-east-2
- us-east-1
- us-west-1
- us-west-2
- af-south-1
- ap-east-1
- ap-south-1
- ap-northeast-3
- ap-northeast-2
- ap-southeast-1
- ap-southeast-2
- ap-northeast-1
- ca-central-1
- eu-central-1
- eu-west-1
- eu-west-2
- eu-south-1
- eu-west-3
- eu-north-1
- me-south-1
- sa-east-1

I'm completely ignorant about GovCloud, Wavelength and other esoteric services, but the list above should be enough to cover almost every need.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 🙏 lets do a small PR covering all of them like the did

**Comment by 0x2b3bfa0** [comment]
@mapattacker,  `ap-southeast-1` should be already active, among many others. 🎉

**Comment by 0x2b3bfa0** [comment]
This issue will be closed automatically as soon as iterative/terraform-provider-iterative#96 gets merged.
