### ISSUE TITLE
Installed cli applications that are available in my workflow don't seem to be available...

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#453]
...when I connect via EC2 connect

[discord](https://discord.com/channels/485586884165107732/728693131557732403/822535434302783498)

**Comment by 0x2b3bfa0** [comment]
@btjones-me, is this still relevant?

**Comment by btjones-me** [comment]
Yep, this ticket appears to be resolved - thanks very much! It appears I can access installed commands such as `aws` which were installed by github action, and now access the `/__w/` folder which I couldn't before

**Comment by 0x2b3bfa0** [comment]
Great! Feel free to reopen it if you experience again any similar issue.
