### ISSUE TITLE
Deprecate wait for cloud runner readiness 

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#457]
This is actually achieved by the provider.

**Comment by DavidGOrtega** [comment]
https://github.com/iterative/terraform-provider-iterative/pull/70 needs to be merged first

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, what't the status of this issue?

**Comment by 0x2b3bfa0** [comment]
Closed with #523
