### ISSUE TITLE
Question/Suggestion: open certain ports on self hosted CML runners?

### ISSUE THREAD

**Issue by asmith26** [iterative/cml#471]
Hi there, thanks for all these fantastic libs!

I was wondering if there was a way to **open certain ports** when deploying a [Self hosted CML runner](https://dvc.org/doc/cml/self-hosted-runners)?

E.g. I was thinking about running a cml-runner to host a [Streamlit](https://streamlit.io/) HTTP application following a new ML experiment, to more quickly analyse results (any other suggestions regarding a good way to achieve this also very welcome).

Many thanks for any help! :)

**Comment by 0x2b3bfa0** [comment]
👋  Welcome, @asmith26! Are you trying to deploy our runner in the cloud, or just locally? Also, which provider are you using, GitHub or GitLab?

As far as I know, neither of the supprted self-hosted runners were designed to accept incoming connections, but you can always use a [third-party tunneling service](https://github.com/anderspitman/awesome-tunneling) like [`ngrok`](https://ngrok.com/) or plain [SSH tunneling](https://www.ssh.com/academy/ssh/tunneling) to access your service.

**Comment by asmith26** [comment]
Thanks for your help @0x2b3bfa0. Cloud + GitHub. 

SSH tunnelling sounds a useful approach, thanks for suggesting. Do you know how I might achieve this (possibly via the `limit-access-to-actor` option?)

**Comment by 0x2b3bfa0** [comment]
@asmith26, after performing some tests, I have discovered that GitHub cloud runners actually let services listen to the host bind address. 😱 

At least for our AWS machines, if you run a GitHub Actions job that binds to `0.0.0.0` on its environment, it will be exposed to the wide internet through the machine public address. 

```console
Terraform apply...
··· "attributes": {···, "instance_ip":"3.101.112.236", ···
```

⚠️ **Warning:** please don't do this, as you'll be effectively letting anybody access your streamlit application from anywhere on the wild internet.

**Comment by 0x2b3bfa0** [comment]
Instead, you can bind your server to `localhost` so it only accepts local connections and you can just use an SSH tunnel to bring that service to your local machine securely. As you've already guessed, the `--cloud-ssh-private` will allow you tu use a custom private key (the public gets computed automatically) for the machine.

**Comment by DavidGOrtega** [comment]
Of course that only happens if you use GitHub and don't use a container as we always recommend for security purposes.
In GL is not the case since it always runs docker in docker

**Comment by DavidGOrtega** [comment]
@asmith26 as @0x2b3bfa0 states we don't close any port and any service that you launch will be listening outside if you bind it as 0.0.0.0

**Comment by DavidGOrtega** [comment]
closed as we dont have to open any port
