### ISSUE TITLE
Use rational names for GPU models

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#509]
> _[C]an somebody explain [...] the distinction between k80 and tesla? Nvidia [has] a Tesla K80 GPU, but I don't know which I should be choosing here._ ([Discord](https://discord.com/channels/485586884165107732/728693131557732403/841338755993567232))

Currently we support both Tesla K80 and Tesla V100 accelerators from NVIDIA on every cloud provider, but option names are a bit imprecise: `--cloud-gpu=k80` means Tesla K80 and `--cloud-gpu=tesla` means Tesla V100. :see_no_evil: Should we replace `tesla` with `v100` and keep the former just for backwards comaptibility?

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 but lets keep tesla a bit for backward compat
