### ISSUE TITLE
don't require a token when not needed

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#515]
Basic commands such as `cml-publish --version` should succeed even without a token defined.

https://github.com/iterative/setup-cml/pull/31/checks?check_run_id=2583733405#step:9:8

**Comment by 0x2b3bfa0** [comment]
That issue was probably solved long ago, please keep in mind that it happens with 0.1.30 but not with 0.3.8 (latest)

**Comment by 0x2b3bfa0** [comment]
In this use case, you may just check for a more recent specific version. Maybe 0.3.0?

**Comment by casperdcl** [comment]
yep, works

**Comment by DavidGOrtega** [comment]
> That issue was probably solved long ago, please keep in mind that it happens with 0.1.30 but not with 0.3.8 (latest)

@0x2b3bfa0 I wish you memory. I did it and I do not remembered it
