### ISSUE TITLE
Separate unit tests from acceptance tests

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#527]
> _CML is a project that relies heavily on external infrastructure, and some acceptance tests are practically unavoidable if we want to make sure that nothing breaks. Nevertheless, I was wondering if we could mock as much as possible to separate unit from acceptance tests, enabling users to check their contributions for errors without having to care about those services._

**Comment by 0x2b3bfa0** [comment]
Solving this would probably imply repourposing `test.yml` from #526 to run unit tests first and relying on GitHub Environments just for acceptance tests.

**Comment by 0x2b3bfa0** [comment]
[Tensorboard tests](https://github.com/iterative/cml/blob/b8f402f9df31907e0f1e57fc3ddb17c668e2aab9/bin/cml-tensorboard-dev.test.js#L50-L54) are flaky because of rate limits: yet another reason to separate unit tests from acceptance tests and only run the latter on demand.

**Comment by DavidGOrtega** [comment]
I don't find a proper way to do such unit tests aside recording the API responses as I have said so many times.
If you are willing to do so @0x2b3bfa0 you have to setup sinon.js to mock the real responses.
