### ISSUE TITLE
cml-pr: follow-up

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#529]
Follow-up to #510

- [ ] separate driver-specifics https://github.com/iterative/cml/pull/510#discussion_r632843873, https://github.com/iterative/cml/pull/510#discussion_r632846778

**Comment by 0x2b3bfa0** [comment]
>_[I wonder if and why we should recommend quoting variadic arguments to `cml-pr` by default. Shell globs are as powerful as internal globs and, at least for my tastes, `cml-pr dvc.lock` is nicer than `cml-pr 'dvc.lock'`](https://iterativeai.slack.com/archives/C01900GSB4J/p1622149354227200)_

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 I think both are supported

**Comment by 0x2b3bfa0** [comment]
Yes, it's mostly a documentation choice and, to a lesser extent, a design decision: I would even consider providing a mechanism to enable or disable globs like in `dvc add` or `git add`

**Comment by 0x2b3bfa0** [comment]
It's me, or `cml-pr` would be a lot more useful if pull request titles, pull request messages and commit messages were configurable; or, at least, if there was an option to disable the `skip-ci` text? See [this discuss.dvc.org thread](https://discuss.dvc.org/t/cml-dvc-github-actions-hyper-parameter-tuning/812/4?u=0x2b3bfa0) for an example.

**Comment by dacbd** [comment]
Stale / done?
