### ISSUE TITLE
replace/remove mmmagic dependency

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#544]
mmmagic uses gyp and needs to compile libraries. It should be replaced by a better one.

 - needs sudo
 - uses native
 - needs to compile
 - slower install time

**Comment by 0x2b3bfa0** [comment]
* [`file-type`](https://github.com/sindresorhus/file-type) doesn't support SVG, but looks nice
* [`@npcz/magic`](https://www.npmjs.com/package/@npcz/magic) doesn't *(cough)* use native code

**Comment by DavidGOrtega** [comment]
> file-type doesn't support SVG, but looks nice
 
 We used it 😁

**Comment by dacbd** [comment]
Copying snippet from #836 incase its helpful for any viewers:

--------
I was looking at: https://github.com/iterative/setup-cml/issues/53

How much work would it be to eliminate as a dependency? It seems to be only used in one place, I'm not familiar with this chunk: https://github.com/iterative/cml/blob/cf7bfd039bc366d781ee897f774ca394f21e3f39/src/utils.js#L27-L47

and if IIRC is the only complied cml dependency?
