### ISSUE TITLE
lint: fix issues

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#547]
I open this issue to discuss CML's coding convention change and tasks needed to perform such change.

@0x2b3bfa0 @casperdcl @shcheklein

**Comment by DavidGOrtega** [comment]
This is also very unfriendly to review  
![image](https://user-images.githubusercontent.com/414967/118963549-d4a02580-b966-11eb-83c5-7ac2a096dce3.png)

**Comment by 0x2b3bfa0** [comment]
It would be nice to have a parent issue in a higher-level repository — or a Slack thread— to discuss this with the other project teams so all we follow the same conventions. In our case, the specifics probably boil down to these three points:

1. [TypeScript](https://en.wikipedia.org/wiki/TypeScript) or [JavaScript](https://en.wikipedia.org/wiki/JavaScript)
2. [`dromedaryCase`](https://en.wikipedia.org/wiki/Camel_case) or [`snake_case`](https://en.wikipedia.org/wiki/Snake_case)
3. Formatter and linter settings

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 of course but this issue is also the issue where to review what we are going to do once we agree.

**Comment by casperdcl** [comment]
2 & 3. AFAIK everyone's agreed on camelCase. I'll fix the linter issues.

I think we can discuss 1. TS vs JS in a separate issue if needed

**Comment by casperdcl** [comment]
btw this https://github.com/yargs/yargs/issues/1679 is annoyingly not fixed

**Comment by 0x2b3bfa0** [comment]
(As frustrating as https://github.com/yargs/yargs/issues/1312)

**Comment by 0x2b3bfa0** [comment]
By the way: do we agree on [the definition of camel case](https://google.github.io/styleguide/jsguide.html#naming-camel-case-defined)? 😉

**Comment by casperdcl** [comment]
Yes, but beware that the example table is not complete (e.g. it doesn't properly show rule 3b with a `properNounObjectName` rather than a `ProperNounClassName`)

**Comment by 0x2b3bfa0** [comment]
Renaming should be as easy (?) as taking a look to this list and applying the conversion rules above.
```bash
npx grasp --only-matching --no-filename --no-line-number 'ident' **/* |
grep --invert-match '[A-Z]' | grep '_' |
sort --unique
```

**Comment by casperdcl** [comment]
No, it's a fair bit more involved than that but I'll open a PR soon.

**Comment by 0x2b3bfa0** [comment]
> [_Give as descriptive a name as possible, within reason. Do not worry about saving horizontal space as it is far more important to make your code immediately understandable by a new reader. Do not use abbreviations that are ambiguous or unfamiliar to readers outside your project, and do not abbreviate by deleting letters within a word._](https://google.github.io/styleguide/jsguide.html)

That fair bit looks promising. 👀
