### ISSUE TITLE
cml-runner needs more integration tests

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#550]
Because we are using images and we are not running checkbot as much as we should we need to include runner tests to avoid issues like #548

**Comment by 0x2b3bfa0** [comment]
Duplicate of #538?

**Comment by DavidGOrtega** [comment]
I would say related

**Comment by 0x2b3bfa0** [comment]
As per #527, I would tend to avoid integration tests whenever possible and solve these issues by resorting to simpler unit tests.

**Comment by DavidGOrtega** [comment]
> Duplicate of #538?
