### ISSUE TITLE
cml-pr convention name seems to be breaking GH's branches page

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#551]
seems to be perfectly fine in BB and GL.

![image](https://user-images.githubusercontent.com/414967/119011042-edbfcb00-b994-11eb-8a75-c9742eb6df18.png)

**Comment by 0x2b3bfa0** [comment]
Are you sure that it's the naming? 
![Captura de pantalla 2021-05-20 a las 18 01 30](https://user-images.githubusercontent.com/11387611/119011533-72124e00-b995-11eb-89ed-cd6564087ec0.png)

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 with your image I can even confirm it!

What breaks it is refs/heads/...

**Comment by 0x2b3bfa0** [comment]
![Captura de pantalla 2021-05-20 a las 18 38 18](https://user-images.githubusercontent.com/11387611/119016720-8f95e680-b99a-11eb-915f-7a694bef36f4.png)

**Comment by 0x2b3bfa0** [comment]
Do you have a minimal example? I'm unable to reproduce on a fork... 🤔

**Comment by 0x2b3bfa0** [comment]
Now I am! 🙃

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 able to reproduce it?

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 you dont have to spend time on this. We have a PR
