### ISSUE TITLE
Setup OlivaBot in GL and BB

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#552]
GL
![image](https://user-images.githubusercontent.com/414967/119014028-dcc48900-b997-11eb-877a-f866b379739b.png)

BB
![image](https://user-images.githubusercontent.com/414967/119014125-f1a11c80-b997-11eb-9d2a-656b01bba148.png)

GH
![image](https://user-images.githubusercontent.com/414967/119014219-08477380-b998-11eb-9761-6334677546ac.png)

**Comment by casperdcl** [comment]
done
