### ISSUE TITLE
Investigate Terraform CDK as an alternative to custom templates

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#556]
We should probably use [Terraform CDK](https://www.hashicorp.com/blog/cdk-for-terraform-enabling-python-and-typescript-support) instead of the custom [`src/terraform.js`](https://github.com/iterative/cml/blob/4fd2d8b866aed63dd15a5073f9dfafdb51c13544/src/terraform.js) source file.

See #584 and #564 for more information of the current pitfalls.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 The idea would be calling our provider inside the runner instead of generating the terraform file?

**Comment by 0x2b3bfa0** [comment]
Yes, this could allow us to use the Terraform provider directly from JavaScript.

**Comment by DavidGOrtega** [comment]
I like it if it does not write a TF file like we do, if not not sure about the effort

**Comment by 0x2b3bfa0** [comment]
Not useful.
