### ISSUE TITLE
overhaul README

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#557]
- installation/set-up instructions are littered across entire file (start, middle & end)
- missing commands & description
- Current docs do not make it clear enough that a PAT is required to run e.g. https://github.com/iterative/cml-runner-base-case CC @dmpetrov
  + https://github.com/iterative/cml#environment-variables
  + https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by DavidGOrtega** [comment]
This issue is a never ending one. We have passed from having how to setup it in the README to not have it. Maybe it's because in the videos is specifically taught

**Comment by casperdcl** [comment]
all part of good ol' #514 :)
