### ISSUE TITLE
cml-runner: Add an option to reuse only idle runners

### ISSUE THREAD

**Issue by courentin** [iterative/cml#575]
Today, the `--reuse` option of `cml-runner` does not care if the runner is in use or not.
While it is convenient when multiple jobs can be run on the same runner, some job needs a dedicated runner to work (jobs that take the runner resources).

However, we could benefit from runner reusability for this kind of job by introducing a `--reuse-idle` option to the runner. This option would reuse a runner only if it is idle (option naming to be challenged).

**Comment by courentin** [comment]
Implementation notes:

### Github

Github returns an `is_busy` boolean that is `false` when the runner is idle ([see the doc](https://docs.github.com/en/rest/reference/actions#list-self-hosted-runners-for-a-repository)).
We can pass `is_idle` in `opts` and filter runners depending on this value, here:
https://github.com/iterative/cml/blob/75866d103a29ecb8c1a0ec4c053cd93e2f87b0c1/src/drivers/github.js#L233-L245

### Gitlab
I wasn't able to test it on gitlab but they seem to have an `active` field ([see the doc](https://docs.gitlab.com/ee/api/runners.html#list-all-runners)).

However I was not able to see the signification of this `active`, can someone with a gitlab repo and runner setup help me to make sure this field checks runner idle-ness, maybe @DavidGOrtega ?

**Comment by 0x2b3bfa0** [comment]
Thank you very much, @courentin! This could be a nice way for `cml-runner` to expedite runs triggered with `--reuse` runners.

What would happen if the runner accepts another task between the idleness check and the task creation?

**Comment by courentin** [comment]
I haven't thought about it, it will have the same behaviour than `--reuse` in this case.
Not sure if we can avoid this?

**Comment by 0x2b3bfa0** [comment]
So true, we already face this possible race condition. I guess that it would be a minor issue to live with: the worst case would imply feeding a single runner with two tasks serially.

**Comment by DavidGOrtega** [comment]
As I stated runners takes jobs, thats it. So when we launch a workflow that launches one machine and we have already a runner with that tags what will happen is that the job will be taken by any of the runners, thats why we cleanup runners after idle and one of the runners will remain idle until idle-timeout happens and the other will reach the same fatal destiny after completing the job and idle-timeout happens 😈

**Comment by DavidGOrtega** [comment]
We also have the option ```--single```

**Comment by dacbd** [comment]
I fully understand what is being proposed here so feel free to re-open.

GitHub Actions will only distribute a job to a runner if it is idle, to run multiple jobs on a single instance you would need to register multiple runners as different independent services on the instance.

the `--single` flag will ensure that only a job is run. w/o this instance will continue to pick jobs matching its provided labels until the idle timeout is reached, after which it will self-terminate.

**Comment by casperdcl** [comment]
use case explanation:

1. `cml runner --labels=xyz --single`: con: often have to wait 5min+ to provision
2. `cml runner --labels=xyz --reuse`: con: no parallel jobs (queue waiting for one runner)
3. `cml runner --labels=xyz --reuse-idle`: this feature request: no need to wait to provision iff another job has just completed (so an idle runner is available)

**Comment by dacbd** [comment]
So with `--reuse-idle` if:
1. a `runner` is registered with that label
2. that ` runner` is idle

`cml runner` exists so the dependant job can get picked up without creating a new instance,

**Comment by casperdcl** [comment]
> 1. a job is submitted & launches a runner (no `--single`)
> 2. job finishes, runner waits for more jobs (upto `idle_timeout`)
> 3. 10 jobs are submitted before `idle_timeout` is triggered. 1 job gets assigned the existing runner above, the remaining 9 jobs launch their own runners

-- @casperdcl in https://github.com/iterative/cml/issues/1025#issuecomment-1144718587

> Seems very reasonable, so `cml runner` should try to check for an existing one if present exit successfully so the dependant job can get picked up. Though this is dangerous territory for a race condition.
> 
> I could see: 10 jobs get rapidly spawned, and there is 1 runner idle. The 10 jobs all do their check for idle runner and see one, so no new runner is created, a few seconds later, our existing runner has its new job but we have 9 waiting in the queue for that same runner.

-- @dacbd in https://github.com/iterative/cml/issues/1025#issuecomment-1146103104
