### ISSUE TITLE
Support for DAGsHub | cml-send-comment

### ISSUE THREAD

**Issue by PuneethaPai** [iterative/cml#577]
We can use DAGsHub api and add support for adding comments to PR/Issues.

**API Details:**

- Type: POST
- Authentication: Password or Token based
- URL: https://dagshub.com/api/v1/repos/{username}/{reponame}/issues/{index}/comments
- Body:
```json
{
    "body": "What you want to comment"
}
```

**Example Curl Command:**
```sh
curl -u "Dean" -H "Content-Type: application/json" -X POST -d '{"body":"A comment"}' https://dagshub.com/api/v1/repos/OperationSavta/SavtaDepth/issues/13/comments
```

@deanp70 and @guysmoilov can add more details.

**Comment by 0x2b3bfa0** [comment]
Nice! Please keep in mind that `cml-send-comment` operates on commits and, optionally, on the associated pull requests.

https://github.com/iterative/cml/blob/a2707c00514499b8e193986ff55db6776d71693e/src/drivers/bitbucket_cloud.js#L23-L62
https://github.com/iterative/cml/blob/a2707c00514499b8e193986ff55db6776d71693e/src/drivers/github.js#L72-L85
https://github.com/iterative/cml/blob/a2707c00514499b8e193986ff55db6776d71693e/src/drivers/gitlab.js#L73-L84

**Comment by guysmoilov** [comment]
Thanks @PuneethaPai !
I think you covered everything.
I didn't know that CML comments primarily on commits - DAGsHub doesn't have such an API yet, I'll update here if this changes.
I'm not sure how this affects a possible integration?

**Comment by dacbd** [comment]
@guysmoilov Please feel free to contribute, but we don't foresee us adding this feature anytime soon, so I'm going to close this for now.
