### ISSUE TITLE
Failed preparing GitHub runner: TAR_BAD_ARCHIVE: Unrecognized archive format

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#580]
GH downloads cache is down, making our CML runner undeployable. Maybe we should include the distros as a resource in CML package?

![image](https://user-images.githubusercontent.com/414967/121168319-1a0f8e80-c853-11eb-9f1f-e0244e9c57d8.png)

**Comment by 0x2b3bfa0** [comment]
It looks like this has happened due to [a global failure](https://status.fastly.com/incidents/vpk0ssybt3bj) of Fastly services. Do you think that it's worth shipping 500+ MB of vendored third-party binary dependencies with our package to avoid once-in-a-decade incidents?

**Comment by DavidGOrtega** [comment]
I did not review how much they where, but maybe we could mirror it somewhere

**Comment by 0x2b3bfa0** [comment]
My point is that no matter where that _somewhere_ is, it will probably be subject to the same kind of failures and probably won't benefit from the awesome reliability teams working at GitHub, GitLab and all the server chain that's behind our current queries.

**Comment by 0x2b3bfa0** [comment]
Anyhow, if you keep seeing any advantage on keeping our own copies, let's find a good place to store them.

**Comment by DavidGOrtega** [comment]
The main difference is that GH users probably wont suffered this effect because the runner is already downloaded. Having prepared a machine every time may incur in this unwanted effect leaving our users without the capacity of continue working.
The point of breakage is bigger than having the runner downloaded and ready.

**Comment by DavidGOrtega** [comment]
Another solution could be reuse the downloaded runner

**Comment by 0x2b3bfa0** [comment]
> _I would say that putting a cache layer on top of theirs is not difficult nor expensive._

That's exactly what Fastly did, _putting a cache layer_, and it [failed](https://status.fastly.com/incidents/vpk0ssybt3bj) producing this 503 error. They (GitHub, GitLab, Fastly, _et cetera_) have a solid SRE team that's in charge of avoiding service interruprions, or mitigating them when things go awry once in a decade. We don't.

I'd avoid introducing another point of failure in the chain unless we're able to achieve a better SLA than Fastly, GitHub, GitLab and all their servers.

**Comment by 0x2b3bfa0** [comment]
🔔  @iterative/cml, 👍🏼  this comment to leave this issue open, 👎🏼  to close it.

**Comment by DavidGOrtega** [comment]
I want to leave it open. As I stated we could download the package just once. Or even better, Im closing this one and opening a new one

**Comment by DavidGOrtega** [comment]
I agree that having a download CDN might end up with the same problem. Closed via #615
