### ISSUE TITLE
Gitlab repository mirror failed

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#586]
If we do not fix this the repos are unsync and we are having issues with the tests

**Comment by 0x2b3bfa0** [comment]
This transient error — whose cause is still unknown — is not reproducible anymore. As of 2021-08-25 00:10 UTC, both repositories are in sync at `899c6d2`

* [github.com/iterative/cml/commit/899c6d2](https://github.com/iterative/cml/commit/899c6d2e3eaffc66d12492deffa658e8430f1c66)
* [gitlab.com/iterative.ai/cml/-/commit/899c6d2](https://gitlab.com/iterative.ai/cml/-/commit/899c6d2e3eaffc66d12492deffa658e8430f1c66)
