### ISSUE TITLE
NVIDIA drivers not installing on Azure cloud runner

### ISSUE THREAD

**Issue by MaxHuerlimann** [iterative/cml#590]
Hi everybody
I am trying to use `cml-runner` on GitLab to deploy a GPU machine on which to run training. The deployment works great but the docker container then running the training can't find any NVIDIA drivers it seems, as I can't run 'nvidia-smi'.

My .gitlab-ci.yml looks like this (simplified):
```bash
stages:
  - deploy
  - train

deploy:
  stage: deploy
  when: always
  image: dvcorg/cml:0-dvc2-base1-gpu
  script:
    - cml-runner
      --cloud azure
      --cloud-region eu-west
      --cloud-type Standard_NC4as_T4_v3
      --cloud-hdd-size 128
      --cloud-gpu v100
      --labels=cml-runner-gpu

train:
  stage: train
  when: on_success
  image: dvcorg/cml:0-dvc2-base1-gpu
  tags:
    - cml-runner-gpu

  script:
    - nvidia-smi
```
In the examples it's not mentioned that I need to install the drivers myself on the deployed machine, it looks like it should work out-of-the-box, or am I overlooking something? Is that only for AWS? Do I need to pass a script installing the drivers through `--cloud-startup-script`?

Cheers

**Comment by MaxHuerlimann** [comment]
Ah I saw on Discord that I guess it was an issue with needing to reboot the machine. Apparently it should be resolved, so am I using a wrong docker image?

**Comment by 0x2b3bfa0** [comment]
👋🏼  Welcome, @MaxHuerlimann! Your images are the right ones, and `nvidia-smi` should work out of the box.

**Comment by 0x2b3bfa0** [comment]
Please try running your workflow again and, in case it doesn't work, feel free to ping us again on this issue.

**Comment by MaxHuerlimann** [comment]
Hi, the issue is still persisting. If I pass a startup script that installs the drivers it works, though, so like this:
```bash
stages:
  - deploy
  - train

deploy:
  stage: deploy
  when: always
  image: dvcorg/cml:0-dvc2-base1-gpu
  script:
    - script=$(echo 'sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y nvidia-driver-460' | base64 --wrap 0)
    - cml-runner
      --cloud azure
      --cloud-region eu-west
      --cloud-type Standard_NC4as_T4_v3
      --cloud-hdd-size 128
      --cloud-startup-script $script
      --labels=cml-runner-gpu

train:
  stage: train
  when: on_success
  image: dvcorg/cml:0-dvc2-base1-gpu
  tags:
    - cml-runner-gpu

  script:
    - nvidia-smi
```

**Comment by 0x2b3bfa0** [comment]
Able to reproduce!

**Comment by 0x2b3bfa0** [comment]
From the `/var/log/cloud-init-output.log` file on a running instance:
```console
$ sudo ubuntu-drivers autoinstall
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 linux-modules-nvidia-460-azure-edge : Depends: linux-modules-nvidia-460-5.4.0-1049-azure (= 5.4.0-1049.51~18.04.1) but it is not going to be installed
                                       Depends: nvidia-kernel-common-460 (<= 460.80-1) but 460.84-0ubuntu0~0.18.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by 0x2b3bfa0** [comment]
Solved by removing the the `graphics-drivers/ppa` introduced with https://github.com/iterative/terraform-provider-iterative/pull/135.

```console
$ sudo add-apt-repository --remove ppa:graphics-drivers/ppa
$ sudo apt update
$ sudo ubuntu-drivers autoinstall
```

**Comment by 0x2b3bfa0** [comment]
@MaxHuerlimann, sorry for the late reply. It should be fixed as soon as we release https://github.com/iterative/terraform-provider-iterative/pull/144

**Comment by MaxHuerlimann** [comment]
That's great! Thanks for the quick fix :)
