### ISSUE TITLE
Default('thing') vs Default('thing', '')

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#592]
Coming from [here](https://github.com/iterative/cml/pull/591#discussion_r651642417)
We have to review whats behind this and why we should not even remove the deafult

**Comment by 0x2b3bfa0** [comment]
If we rely on default values being empty strings versus the `undefined` value it would make some sense to have this distinction. Nevertheless, we probably shouldn't rely on this and always check for `undefined` before running any string methods over values; see Typescript for a compendium of good practices on the matter.

**Comment by dacbd** [comment]
going say this is no longer applicable after https://github.com/iterative/cml/pull/712
