### ISSUE TITLE
Remove Restyle in CML or adjust it to follow airbnb style

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#596]
Having some clear difficulties in having consistency in style, its better to just let the linter speak and refuse the PR if the style does not match the chosen style.

We have to:
 - Remove Restyle or make it use our eslint config (I remember that to not be possible)

This will make contributions harder but at least the base source code will follow the same convention.

**Comment by 0x2b3bfa0** [comment]
Existential doubt from https://github.com/iterative/cml/pull/581#discussion_r652600023:

```javascript
(item) => {
  const { property: { data = '' } = {} } = item;
  return data.endsWith('text');
}
```

_versus_

```javascript
(item) => item && item.property && item.property.data && item.property.data.endsWith('text')
```

_versus_

```javascript
(item) => item?.property?.data?.endsWith('text')
```

The last one is only valid in Node.js 14+ as stated on #597

**Comment by 0x2b3bfa0** [comment]
Note: as per https://github.com/iterative/cml/pull/581#discussion_r652781670, we probably should broaden a bit the scope of the issue title.

**Comment by 0x2b3bfa0** [comment]
Another style topic: https://github.com/iterative/cml/pull/583#discussion_r657433898

**Comment by 0x2b3bfa0** [comment]
Speaking about what linters can't detect: how deffensive should we be when writing code that interacts with complex systems out of our control?

- https://github.com/iterative/cml/pull/468#discussion_r610534623
- https://github.com/iterative/cml/pull/563#issue-654270569
- https://github.com/iterative/cml/pull/583#discussion_r657449080
- https://github.com/iterative/cml/pull/608#issuecomment-868690031

**Comment by 0x2b3bfa0** [comment]
Already using optional chaining 🎉 
* https://github.com/iterative/cml/pull/943#pullrequestreview-937334724

**Comment by 0x2b3bfa0** [comment]
Tracking https://github.com/iterative/cml/pull/1026#discussion_r894820360
