### ISSUE TITLE
Drop support for Node.js 12 or use a transpiler

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#597]
Node.js 12 is [in maintenance mode](https://nodejs.org/en/about/releases/) and will stop being supported on 2022-04-30. It would be nice to start using, Node.js 14 or even 16 to take advantage of features like [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) as per https://github.com/iterative/cml/pull/581#discussion_r652756206.

**Comment by DavidGOrtega** [comment]
I don't have to wait for a specific node version we can always use a transpiler.

**Comment by 0x2b3bfa0** [comment]
If we choose that path, it would be nice to consider TypeScript. Anyhow, we
can remain in the pure JavaScript realms with Babel.

**Comment by 0x2b3bfa0** [comment]
See also https://github.com/iterative/setup-cml/issues/40

**Comment by 0x2b3bfa0** [comment]
Already using optional chaining:
* https://github.com/iterative/cml/pull/943#pullrequestreview-937334724
