### ISSUE TITLE
Investigate - default idle-timeout seems not to be destroying the machine

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#600]
Coming from [discord](https://discord.com/channels/485586884165107732/728693131557732403/854747177100115988)

in private message:
> It seems that we solved this issue - it turns out that there was additional argument --idle-timeout that we ignored. 

however idle-timeout has been always 5min by default.

**Comment by 0x2b3bfa0** [comment]
After reading the pertaining code, I struggle to see how specifying `--idle-timeout=300` could cause a behavior other than the default one. 🤔  I'll  run it just in case.

**Comment by 0x2b3bfa0** [comment]
Unable to reproduce. 🤷🏼‍♂️
