### ISSUE TITLE
Repository URL inferrence broken for non-HTTPS repository servers

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#616]
### Follow-up of https://github.com/iterative/cml/pull/608#issuecomment-869881248

Under normal operation conditions, CML tries to infer the repository URL from the Git configuration instead of requiring users to specify it on each command-line invocation. Unfortunately, the code in charge of this behavior blindly assumes HTTPS as the remote URL protocol, and some self-hosted GitLab instances use plain old HTTP instead.

https://github.com/iterative/cml/blob/6c451d965aaea2ad2b1812dd2a223def9ce87739/src/cml.js#L30-L36

Ideally, the `gitRemoteUrl` function should check both HTTPS and plain HTTP (in that order) and return the first valid URL after issuing a network request to make sure that there is a server listening on the specified address.

```javascript
let error;
for (const type of ['https', 'http']) {
  const repoUrl = stripAuth(gitUrlParse(url).toString(type));
  try {
    await fetch(repoUrl);
    return repoUrl;
  } catch (err) {
    error = err;
  }
}
throw error;
```

Unfortunately it's not that easy, because the `gitRemoteUrl` function is being called from the constructor of the`CML` class, and constructors can't be asynchronous. The only solution I can think of would be resorting to the same approach as in https://github.com/iterative/cml/issues/463#issuecomment-813351066.

<sub>DCLXVI #616 🤣 </sub>

**Comment by DavidGOrtega** [comment]
You have to take in mind also that fetch wont work without SSL or allow insecure

**Comment by 0x2b3bfa0** [comment]
> _We have to take in mind also that fetch wont work without SSL or allow insecure_

As far as I can test, `fetch` **does** work _without SSL_ (actually TLS on sane systems), but doesn't allow insecure connections over HTTPS. We can remediate both cases with something like this:

```javascript
const fetch = require('node-fetch');
const https = require('https');

await fetch(repoUrl, {
  agent:
    repoUrl.startsWith('https') &&
    new https.Agent({
      rejectUnauthorized: false,
    }),
});
```

**Comment by DavidGOrtega** [comment]
Or course we can override insecure connections. ```NODE_TLS_REJECT_UNAUTHORIZED``` will also work like we already know. The question is if we should allow it.

**Comment by 0x2b3bfa0** [comment]
> _Of course we can override insecure connections. `NODE_TLS_REJECT_UNAUTHORIZED` will also work like we already know. The question is if we should allow it._

A considerable amount of private GitLab instances are being deployed in an isolated network with no fully qualified domain name, so getting a recognized certificate authority to sign you a certificate is not possible under normal circumstances, let apart getting it for free.

Because of this, many organizations choose to either:

1. Use HTTPS with self-signed certificates and manually add their custom root certificate to the systems' trust store
   - [X] Protected from passive attacks
   - [X] Protected from active attacks

2. Use HTTPS with self-signed certificates and ignore verification, like in `NODE_TLS_REJECT_UNAUTHORIZED`
   - [X] Protected from passive attacks
   - [ ] Protected from active attacks
   
3. Use plain HTTP without any kind of authentication, signing nor encryption mechanism
   - [ ] Protected from passive attacks
   - [ ] Protected from active attacks

Unfortunately, **(2)** is a fairly common scenario and we should support it somehow. We could add a `--insecure` flag (like in the `curl` command line tool) to all the relevant CML commands, or simply require users to explicitly set the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable.

I'd recommend to keep the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable as the only way of allowing insecure HTTPS connections **and** encourage people to configure their systems to follow **(1)** whenever possible.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega,  to avoid going off at a tangent, the action points to solve this issue are the following:

1. Refactor the CML class to call `gitRemoteUrl` on demand instead of calling it from the constructor. See https://github.com/iterative/cml/issues/463#issuecomment-813351066 and https://github.com/iterative/cml/issues/463#issuecomment-813372984 for a reference implementation.
2. Refactor the `gitRemoteUrl` function to try both the `https` and `http` protocols in that order and return as soon as one of them doesn't produce a `fetch` error.

**Comment by 0x2b3bfa0** [comment]
#### Discord messages showing similar symptoms
* [Discord/#cml/857985384960491570](https://discord.com/channels/485586884165107732/728693131557732403/857985384960491570): unrelated, see #608 
* [Discord/#cml/859003987340034068](https://discord.com/channels/485586884165107732/728693131557732403/859003987340034068): probably related

**Comment by dacbd** [comment]
[seems cursory glance at the currnet state](https://github.com/iterative/cml/blob/4668433d9cef8f792ce4df1417d1682d72464ce6/src/cml.js#L33) im going to guess this is resolved.
