### ISSUE TITLE
--reuse must check if the runner is offline or online

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#621]
If we have a runner offline, mostly because of a failure unregistering them?? Reuse wont work since the --reuse label will find it and wont start.
```--reuse``` should only apply if the runner is online

### Logs
```sh
Run cml-runner \
  cml-runner \
  --reuse \
  --cloud-spot \
  --cloud aws \
  --cloud-region us-west \
  --cloud-type g3.4xlarge \
  --cloud-hdd-size 64 \
  --labels gpu
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    REPO_TOKEN: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Reusing existing runners with the gpu labels...
```

**Comment by ivyleavedtoadflax** [comment]
Ahh maybe this is the same as https://github.com/iterative/cml/issues/610?

**Comment by 0x2b3bfa0** [comment]
Thanks for linking the issue, @ivyleavedtoadflax! Yes, it's related to #610: we should only consider online runners, even if we don't care about their busy/idle status.
