### ISSUE TITLE
How necessary is it to use a Personal Access Token?

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [iterative/cml#625]
Just reading [github's guidance](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#potential-impact-of-a-compromised-runner) on hardening workflow instances. Their guidance is not to use Personal Access Tokens (PATs) in actions. I'm just wondering if there is a way around using them in CML workflows?

**Comment by 0x2b3bfa0** [comment]
Unfortunately, the [only way](https://docs.github.com/rest/reference/actions#create-a-registration-token-for-a-repository) of registering self-hosted runners without user interaction depends on either a [personal access token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) or a [GitHub App](https://docs.github.com/en/developers/apps) token.

Ideally, you should be able to use the ephemeral [GitHub Actions tokens](https://docs.github.com/es/actions/reference/authentication-in-a-workflow) generated fro each run — in combination with explicit [`permissions`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions) — to register self-hosted runners, but none of the available scopes is allowed to access this functionality.

**Comment by 0x2b3bfa0** [comment]
Commands other than `cml-runner` should not require a personal access token to work as expected.

**Comment by 0x2b3bfa0** [comment]
As per [the GitHub documentation](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#considering-cross-repository-access) you link on https://github.com/iterative/cml/issues/625#issue-933118686, 

> * _You should never use personal access tokens from your own account. These tokens grant access to all repositories within the organizations that you have access to, as well as all personal repositories in your user account. This indirectly grants broad access to all write-access users of the repository the workflow is in. In addition, if you later leave an organization, workflows using this token will immediately break, and debugging this issue can be challenging._
>
> * _If a personal access token is used, it should be one that was generated for a new account that is only granted access to the specific repositories that are needed for the workflow. Note that this approach is not scalable and should be avoided in favor of alternatives, such as deploy keys._

While we don't recommend users to go to great lengths and create a separate GitHub account for each repository in order to generate granular personal access token, it seems a sensible security recommendation.

There is sensible and practical alternative, though. You can create a [GitHub App](https://docs.github.com/en/developers/apps), authorize it to your repository, and use the resulting token instad of the personal one.

**Comment by 0x2b3bfa0** [comment]
The official end to end tests on the [actions/runner](https://github.com/actions/runner) repository [seem to use a personal access token](https://github.com/actions/runner/blob/fc4027b3f1ea66e26c334a2142da25a34f10ec8c/.github/workflows/e2etest.yml#L169), by the way.

**Comment by ivyleavedtoadflax** [comment]
Thanks for the in depth answer @0x2b3bfa0. I'll look into the GitHub App approach, but agree ephemeral tokens would be ideal, hopefully GitHub will action your feature request :+1:

**Comment by 0x2b3bfa0** [comment]
You're welcome! I also hope so.

**Comment by 0x2b3bfa0** [comment]
🔔  @iterative/cml, should we close this issue and (optionally) integrate it as part of the documentation, or leave it open to track the GitHub feature request?

**Comment by casperdcl** [comment]
The usual approach is to use a PAT of a bot account, where the bot itself is granted minimal permissions. [As you say](https://github.com/iterative/cml/issues/625#issuecomment-871350566), GH itself does this.

**Comment by ivyleavedtoadflax** [comment]
Would you consider adding some more information in the documentation on how best to do this?

**Comment by 0x2b3bfa0** [comment]
> [_User accounts are intended for humans, but you can give one to a robot, such as a continuous integration bot, if necessary._](https://docs.github.com/es/get-started/learning-about-github/types-of-github-accounts#personal-user-accounts)

A bot account is just a separate GitHub user account created with the only purpose of performing automated actions.

**Comment by 0x2b3bfa0** [comment]
Bot accounts, as @casperdcl, are the usual (and probably more convenient) approach for this use case, but you can also use a GitHub App to achieve the same in a more idiomatic way. You can get a token for your newly created application by following [this guide](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps).

As per the [_permission on administration_](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-administration) and [_permission on self-hosted runners_](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-self-hosted-runners) sections of the GitHub Apps documentation, you should give read and write access to (at least) one of the following permissions:

1. **For repository-level runners:** <kbd>Repository permissions</kbd> → <kbd>Administration</kbd> → <kbd>Access: read & write</kbd>
2. **For organization-level runners:** <kbd>Organization permissions</kbd> → <kbd>Self-hosted runners</kbd> → <kbd>Access: read & write</kbd>

For many of our use cases, **(1)** should be enough, given that we usually recommend the use of repository-level runners.

**Comment by ivyleavedtoadflax** [comment]
Perfect, Thanks @0x2b3bfa0

**Comment by 0x2b3bfa0** [comment]
**Remaining action points**

* https://github.com/iterative/cml/issues/625#issuecomment-871382710
* https://github.com/iterative/cml/issues/652

> 🔔 _@iterative/cml[, should we close this issue and (optionally) integrate it as part of the documentation, or leave it open to track the GitHub feature request?](https://github.com/iterative/cml/issues/625#issuecomment-871382710)_

**Comment by casperdcl** [comment]
#652 is an epic.
#625 meanwhile should only be closed after:

> move text from this issue to the documentation

**Comment by 0x2b3bfa0** [comment]
Moved to https://cml.dev/doc/self-hosted-runners
