### ISSUE TITLE
GH runner version alignment to avoid delays

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#641]
GH runner updates itself with latest version before being operative adding more delay to the startup.
We should implement a mechanism that updates the version that we are downloading to the latest one.

**Comment by 0x2b3bfa0** [comment]
(Related to #615) 🤖

**Comment by 0x2b3bfa0** [comment]
> _We should implement a mechanism that updates the version that we are downloading to the latest one._

Or, preferably, start by downloading the latest version.

**Comment by DavidGOrtega** [comment]
> Or, preferably, start by downloading the latest version.

We are saying the same. I think we wont have a ```latest``` link but a versioned one if we have to determine which is

**Comment by casperdcl** [comment]
fixed by #679
