### ISSUE TITLE
Support for Bitbucket Cloud Pipelines self-hosted runners

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#646]
BB is offering self hosted runners in beta.

**Comment by 0x2b3bfa0** [comment]
Related to (or duplicate of) #140?

**Comment by DavidGOrtega** [comment]
There are two BB

**Comment by 0x2b3bfa0** [comment]
Then, this is just for Bitbucket Cloud Pipelines and not for Bitbucket Data Center, right? While I'd consider merging this issue with #140, it might be fine to keep both as long as they track different tasks.

See also the [official announcement](https://community.atlassian.com/t5/Bitbucket-Pipelines-articles/Bitbucket-Pipelines-Runners-is-now-in-open-beta/ba-p/1691022), the [documentation](https://support.atlassian.com/bitbucket-cloud/docs/runners) and [this guide](https://support.atlassian.com/bitbucket-cloud/docs/set-up-and-use-runners-for-linux)

**Comment by 0x2b3bfa0** [comment]
Bitbucket officially supports self-hosted runners: https://iterativeai.slack.com/archives/C700E1B3Q/p1630099128011300

**Comment by Moynihan18** [comment]
Received a request for this feature from a prospective customer. Has there been any movement on this?

**Comment by 0x2b3bfa0** [comment]
@Moynihan18, see #798
