### ISSUE TITLE
CML <-> DVC push

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#656]
Try to push dvc ephemeral commits

**Comment by 0x2b3bfa0** [comment]
Won't work out of the box for GitHub, see https://github.com/iterative/cml/issues/560#issuecomment-852250748 and dulwich/dulwich#882

**Comment by DavidGOrtega** [comment]
Does not have to be in DVC, its just only find out a mechanism in CML

**Comment by 0x2b3bfa0** [comment]
Here you're a quick patch from my test repository:

```bash
# Dulwich headless authentication patch for GitHub Actions
# See https://github.com/iterative/cml/issues/560#issuecomment-852250748

credentials="$(
  git config --local http.https://github.com/.extraheader |
  awk '{print $3}' |
  base64 --decode
)"

address="$(
  git config --local remote.origin.url |
  sed 's/^https:\/\///'
)"

git config --local remote.origin.url "https://$credentials@$address"
git config --local user.email "action@github.com"
git config --local user.name "GitHub Action"
```

**Comment by 0x2b3bfa0** [comment]
And, believe me, it would be easier to have it fixed in DVC.

**Comment by casperdcl** [comment]
also related to https://github.com/iterative/dvc/issues/6823#issuecomment-1072991559?

**Comment by dacbd** [comment]
out of our control for the time being, https://github.com/jelmer/dulwich/issues/882
