### ISSUE TITLE
Files not being created in the repository

### ISSUE THREAD

**Issue by JayThibs** [iterative/cml#658]
I've been following the tutorial here: https://www.youtube.com/watch?v=9BgIDqAzfuA

I made some modifications to the file structure and I'm running into some errors in this repository: https://github.com/JayThibs/github-actions-ml-template

Essentially, I'm expecting github actions to create the three files it's supposed to create in training/outputs/, but the files are nowhere to be found. When I run the code on my own machine it works, but when I'm using github actions to run the code, it only works if I set the files to be created at the root of the repository. How can I resolve this?

**Comment by 0x2b3bfa0** [comment]
@JayThibs, CML isn't going to automatically commit any changes you make to the repository during the workflow execution, if that's what you mean. You can either use `cml-pr training/outputs/*` to create a pull request with the changes or just commit everything manually with `git commit` and `git push` like this:

```bash
git config --local user.email "action@github.com"
git config --local user.name "GitHub Action"

git add training/outputs/*
git commit --message "Commit training outputs"
git push
```

Please keep in mind that the latter solution won't handle merge conflicts gracefully if there is a race condition between several simultaneous runs.

**Comment by JayThibs** [comment]
@0x2b3bfa0 Thanks, it works! I will consider both approaches depending on the task. For now I've used the first approach. The second approach is more automated (I don't need to use a github secret token in this case) so I may end up using it more. However, I'll keep your word of caution.

Do you know if there's a way I can make it so that the Action isn't run again once the files are pushed? Because otherwise, this will cause the Action to be run twice...

**Comment by 0x2b3bfa0** [comment]
@JayThibs, not sure about your specific setup, but `cml-pr` commits contain the `[skip ci]` string in the message to avoid triggering the workflow again.

If you want to achieve the same result with the proposed alternative `git push` method, you shouldn't need to worry about repeated runs either. Pushes made with the default token used by `actions/checkout@v2` shouldn't trigger new workflow runs.

**Comment by JayThibs** [comment]
@0x2b3bfa0 In my case, I trigger the Action when there's a new push. Are you saying I need to add a --skip-ci flag? Because at the moment I added `cml-pr training/outputs/*` and it's triggering the CI.

**Comment by 0x2b3bfa0** [comment]
I mean `git commit --message "Add some files [skip ci]"` (verbatim)

**Comment by JayThibs** [comment]
Ok that's perfect! Thank you so much. I'm still getting used to GitHub Actions, but couldn't find anything about [skip ci]. Didn't look hard enough I guess.

Anyway, this resolve my issue. I will close this now.

**Comment by 0x2b3bfa0** [comment]
Glad to hear that!
