### ISSUE TITLE
Azure TFS and CML

### ISSUE THREAD

**Issue by RostyslavBryiovskyi** [iterative/cml#660]
Hi all! Thanks for your great tools!:)
Can I use CML with Azure TFS somehow ?

**Comment by 0x2b3bfa0** [comment]
👋🏼  Welcome, @RostyslavBryiovskyi! Would you like to use self-hosted Azure Pipelines runners from Azure DevOps Server (formerly **T**eam **F**oundation **S**erver) in conjunction with CML? If so, maybe we can merge this issue with #142

**Comment by RostyslavBryiovskyi** [comment]
> 👋🏼 Welcome, @RostyslavBryiovskyi! Would you like to use self-hosted Azure Pipelines runners from Azure DevOps Server (formerly **T**eam **F**oundation **S**erver) in conjunction with CML? If so, maybe we can merge this issue with #142; it's on our roadmap.

@0x2b3bfa0, thankful for your quick reply!👍 Yeah, 
It would be great, and I'm looking forward to that😊
Could you please tell me, how long it will take ?

**Comment by 0x2b3bfa0** [comment]
Duplicate of #142

**Comment by 0x2b3bfa0** [comment]
> _Could you please tell me, how long it will take?_

We haven't started to implement it yet. Please stay tuned to #142 for updates and, optionally, upvote it so we can keep track of the interested users.
