### ISSUE TITLE
Single accepts only one job but does not cleanup

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#662]
And strangely appears as offline.

![image](https://user-images.githubusercontent.com/414967/126157697-b70eb645-8881-4406-af14-8bf43fcd305f.png)

**Comment by DavidGOrtega** [comment]
related to #649

**Comment by 0x2b3bfa0** [comment]
Missing `process.on('exit', () => shutdown(opts));` on the `cml-runner` script?
