### ISSUE TITLE
Jest execution time is getting higher

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#664]
For some reason execution time is increasing...

**Comment by 0x2b3bfa0** [comment]
> _For some reason_

Either API calls have become slower or we're issuing more of them... In the past, something similar happened because our dummy pull request had hundreds of comments.

**Comment by DavidGOrtega** [comment]
> In the past, something similar happened because our dummy pull request had hundreds of comments.

I supposed that and updated the sha, it did not help

**Comment by 0x2b3bfa0** [comment]
> _I supposed that and updated the sha, it did not help_

It might not be (just) the commit hash, but also the assigned pull request. Bitbucket treats both kinds of comments separately.
