### ISSUE TITLE
cml-runner: GCP runner is terminating right after the start

### ISSUE THREAD

**Issue by aguschin** [iterative/cml#665]
First of all, I don't know whether this is an issue in this particular CI or some bug in CML. The problem is that runner is terminated right after it starts:
```
$ cml-runner --cloud-spot \ --cloud gcp \ --cloud-region us-west1 \ --cloud-type e2-standard-2 \ --idle-timeout 3000 --labels cml-runner
Preparing workdir /home/runner...
Launching gitlab runner
{"level":"info","date":"2021-07-T09:49:00.352Z","repo":"https://gitlab.com/iterative.ai/demo_use_cases/siim_covid19/siim_covid19"}
{"level":"info","date":"2021-07-T09:49:00.353Z","repo":"https://gitlab.com/iterative.ai/demo_use_cases/siim_covid19/siim_covid19","status":"ready"}
{"level":"info","status":"terminated"}
Unregistering runner cml-7hau9vncvk...
{"level":"info","date":"2021-07-T09:54:22.272Z","repo":"https://gitlab.com/iterative.ai/demo_use_cases/siim_covid19/siim_covid19"}
	Success
```

The job itself is here: https://gitlab.com/iterative.ai/demo_use_cases/siim_covid19/siim_covid19/-/jobs/1440757749

If this is not a bug in CML, then we'd probably still don't want to treat this as a "successful" execution of cml-runner command.

It worked with Azure few commits ago. The commit which introduced the change is b5a19d04b4007c0c9baa9d372762d34c65b94f55 https://gitlab.com/iterative.ai/demo_use_cases/siim_covid19/siim_covid19/-/commits/feature/ci-gcp/

GOOGLE_APPLICATION_CREDENTIALS is set up in the repo's CI.

**Comment by 0x2b3bfa0** [comment]
@aguschin, I don't have access to that repository. 🤔

**Comment by DavidGOrtega** [comment]
For the record:

```sh
 cml-runner --cloud-spot \ --cloud gcp \ --cloud-region us-west1 \ --cloud-type e2-standard-2 \ --idle-timeout 3000 --labels cml-runner
```

Gitlab does not support backslashes, does not need it.

```
cml-runner 
       --cloud-spot
      --cloud gcp
      --cloud-type e2-standard-2
      --idle-timeout 3000
      --labels cml-runner
```

also ```us-west1``` is not a valid region
