### ISSUE TITLE
Investigate why CML AMI is not present on us-west-1

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#670]
https://github.com/iterative/terraform-provider-iterative/issues/167 happens because TPI falls back to ubuntu. Then cml can not be installed due to the lack of node js. Im working on a fix in te TPI to setup the stack completely if missing it. 

This issue is just to check why the images can not be found.

**Comment by 0x2b3bfa0** [comment]
Mitigated with https://github.com/iterative/terraform-provider-iterative/commit/aec00d68d84c82d6bcb81e8da6720732b284811e

**Comment by DavidGOrtega** [comment]
I hav to check other regions... but users are reporting ```us-east-1``` as the original region where cml-runner were not found

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0

**Comment by 0x2b3bfa0** [comment]
Mitigated with https://github.com/iterative/terraform-provider-iterative/pull/170; images will be updated as part of the https://github.com/iterative/viewer-itops/issues/59 saga.
