### ISSUE TITLE
Failed parsing log: Unexpected token { in JSON at position 153

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#671]
### From Discord [#cml (comment)](https://discord.com/channels/485586884165107732/728693131557732403/868831336704639036)

```console
$ cml-runner --cloud=aws --cloud-region=us-east-1 --cloud-type=t2.large
```
```console
-- Logs begin at Sat 2021-07-24 20:03:53 UTC, end at Sun 2021-07-25 11:15:20 UTC. --
Jul 25 11:10:02 ip-172-31-4-59 systemd[1]: Started cml.service.
Jul 25 11:10:17 ip-172-31-4-59 cml.sh[12772]: Preparing workdir /tmp/tmp.vnyMsh2f6x/.cml/cml-ds05uj5g8d...
Jul 25 11:10:17 ip-172-31-4-59 cml.sh[12772]: Launching gitlab runner
Jul 25 11:10:19 ip-172-31-4-59 cml.sh[12772]: EC2 id i-085cbd9f31fb95232
Jul 25 11:10:19 ip-172-31-4-59 cml.sh[12772]: Failed parsing log: Unexpected token { in JSON at position 153
```

https://github.com/iterative/cml/blob/b5c1afb285918ec08cdff89d373213bfdc6b80b6/src/cml.js#L203

Maybe related to the changes on https://github.com/iterative/cml/pull/583#discussion_r657404794...

**Comment by 0x2b3bfa0** [comment]
Unable to reproduce 🤔

**Comment by DavidGOrtega** [comment]
This happens sometimes. It's not new. Maybe comes empty lines.

**Comment by DavidGOrtega** [comment]
We should print the data at least to know whats going on

**Comment by DavidGOrtega** [comment]
a successfully registered GL log:

```sh
Preparing workdir /home/runner...
Launching gitlab runner
{"level":"info","date":"2021-07-26T06:50:27.680Z","repo":"https://gitlab.com/iterative.ai/fashion_mnist"}
{"level":"info","date":"2021-07-26T06:50:27.681Z","repo":"https://gitlab.com/iterative.ai/fashion_mnist","status":"ready"}
```

**Comment by 0x2b3bfa0** [comment]
> We should print the data at least to know whats going on

Like in #672?

**Comment by 0x2b3bfa0** [comment]
Update: this issue will remain open until we manage to reproduce the error and get a copy of the offending JSON as per #672

**Comment by 0x2b3bfa0** [comment]
Related to errors in https://github.com/iterative/cml/issues/808#issuecomment-965391770

**Comment by dacbd** [comment]
perhaps its time close with https://github.com/iterative/cml/pull/1030 ?
