### ISSUE TITLE
MaxSpotInstanceCountExceeded in GL tests due to GPU

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#675]
We have a difficult scenario having MaxSpotInstanceCountExceeded errors. Probably reuse will solve this

**Comment by 0x2b3bfa0** [comment]
If we enable the `--reuse` option, unit tests won't [always] cover the runner creation process. Do we want that?

**Comment by casperdcl** [comment]
@shcheklein found that there are multiple instances running for about a week. We need:

- [ ] automatic warning (email etc.) if instances run for more than e.g. 30min
- [ ] automatic shutdown of instances (timeout)
- [ ] figure out why CML didn't cleanly terminate the instances

`--reuse` will only hide the problem without solving it

**Comment by DavidGOrtega** [comment]
related to #680 

This might be related to #678 after seeying the logs seems that the chrono is not working properly

**Comment by casperdcl** [comment]
also https://github.com/cloud-custodian/cloud-custodian (@dberenbaum suggestion)

**Comment by dacbd** [comment]
We haven't seen this in a while, closing for now.
