### ISSUE TITLE
Unexpected stop of container build [CML, AWS, github]

### ISSUE THREAD

**Issue by sergeychuvakin** [iterative/cml#676]
My scenario:
I'm trying to create appropriate pipeline for my ML project. I'm using the following CML yaml file:
```
on:
  # Trigger the workflow on push or pull request
  push:
    branches:
      - mybranch

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on EC2
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
        run: |
          cml-runner \
              --repo https://github.com/MyCompany/myrepo \
              --token=$PERSONAL_ACCESS_TOKEN \
              --cloud aws \
              --cloud-region us-west-1 \
              --cloud-type=g3.4xlarge \
              --labels=cml-runner \
              --idle-timeout 30
    
  model-training:
    needs: [deploy-runner]
    runs-on: [self-hosted, cml-runner]
    container:
      image: docker://dvcorg/cml:0-dvc1-base1-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Train model
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DVC_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DVC_SECRET_KEY }}
          REQUIREMENTS_FILE: 'training/training_req.txt'
        run: |
          export AWS_DEFAULT_REGION=us-east-1
          echo "Install reqs"
          sudo apt update
          sudo apt-get install default-jre scala
          pip install py4j
          pip install --no-cache-dir -e .
          export PYSPARK_PYTHON=python3
          echo "Start CML"
          python3 -m spacy download en_core_web_sm
          echo "Pull data"
          dvc repro
          echo "## Model metrics" > report.md
          cat prepare_data/metrics.txt >> report.md
          cml-send-comment report.md
          

```
As you can notice I used the following image docker://dvcorg/cml:0-dvc1-base1-gpu, but I started receive the following error message:

<img width="506" alt="Screenshot 2021-07-27 at 20 22 31" src="https://user-images.githubusercontent.com/33733128/127202138-a072b13b-3c3f-49cc-b43c-fd5a8c06db2a.png">
<img width="997" alt="Screenshot 2021-07-27 at 20 24 36" src="https://user-images.githubusercontent.com/33733128/127202146-1c14495f-da21-412f-b8d5-75169eace54c.png">

I can see that container started to build but unexpectedly stopped, and I do not see the reason of this behavior. Actually i did not change anything in my script, and it just stopped work, but earlier I run it successfully. 

Thanks!

**Comment by sergeychuvakin** [comment]
Full logs archive. 
[logs_261.zip](https://github.com/iterative/cml/files/6887653/logs_261.zip)

**Comment by DavidGOrtega** [comment]
@sergeychuvakin thanks for reporting. Im checking.

**Comment by DavidGOrtega** [comment]
With self hosted runners this is happening too

**Comment by DavidGOrtega** [comment]
Ok, GH runner seems to be restarting due to updates. This is a new behaviour

> Runner will exit shortly for update, should back online within 10 seconds.

**Comment by sergeychuvakin** [comment]
> Ok, GH runner seems to be restarting due to updates. This is a new behaviour
> 
> > Runner will exit shortly for update, should back online within 10 seconds.

Ok, thank you for investigation! Appreciate your efforts, looking forward to updates

**Comment by casperdcl** [comment]
doesn't seem fixed (yet)

**Comment by DavidGOrtega** [comment]
fixed! Seems that the error that appeared later on was a hicup. I have tried multiple times successfully

**Comment by sergeychuvakin** [comment]
Thanks! I was able to run it as well.
