### ISSUE TITLE
tests: GCP

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#680]
Due to https://github.com/iterative/terraform-provider-iterative/pull/156, GCP should be supported.

- [x] Fix bugs (#678?)
- [ ] #921 
- [x] Update README (#717)
- [x] Update https://cml.dev/doc (https://github.com/iterative/cml.dev/pull/105)

**Comment by casperdcl** [comment]
start of "docs": https://github.com/iterative/terraform-provider-iterative/pull/156, https://github.com/iterative/terraform-provider-iterative/pull/166

**Comment by 0x2b3bfa0** [comment]
# Stub, [from Notion](https://www.notion.so/iterative/Google-Cloud-support-37b8a365496046de8c1d2e1afd21b223)

> ## Prerequisites
> 
> 1. Create a new Google Cloud project ([official documentation](https://cloud.google.com/resource-manager/docs/creating-managing-projects))
> 2. Create a new service account for the newly created project ([official documentation](https://cloud.google.com/iam/docs/creating-managing-service-accounts))
> 3. Create a new service account key for the newly created service account ([official documentation](https://cloud.google.com/iam/docs/creating-managing-service-account-keys))
> 4. Store the contents of the downloaded JSON key as a [GitHub repository secret](https://docs.github.com/es/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) named `GOOGLE_APPLICATION_CREDENTIALS_DATA`
> 
> My failed blog post has [some extra guidance](https://www.notion.so/Introducing-Continuous-Machine-Learning-on-Kubernetes-5fbc3c905805470c8eb59c58592ec017) for GitHub and GitLab and best practices for secret handling in CI/CD environments.
> 
> ## Usage
> 
> ```yaml
> on: workflow_dispatch
> jobs:
>   deploy:
>     runs-on: ubuntu-latest
>     steps:
>       - uses: iterative/cml@v1
>       - run: >-
>           cml-runner
>           --cloud=gcp 
>           --cloud-region=us-west1-b
>           --cloud-type=custom-8-65536-ext
>           --cloud-gpu=v100
>         env:
>           REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
>           GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
>   deploy:
>       runs-on: self-hosted
>       steps:
>         - run: nvidia-smi
> ```
> 
> The `--region` option specifies what Google Cloud calls **zones***,* not **regions** **like in other cloud vendors.
> 
> You can check [this list](https://cloud.google.com/compute/docs/gpus/gpu-regions-zones) to determine which zones provide GPU accelerators and which models are available. Not every zone has availability for every GPU model.
> 
> Custom machine types can be specified with `custom-{cores}-{memory}` where `{cores}` represents the number of CPU cores and `{memory}` represents the RAM memory in megabytes; appending the `-ext` suffix will also enable [extended memory](https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#gcloud).
> 
> GPU accelerators are only available on [N1](https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines) and [A2](https://cloud.google.com/compute/docs/accelerator-optimized-machines#a2_machines) machines. Trying to request accelerators in any other machine will produce an error. 
> 
> ## Authentication
> 
> You can set either the `GOOGLE_APPLICATION_CREDENTIALS_DATA` environment variable to the **contents** of a service account JSON file, or the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to the **path** of the mentioned file.
> 
> The former is more convenient for CI/CD scenarios, where secrets are (usually) provisioned through environment variables instead of files.

**Comment by 0x2b3bfa0** [comment]
> /tests

Hwat? [[sic]](https://en.wikipedia.org/wiki/Sic)

**Comment by 0x2b3bfa0** [comment]
https://github.com/iterative/cml/issues/680#issuecomment-900616914 contains some valuable bits and pieces we don't have anywhere else. 🤔 Should they be promoted to cml.dev/doc?
