### ISSUE TITLE
Feature Request: Automated testing when merging to main

### ISSUE THREAD

**Issue by davesteps** [iterative/cml#681]
If we assume our currently deployed model is on the main branch. When we train a better model on a new branch and we decide to merge into main, we want to run some CI/CD tests that will confirm our branch is ok to merge. In particular we want to test that 1) all of the dvc tracked files have been pushed to the remote and 2) if you run dvc status it return something like ‘All data and pipeline up to date.’. We have set up some python tests to confirm this but it doesn’t seem the most robust. Could there be some CML function to do this in a more formal way?

FYI I [asked this on he forum](https://discuss.dvc.org/t/automated-testing-when-merging-to-main/826) and was asked to open it as an issue. 

Thanks.

**Comment by DavidGOrtega** [comment]
@davesteps thanks for the feature

**Comment by davesteps** [comment]
I think this would actually be covered by the dvc feature discussed here: https://github.com/iterative/dvc/issues/5369

**Comment by dacbd** [comment]
Closing in favor of the linked issue, @davesteps if you want us/cml to revisit this feel free to reopen the issue.

**Comment by casperdcl** [comment]
I assume it would be something like

```bash
cml send-github-check --status queued
pip install ...
cml send-github-check --status in_progress
dvc verify && cml send-github-check --conclusion success || cml send-github-check --conclusion failure
```
