### ISSUE TITLE
Docker with latest version of Cuda

### ISSUE THREAD

**Issue by bhaswa** [iterative/cml#685]
Hi,

The provided docker cml-py3:latest supports cuda 10.1 only. Do you have any plan to release a docker image with later version of Cuda support?

Thanks in advance.

**Comment by 0x2b3bfa0** [comment]
@bhaswa, the `cml-py3` images have been deprecated. Our [new images](https://github.com/iterative/cml#docker-images) already provide CUDA 11.

```
iterativeai/cml:0-dvc2-base1-gpu
```
