### ISSUE TITLE
Error: REPO_TOKEN does not have enough permissions to access workflow API

### ISSUE THREAD

**Issue by quyetvk** [iterative/cml#688]
Hi!

I am trying to create self-hosted runner according to https://dvc.org/blog/cml-self-hosted-runners-on-demand-with-gpus
But I've got the error 
```
{"level":"error","status":"terminated"}
Error: REPO_TOKEN does not have enough permissions to access workflow API
    at CML.repo_token_check (/cml/src/cml.js:236:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
        Destroy scheduled: 30 seconds remaining.
        No TF resource found
```

My command are:
`docker run --name gpurunner --gpus all -e RUNNER_IDLE_TIMEOUT=1000 -e RUNNER_LABELS=cml,gpu -e RUNNER_REPO="https://<my_domain>/gitlab/<my_project_path_without_git_at_end>" -e repo_token="<my_personal_token>" dvcorg/cml-py3`

"my_personal_token" was generated by go to "Edit Profile" > "Access Tokens" > create new token (permission is "Api" and I also try to enable all permission)

I executed above command in my AI training server

`Self-hosted gitlab server (public)      <--------> AI Training Server`

Could you please tell me what wrong I did?
Thank you in advanced!

P/S: I also referred to https://github.com/iterative/cml/issues/562

**Comment by 0x2b3bfa0** [comment]
👋🏼  Welcome, @quyetvk! Can you please run again your command using [`iterativeai/cml:0-dvc2-base1-gpu`](https://github.com/iterative/cml#docker-images) instead of `dvcorg/cml-py3` as the container image? The latter is deprecated.

**Comment by 0x2b3bfa0** [comment]
Closing after a week of inactivity. Feel free to reopen the issue if you keep seeing this error after migrating to the new container.
