### ISSUE TITLE
Tests hang forever

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#694]
This happens due to tbLink implementation.
This is due to a weird Jest condition with promises and setInterval.

**Comment by 0x2b3bfa0** [comment]
Is this related to #674?

**Comment by DavidGOrtega** [comment]
yes @0x2b3bfa0

**Comment by DavidGOrtega** [comment]
What is happening is that jest is hang forever. 
I thought it was a combination of both, but seems that the issue is other and has appeared for every single PR??

**Comment by 0x2b3bfa0** [comment]
> _What is happening is that jest is hang forever._

Exactly! And it's getting killed by GitHub-hosted Actions' timeout. 🙃

**Comment by 0x2b3bfa0** [comment]
> _I thought it was a combination of both, but seems that the issue is other and has appeared for every single PR??_

That would be the only missing thing to render me completely insane. 🤔

**Comment by DavidGOrtega** [comment]
> > _I thought it was a combination of both, but seems that the issue is other and has appeared for every single PR??_
> 
> That would be the only missing thing to render me completely insane. 🤔


Yea, I can reproduce it without the proxy setup and teardown, you can see it happening also in the jest PR

**Comment by 0x2b3bfa0** [comment]
### Attempts to fix this issue

* #693

### Affected unmerged pull requests
* #674
* #689
* #703

**Comment by 0x2b3bfa0** [comment]
:bell: @DavidGOrtega, continuing the Jest conversation from https://github.com/iterative/cml/pull/703#issuecomment-910345594 

In the case of https://github.com/iterative/cml/pull/703, tests were being blocked by an infinite loop with synchronous calls on `read-pipe.js`; not sure about #674 and #689, but they're probably creative variations of blocked event loop.

**Comment by DavidGOrtega** [comment]
The issue is happening for await and setTimeout...

https://github.com/facebook/jest/issues/7339

among others

**Comment by 0x2b3bfa0** [comment]
In the case of #674, it can't be reproduced outside GitHub Actions. 🤔

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 I know!!! I said this in our CML meetings. The PR works in GL but not in GH.
It has to be an issue with GA combined with Jest
