### ISSUE TITLE
`GIT_USER_NAME` and `GIT_USER_EMAIL`

### ISSUE THREAD

**Issue by duijf** [iterative/cml#697]
Same discussion as https://github.com/iterative/viewer/issues/2399 (Studio internal), but for CML.

Currently, CML creates commits as `olivaw@iterative.ai`. This email address is associated with @iterative-olivaw, which is an account that we use for internal CI purposes. This seems to be specified here:

https://github.com/iterative/cml/blob/fe65e9f1225d4a97a3ffa34ecaf5ce33bf697e26/src/cml.js#L15-L16

Since CML is also used outside of Iterative, we may want to commit with a more "immediately obvious" email address / name to avoid confusion. E.g. create a specific GitHub/GitLab/BitBucket account and the email address `bots+cml@iterative.ai`.

We should also make these settings configurable so users can change the defaults if they wish.

**Comment by DavidGOrtega** [comment]
@duijf Sorry for the inconvenience we thought of our Olivaw[bot] just to expose that the crime was actually done by CML 😄

**Comment by 0x2b3bfa0** [comment]
* Linking to #945

**Comment by dacbd** [comment]
> * Linking to [ci: expose --user-email --user-name #945](https://github.com/iterative/cml/pull/945)

do we consider this issue closed then?

**Comment by casperdcl** [comment]
yes looks like it to me
