### ISSUE TITLE
Docker image dvcorg/cml and iterativeai/cml

### ISSUE THREAD

**Issue by Hongbo-Miao** [iterative/cml#706]
I found both docker image [dvcorg/cml](https://hub.docker.com/r/dvcorg/cml) and [iterativeai/cml](https://hub.docker.com/r/iterativeai/cml).
have same tags and digests.

However,

- The demo at https://github.com/iterative/cml#github is using `iterativeai/cml`.
- The demo at https://github.com/iterative/cml_cloud_case/blob/master/.github/workflows/cml.yaml is using `dvcorg/cml`.

Which one is recommended to use in future? Is it `iterativeai/cml`? Thanks!

**Comment by 0x2b3bfa0** [comment]
Welcome, @Hongbo-Miao! `dvcorg/cml` is a [mirror](https://github.com/iterative/cml/blob/899c6d2e3eaffc66d12492deffa658e8430f1c66/.github/workflows/test-deploy.yml#L122) we keep for backwards compatibility and don't plan to deprecate anytime soon. Nevertheless, `iterativeai/cml` is the [recommended](https://cml.dev/doc/self-hosted-runners#docker-images) image repository.

**Comment by Hongbo-Miao** [comment]
Thanks @0x2b3bfa0 for the info!
