### ISSUE TITLE
Consider using `pino` instead of `winston` for logging

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#709]
It could be a better option, not only because of asthetics, but also because of functionality and apparent project [health](https://snyk.io/advisor/npm-package/pino). Configured logger objects can be passed as suggested on https://github.com/pinojs/pino/issues/1108#issuecomment-913794291.

#### See also

* https://github.com/iterative/cml/pull/703#issuecomment-910773193
* https://github.com/iterative/cml/pull/703#issuecomment-910343160
* https://github.com/pinojs/pino/issues/1108#issuecomment-913794291

**Comment by 0x2b3bfa0** [comment]
### See–it–yourself comparison

```javascript
const pino = require('pino');
const winston = require('winston');

const pinoLogger = pino(
  {
    prettyPrint: {
      ignore: 'pid,hostname',
      translateTime: true,
      colorize: true
    },
    level: 'debug'
  },
  process.stderr
);

const winstonLogger = winston.createLogger({
  level: 'debug',
  format: winston.format.combine(
    winston.format.colorize(),
    winston.format.timestamp({ format: 'YYYY-MM-DD HH:mm:ss.SSS ZZ' }),
    winston.format.simple()
  ),
  transports: [
    new winston.transports.Console({
      stderrLevels: Object.keys(winston.config.npm.levels)
    })
  ]
});

for (logger of [pinoLogger, winstonLogger]) {
  logger.error(new Error('runners are exhausted because of cloud altitude'));
  logger.warn('the personal access token has been written backwards');
  logger.info('no bot dared to comment on your last commit');
  logger.debug('this repository contains files');
}
```

**Comment by DavidGOrtega** [comment]
I do not understand what do you want to showcase with this example. Whats the main difference?

**Comment by 0x2b3bfa0** [comment]
1. Full and readable stack traces for errors
2. Object formatting

**Comment by dacbd** [comment]
`p3-cool-if-someone-is-really-bored-on-a-weekend` or `p4-graveyard`?

**Comment by 0x2b3bfa0** [comment]
`p5-low-priority-enough-to-postpone-choosing-a-priority`
