### ISSUE TITLE
Is there a way to only keep the last cml-send-comment report in the merge request overview?

### ISSUE THREAD

**Issue by saadlaaribi** [iterative/cml#719]
After creating a CML workflow, I start to get a new cml-send-comment report on my merge request overview after each commit. This can be annoying because your merge request overview can be spammed by similar reports made for commits that doesn't  change your ML pipeline (e.g. Fixing some comment typos).
Is there a way of automatically deleting previous reports and only keeping the report created for the last commit?

**Comment by 0x2b3bfa0** [comment]
👋🏼 Welcome, @saadlaaribi! You can use `cml-publish --update` to update the same comment over and over instead of creating new ones.

**Comment by saadlaaribi** [comment]
I am sorry, I made a mistake. I am talking about the comments made by the cml-send-comment command, not the cml-publish.
I apologise for the confusion.

**Comment by 0x2b3bfa0** [comment]
Me too! Both of us were thinking about `cml-send-comment` and writing `cml-publish` :facepalm:

**Comment by saadlaaribi** [comment]
I tried to use cml-send-comment --update on dvcorg/cml-py3 docker, but it doesn't seem to be a valid option.

**Comment by 0x2b3bfa0** [comment]
@saadlaaribi, `dvcorg/cml-py3` is deprecated, can you please try `iterativeai/cml:0-dvc2-base1-gpu` instead?

**Comment by saadlaaribi** [comment]
@0x2b3bfa0, if I use iterativeai/cml:0-dvc2-base1-gpu docker, the option --update seems to be a valid option, but now I am getting a  "{"level":"error"}" message and the pipeline job fails. Do you know what that means?

**Comment by saadlaaribi** [comment]
@0x2b3bfa0, just did that. Here's the error message:
{"level":"error","message":"GitLab does not support comment updates!","stack":"Error: GitLab does not support comment updates!\n    at Gitlab.commentCreate (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:74:23)\n    at CML.commentCreate (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:107:34)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/send-comment.js:12:15)"}

**Comment by 0x2b3bfa0** [comment]
Oops! As per the [Backend Supported Features](https://github.com/iterative/cml/wiki/Backend-Supported-Features) table, updating commit comments is not supported on GitLab because of [this issue](https://gitlab.com/gitlab-org/gitlab/-/issues/333000)-

**Comment by 0x2b3bfa0** [comment]
@saadlaaribi, I'm closing this issue in favor of https://github.com/iterative/cml/issues/735
