### ISSUE TITLE
Error logging on Github Actions

### ISSUE THREAD

**Issue by DanielBarnes** [iterative/cml#727]
Quality of life issue, within the GitHub actions logs when yargs fails to parse an option it doesn't seem to want to display which argument it failed to parse.

Locally there is no issue:
```bash
~/projects/cml$ ./bin/cml.js runner --fail-arg 
cml.js runner

Launch and register a self-hosted runner

Options:
...

Unknown arguments: fail-arg, failArg
```

However, when this happens on an internal project it does not print the argument as expected:
<img width="337" alt="ghar-error-empty" src="https://user-images.githubusercontent.com/1105843/134251179-0e860216-9e2c-4830-81c2-f9048147b95d.PNG">

[I tried and failed to simply reproduce a similar outcome](https://github.com/DanielBarnes/errrrrr/actions)
But on an internal project, this is consistently reproducible...

I'm not sure if this is a strange error with the GitHub runner environment or something that has to do with the logger is printing/being passed through?

https://github.com/iterative/cml/blob/4508871d60811210481482bc461fcdc245e52c92/bin/cml.js#L10-L26

and here

https://github.com/yargs/yargs/blob/59a86fb83cfeb8533c6dd446c73cf4166cc455f2/lib/usage.ts#L40-L75

If you can spell correctly this isn't an issue...😉 so I'd consider this a very low priority if one at all and `--cloud-startup-scrip` is indeed not an argument 😞

**Comment by DanielBarnes** [comment]
Sooo, if you have a trailing space in your multi-line command the ` ` is parsed as an argument that is not recognized and you get the `Unkown argument:  ` where the argument name that's getting printed is a space.

This is easily detected from your interactive shell determining the end of the command. resulting in bash trying to interrupt the following args as a new command: (space after --idle-timeout=1800 \ )
```bash
cml-runner \
--log \
--single \
--idle-timeout=1800 \  
--token=*** \
--cloud=gcp \
--cloud-region=us-west \
--cloud-type=m \
--cloud-gpu=nogpu
```
results with:

```bash
root@6f2fbfc825d4:/home/runner# cml-runner \
> --log \
> --single \
> --idle-timeout=1800 \ 
cml runner

Launch and register a self-hosted runner

Options:
........

Unknown argument:  
root@6f2fbfc825d4:/home/runner# --token=*** \
> --cloud=gcp \
> --cloud-region=us-west \
> --cloud-type=m \
> --cloud-gpu=nogpu
bash: --token=***: command not found
root@6f2fbfc825d4:/home/runner# 
```

Where the Github actions env execute commands from a file with `bash -e`
so 
```bash
root@6f2fbfc825d4:/home/runner# echo "cml-runner \
> --log \
> --single \
> --idle-timeout=1800 \  
> --token=*** \
> --cloud=gcp \
> --cloud-region=us-west \
> --cloud-type=m \
> --cloud-gpu=nogpu" > test.sh
root@6f2fbfc825d4:/home/runner# bash -e ./test.sh 
root@6f2fbfc825d4:/home/runner# bash -e ./test.sh 
cml runner

Launch and register a self-hosted runner

Options:
 ...........

Unknown argument:  
root@6f2fbfc825d4:/home/runner# 
```

Maybe this is an edge case that could be addressed in yargs?

**Comment by 0x2b3bfa0** [comment]
Well, running `cml runner " "` purposefully would be really evil. 😄  To my mind, this can be mitigated with https://github.com/yargs/yargs/issues/2033, and trying to “solve” it on CML would be suboptimal.

**Comment by DanielBarnes** [comment]
I agree on this is not something that should be resolved in CML, I initially thought there was something strange going on with how the logging was being done.

**Comment by 0x2b3bfa0** [comment]
Shall we close #727 in favor of https://github.com/yargs/yargs/issues/2033?

**Comment by DanielBarnes** [comment]
Close or maybe add an upstream tag as a reminder for a future version bump?

**Comment by 0x2b3bfa0** [comment]
🔔  @iterative/cml ❓

**Comment by casperdcl** [comment]
upstream issue https://github.com/yargs/yargs/issues/2033
