### ISSUE TITLE
GitHub–hosted runners have taken over the `RUNNER_` environment variable prefix

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#738]
Suddenly, GitHub–hosted runners have started to set environment variables with the `RUNNER_` prefix, clashing with the ones we're using on `cml runner` to let users specify command–line options through the environment:

https://github.com/iterative/cml/blob/7d664aec00023e8fba48e660f2f8e184477d8cdd/bin/cml/runner.js#L12

https://github.com/iterative/cml/blob/7d664aec00023e8fba48e660f2f8e184477d8cdd/bin/cml/runner.js#L17-L28

Among others, GitHub–hosted runners are setting `RUNNER_NAME` to esoteric values with uppercase and spaces like `GitHub Actions 3`, causing some cloud vendors to break in unexpected ways.

For example, Google Cloud complains loudly and refuses to create any resources with names containing whitespace:

```console 
Error: Failed creating the machine: googleapi: Error 400: Invalid value for field 'resource.name': 'GitHub Actions 2-egress'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'

More details:
  Reason: invalid, Message: Invalid value for field 'resource.name': 'GitHub Actions 2-egress'. Must be a match of
regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
  Reason: invalid, Message: Invalid value for field 'resource.targetTags[0]': 'GitHub Actions 2'. Must be a match o
f regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
```

AWS also fails because of this, as per https://github.com/iterative/cml/issues/741

#### Workflow
```yaml
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: env | grep ^RUNNER_
```

#### Output
```console
RUNNER_NAME=GitHub Actions 3
RUNNER_OS=Linux
RUNNER_TRACKING_ID=github_···
RUNNER_TEMP=/home/runner/work/_temp
RUNNER_USER=runner
RUNNER_TOOL_CACHE=/opt/hostedtoolcache
RUNNER_WORKSPACE=/home/runner/work/test
RUNNER_PERFLOG=/home/runner/perflog
```

**Comment by DanielBarnes** [comment]
┬──┬ ¯\_(ツ)

┻┻︵ヽ(`Д´)ﾉ︵┻┻

**Comment by 0x2b3bfa0** [comment]
Also seen on https://github.com/iterative/cml/issues/741
