### ISSUE TITLE
publish: Exceeded timeout of 600000 ms for a test

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#749]
I can presume that this [test](https://gitlab.com/iterative.ai/cml/-/jobs/1620410486) consumed 600000 ms which can tell that we might have transient errors in our storage. This might not be a ```technical debt```

```sh
FAIL bin/cml/publish.test.js (617.808 s)
  ● CML e2e › cml publish assets/logo.pdf --md
    thrown: "Exceeded timeout of 600000 ms for a test.
```

**Comment by dacbd** [comment]
Has this ever re-occurred?
