### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#757]
using `/tests`: https://github.com/iterative/cml/runs/3767434423

**Comment by 0x2b3bfa0** [comment]
* https://github.com/nodesource/distributions/issues/1266

**Comment by casperdcl** [comment]
there are some solutions mentioned on that link @0x2b3bfa0

**Comment by 0x2b3bfa0** [comment]
https://github.com/nodesource/distributions/issues/1266#issuecomment-978044871
