### ISSUE TITLE
Environment variable "no_proxy" seems to be unsupported

### ISSUE THREAD

**Issue by oolesen** [iterative/cml#760]
I've been trying to play around with self hosted runners. 

I'm sitting behind a corporate firewall using Github Enterprise, which is also inside the firewall.

I'm using iterativeai/cml:0-dvc2-base1-gpu docker container on a Linux Ubuntu 18.04 machine.
I am fairly confident, my container is set up properly with certificates and proxy settings. For instance can I clone my Github Enterprise repo with no problems. I am also able without any problems to connect an original github runner to my Enterprise repo.

However when I use cml runner, I seem to fail in both of two options:
a) I pass my proxy settings to the docker container, which makes it impossible to reach my Github Enterprise repository (because the proxy is not able to resolve the address).
b) I leave out the proxy settings, so the CML runner can find the Github Enterprise but when it next tries to load the latest Github runner version from github.com, it fails because it doesn't get past the proxy.

It seems to me, that the problem origins in the usage of node-fetch.js, which in turn also only supports either using http/s_proxy or not. But there is no gate evaluating the requested URL and changing the path either through the proxy or not. I'm really no expert in this as you might have guessed after the first few words. So let me try to phrase it in my simple words:

Can you implement cml runner to "respect" the no_proxy setting? Or help me in any other way?

**Comment by DavidGOrtega** [comment]
👋 

```cml-runner```` currently supports ```http_proxy``` and ```https_proxy``` however we do not support ```no_proxy``` yet.
Have you tried to setup ```https_proxy``` using the cml-runner?

**Comment by oolesen** [comment]
Yes, that's what I did. It seems I have two options to fail ;-)
A) I setup http_proxy and https_proxy correctly. Then the cml runner will not find my corporate github, which is also behind the firewall, just like the machine hosting the runner. When asking the proxy for the internal address it fails to resolve it.
B) I don't set up http_proxy/https_proxy. In this case the cml runner will be able to find the corporate github. However it will not be able to reach any address outside corporate firewall, because it doesn't know the proxy

What I would need if cml runner to evaluate the no_proxy setting, which basically says: for every address which matches "no_proxy" don't query the proxy. For all other addresses: query proxy!

Asking boldly: Do you think you can build that in?

**Comment by oolesen** [comment]
That’s really good news! Thanks a lot! Can’t wait to try it out!
