### ISSUE TITLE
CML 0.7.5: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by jamt9000** [iterative/cml#769]
Starting today CI runs using gh actions `iterative/setup-cml@v1` and `cml-runner` are failing with

```
  cml-runner \
  --cloud aws \
  --cloud-region eu-west-1 \
  --cloud-type g4dn.xlarge \
  --labels=$label \
  --cloud-hdd-size 100 \
  --single \
  --no-reuse \
  --cloud-aws-security-group cicd
```

`
{"level":"error","message":"Cannot read property 'map' of undefined","name":"YError","stack":"YError: Cannot read property 'map' of undefined\n    at /usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:29913\n    at j (/usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:4952)\n    at /usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:29809\n    at /usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:4753\n    at Array.reduce (<anonymous>)\n    at C (/usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:4551)\n    at M.applyMiddlewareAndGetResult (/usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:8688)\n    at M.runCommand (/usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:7206)\n    at Jt.[runYargsParserAndExecuteCommands] (/usr/local/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:55967)\n    at Jt.parse (/usr/local/...
`

**Comment by 0x2b3bfa0** [comment]
Our bad, sorry! Fixing with #770...

**Comment by jamt9000** [comment]
Thanks for the quick fix 😄

**Comment by 0x2b3bfa0** [comment]
You're very welcome! Sorry again for the bug.
