### ISSUE TITLE
Error when combining `cml pr` and `cml send-comment --pr`

### ISSUE THREAD

**Issue by daavoo** [iterative/cml#788]
I'm getting the following error:

```json
{
    "level":"error",
    "message":"Cannot destructure property 'url' of 'commitPr' as it is undefined.",
    "stack":"TypeError: Cannot destructure property 'url' of 'commitPr' as it is undefined.\n    at CML.commentCreate (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:126:15)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/send-comment.js:13:15)"
}
```

When combining `cml pr` and `cml send-comment --pr` in the same workflow. 

Here is a minimal example to reproduce:

https://github.com/iterative/test-cml-send-comment-pr

And the failing workflow:

https://github.com/iterative/test-cml-send-comment-pr/runs/4038830121?check_suite_focus=true

**Comment by daavoo** [comment]
> fixed by documentation in #791 and [iterative/cml.dev#138](https://github.com/iterative/cml.dev/pull/138)

I tried `--commit-sha=HEAD` and it fails:

https://github.com/iterative/test-cml-send-comment-pr/actions/runs/1440962182

However, the following works (suggested by @casperdcl):

```
HEAD=$(git log -n1 --format=%h)    
cml send-comment --pr --update --commit-sha=$HEAD report.md
```

https://github.com/iterative/test-cml-send-comment-pr/actions/runs/1441002763
https://github.com/iterative/test-cml-send-comment-pr/pull/3

**Comment by casperdcl** [comment]
Yes we use the GH API (rather than Git directly) for `send-comment --pr` so magic like `HEAD` won't work. We should do

```js
commitSha = exec(`git rev-parse -- ${commitSha}`)
```

**Comment by 0x2b3bfa0** [comment]
Related to https://github.com/iterative/cml/issues/880
