### ISSUE TITLE
CML Instance networking options

### ISSUE THREAD

**Issue by dacbd** [iterative/cml#795]
Using GitHub Actions with AWS in a self-hosted setting.

We have some complicated networking setups in an AWS account that I am trying to migrate projects from a different CI process to GitHub Actions and cml runner.

The Hidden option for an AWS Security Group allows the TF provider to infer which VPC id to use however we have multiple subnets assigned for this virtual network one with public IP addresses and I need to ensure that subnet is not selected (which it has been).

The provider targets the subnet with public IP addresses (to ensure it is reachable for cml I assume?). In this case, cml is running from a self-hosted runner on the internal IP space and would be route-able without a public address.

https://github.com/iterative/terraform-provider-iterative/blob/82d1b6047b728084d8b235e69f181ae608309db8/iterative/aws/provider.go#L201-L213

**Comment by DavidGOrtega** [comment]
> The provider targets the subnet with public IP addresses (to ensure it is reachable for cml I assume?)

Yes, we use ssh to check the runner state to finalise the creation of the resource. We could avoid this but we would not be sure that the runner was deployed properly, aside using the SCMs apis to check that the runner is up an ready. 
We did not choose this approach to no duplicate business logic twice.

**Comment by dacbd** [comment]
I don't think any change in that logic is needed, just if a subnet or other advanced network option is specified the onus is on the user to ensure the instance they are configuring will be routable from the host cml runner is invoked on.

Using the ssh method is fine.

does this help explain?
![example](https://user-images.githubusercontent.com/1105843/140391469-0ffe7c11-e0ae-48d1-acd8-0910a5dac8e4.png)

**Comment by DavidGOrtega** [comment]
We connect using the `instance_public_ip`. The idea would be getting that ip from the net or let the user specify the expected public ip? @dacbd

**Comment by dacbd** [comment]
The idea would be to just use the private IP space connecting with `private_ip`, cml runner is invoked from a self-hosted instance and would be targeting the same network it is on for the cml instance, so besides talking to GitHub, AWS, and loading deps which are all client initiated connections NAT can handle; a public ip would not be required. 

Kind of related to #752 in a way

**Comment by DavidGOrtega** [comment]
@dacbd with cml runner you can launch a self-hosted runner in your network or launch it in your cloud vendor.
In fact the first one will work within any topology. But I guess that you know that already so what I understand is that you might need to have that `private_ip` to be able to do the ssh connection to finish the setup in the cloud vendor.
Is that right?

**Comment by dacbd** [comment]
@DavidGOrtega yes? I don't quite follow your first sentence there.

The root of the issue is cml runner is launching instances with a public IP and I need it to not do that.

The TPI section that I linked above specifically targets a subnet with public IP address which is probably fine for 95% of cases and the majority of users.

If given an additional element (subnet_id or something) override this logic so cml runner does not create an instance with a public IP

No changes to any operational logic should be needed, if the user supplies this "advanced networking option" and creates an instance on a private_ip that's not routable from where cml runner was executed they have successful shot themselves in the foot. However, if I provide that option it should assume it can make that ssh connection to the private ip and everything works as normal.

**Comment by casperdcl** [comment]
@dacbd the sentence is about [*on-premise/local* runners](https://cml.dev/doc/self-hosted-runners#on-premise-local-runners), i.e. you install CML and run `cml runner --token=... --repo=...` on each of your always-on machines, thereby circumventing TPI.
