### ISSUE TITLE
runner: Docker socket mounts

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#799]
Would be nice to auto-mount the Docker socket (in the GitLab runner in particular).
Might circumvent some Docker-in-Docker issues.

Alternatively:

- [x] expose `--docker-volumes` #861
- [ ] document `--docker-volumes` https://github.com/iterative/cml.dev/pull/189
- [x] add `docker_volumes` to TPI https://github.com/iterative/terraform-provider-iterative/pull/367

**Comment by casperdcl** [comment]
Could move https://github.com/iterative/terraform-provider-iterative/blob/ddf38b75c2eec4aed4935de6d6bc21eaf9251b19/iterative/resource_runner.go#L297-L299 to https://github.com/iterative/terraform-provider-iterative/blob/ddf38b75c2eec4aed4935de6d6bc21eaf9251b19/iterative/resource_runner.go#L325 to allow the user to do things like `export DOCKER_VOLUMES="/var/run/docker.sock:/var/run/docker.sock"`.

**Comment by 0x2b3bfa0** [comment]
> _Might circumvent some Docker-in-Docker issues._

And create many others.

**Comment by 0x2b3bfa0** [comment]
#861 seems like a nice compromise between usability and predictability. 👍🏼
