### ISSUE TITLE
option to enable CI/CD checks

### ISSUE THREAD

**Issue by RadionBik** [iterative/cml#800]
Hi!

I have a scheduled job for model re-training and integrated CML to simplify running a DVC pipeline and creating a PR within Github Actions. For example, once a week a job is triggered and in the end I see a new PR with model results. I would like to run some pre-configured checks for the newly created PR, however, they do not run as per [docs](https://cml.dev/doc/ref/pr). I thought that the checks are disabled for the first created with `cml pr` commit, but even a manual second commit does not trigger jobs. Is it because of CML? If so, can this behavior be toggle-able?

**Comment by dacbd** [comment]
I'm guessing that GitHub is parsing the commit message from this in order to not trigger CI:
https://github.com/iterative/cml/blob/68ddbe4bfa329e5a8b90caa3c7f9aa8a8acda109/src/cml.js#L383

If that is the case I don't see why there couldn't be an option to remove that from the commit message.

---------
In the meantime as a workaround, you could look into the `repository_dispatch` event.
Alternatively, I believe composite actions defined in "internal" repos are now accessible from other "internal" repos; you could define all of your checks in a composite action and reuse them where needed.

**Comment by DavidGOrtega** [comment]
@RadionBik as @dacbd states ```cml pr``` avoids the CI run to avoid infinite CI executions (one PR would generate another PR)

A solution might be trigger it with  
```yaml
on:
  issue_comment:
    types: [created]

jobs:
  pr-checks:
    if: includes(github.event.comment.body, '/pr-checks')
```

Then after generating the pr

```sh
echo '/pr-checks' > action.md
cml send-comment --commit-sha HEAD --pr action.md
```

**Comment by casperdcl** [comment]
also after running `cml pr` you could do

```bash
git commit --amend -m "$(git log -n1 --format=%B | sed 's/ \[skip ci\]//')"
git push --force
```

**Comment by RadionBik** [comment]
Thank you for the suggestions guys!

I do realize implications of avoding the `[skip ci]` within the commit message, but in my case this causes more inconvenience than I would expect. 

I have tried the solution by @DavidGOrtega but without success. I could have done something wrong, but nevertheless, this solution requires duplicating `pr-checks` code in `cml.yaml`.

The solution by @casperdcl looks like the easiest option, but I couldn't get the checks running even when pushing a second commit to the new branch. Here is the `cml.yaml` I have tested the solutions on:
```
name: scheduled model training

on:
  push:     # this must be removed when merging to master 
  schedule:
    - cron:  '0 15 * * *'

env:
  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  train:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Train the model
        working-directory: ./some_dir
        run: |
          touch params.yaml
          touch some.lock

      - name: Create branch
        run: |
          # selects dvc repro results to commit to a new branch
          cml pr "**/*.lock" "**/*.json"

      - name: Send report and launch CI checks
        working-directory: ./some_dir
        run: |
          git fetch origin
          # assumption: no commits can ever happen between `cml pr` and the executions below

          # CML by default commits results with [no ci] tag, so we need to run checks manually
          git commit --amend -m "$(git log -n1 --format=%B | sed 's/ \[skip ci\]//')"
          git push --force

          latest_commit_hash=$(git log -n1 --format=format:"%H")

          echo '### Training results >> ./report.md
          cml send-comment ./report.md --rm-watermark --commit-sha=${latest_commit_hash}

          # we are locating the latest branch on origin, removing the /origin and stripping whitespaces
          latest_branch=$(git branch -r --contains ${latest_commit_hash} | sed 's/origin\// /' | awk '{$1=$1};1')
          git checkout ${latest_branch}
          git add params.yaml && git commit -m "run CI tasks" && git push
``` 

I also have `pr.yaml` like this:
```
name: Pull requests

on:
  pull_request:
    branches:
    - "**"

env:
  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_and_lint:
    runs-on: ubuntu-18.04

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Execute
        run: echo "success!"
```

Here, I expect that pushing the second commit will trigger CI/CD checks, however, they are triggered only when a commit is pushed outside of the actions workflow, take a look at this screenshot 
![image](https://user-images.githubusercontent.com/19979628/140895257-3250859c-cc78-4644-95e0-492cbc4b040d.png)

What am I missing here?

P.S. I don't need to rename the commit message in order to trigger the checks when commiting manually.

**Comment by casperdcl** [comment]
@RadionBik your issue is due to using `secrets.GITHUB_TOKEN` rather than your own user/bot token. GitHub will never trigger CI from commits done by the `github-actions` (`secrets.GITHUB_TOKEN`) user. See https://cml.dev/doc/self-hosted-runners?tab=GitHub#personal-access-token

**Comment by RadionBik** [comment]
Hi! Thank you for pointing out this! 

The docs are clear on `personal access token` case, but I am struggling with linking newly created `GitHub APP` credentials (a private key `.pem` and `App ID`) with CML. 

Could you give a tip on how to use them?

**Comment by RadionBik** [comment]
BTW, I have replaced all the occurrences of GITHUB_TOKEN with a temporal PERSONAL_ACCESS_TOKEN I created for this test and still there are no actions running. Is there something else?

**Comment by casperdcl** [comment]
> The docs are clear on `personal access token` case, but I am struggling with linking newly created `GitHub APP` credentials (a private key `.pem` and `App ID`) with CML. We are trying to avoid access tokens, that's why I have gone the other way.

The documentation for GitHub Apps links to https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps which explains how to create a JSON Web Token equivalent.

> BTW, I have replaced all the occurrences of GITHUB_TOKEN with a temporal PERSONAL_ACCESS_TOKEN I created for this test and still there are no actions running. Is there something else?

Have you also made sure to have

```yaml
- uses: actions/checkout@v2
  with:
    token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
```

and also done `git config --global user.name "Some Name" && git config --global user.email <some@email.com>"` to make very sure the commit isn't associated with `github-actions`?

**Comment by casperdcl** [comment]
thanks @RadionBik - started a PR https://github.com/iterative/cml.dev/pull/145
