### ISSUE TITLE
runner's `--cloud-type` pseudonym's not behaving as expected.

### ISSUE THREAD

**Issue by dacbd** [iterative/cml#804]
Was doing some testing using `--cloud-type=m` on AWS and did not get a "m" / medium class instance but got a `c5.24xlarge` 😎 instead... I believe it ended up selecting the last instance type that was created or started on the account. I have seen this behavior a few times.

**Comment by 0x2b3bfa0** [comment]
As per the [provider], the `m` generic instance should be <code>m5.<b>2</b>xlarge</code> and not <code>m5.<b>24</b>xlarge</code>; I wonder if we're doing something wrong or it's just an AWS issue.

Are you running `cml runner --cloud` from an ephemeral CI/CD environment or locally?

[provider]: https://github.com/iterative/terraform-provider-iterative/blob/8121c664c4cc557059e44a332636d61a715c21dd/iterative/aws/provider.go#L406

**Comment by dacbd** [comment]
Hmm, I will double-check, that is the same family so maybe I read logs wrong. Anyway if I reproduce it again I will reopen the issue with more details but will close for now.

**Comment by 0x2b3bfa0** [comment]
> I will double-check, that is the same family so maybe I read logs wrong.

It would be amazing if it were just a layer–8 error. Still, it could be a bug somewhere; feel free to reopen this issue if you find it again.

**Comment by dacbd** [comment]
> layer-8

:joy:
