### ISSUE TITLE
`cml runner` early shutdown from idle-timeout with active job

### ISSUE THREAD

**Issue by dacbd** [iterative/cml#808]
Cloud provider: `gcp`
SCM / CICD: `github` / `actions`

I have been playing with short `--idle-timeout` values and I was a bit baffled when I encountered this. One workflow shutdown earlier before the GitHub action completes the final job, and the other completes as expected, but they are using nearly identical workflows.

Successful workflow:
```yml
name: Build and run Inference - DEV
on:
  push:
    branches: [dev]
jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/gcr-build-push@main
        with:
          tags: latest
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          GCR-key: ${{ secrets.GCP_GCR_KEY }}
          container-name: ***
  deploy-runner:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GCP_CML_RUNNER_KEY }}
        run: |
          cml-runner \
            --single \
            --idle-timeout=360 \
            --token=${{ secrets.PAT_DCB }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-standard-16
  run-inference:
    needs: [build, deploy-runner]
    runs-on: [self-hosted, cml]
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Setup Container image name
        run: echo "ML_CONTAINER=gcr.io/${{ secrets.GCP_PROJECT_ID }}/***" >> "${GITHUB_ENV}"
      - name: Docker GCR Login
        uses: docker/login-action@v1
        with: 
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_GCR_KEY }}
      - name: Load container from GCR
        run: docker pull ${{ env.ML_CONTAINER }}:latest
      - name: Run Inference
        run: |
          docker run ****
```
Failed workflow:
```yml
name: Build and run Inference - PROD
on:
  schedule: # Saturday at 1400 UTC
    - cron: '0 14 * * 6'
  push:
    branches: [prod]
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/gcr-build-push@v1
        with:
          tags: latest
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          GCR-key: ${{ secrets.GCP_GCR_KEY }}
          container-name: ***
  deploy-runner:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GCP_CML_RUNNER_KEY }}
        run: |
          cml-runner \
            --single \
            --idle-timeout=360 \
            --token=${{ secrets.PAT_DCB }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-standard-16
  run-inference:
    needs: [build, deploy-runner]
    runs-on: [self-hosted, cml]
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Setup Container image name
        run: echo "ML_CONTAINER=gcr.io/${{ secrets.GCP_PROJECT_ID }}/***" >> "${GITHUB_ENV}"
      - name: Docker GCR Login
        uses: docker/login-action@v1
        with: 
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_GCR_KEY }}
      - name: Load container from GCR
        run: docker pull ${{ env.ML_CONTAINER }}
      - name: Run Inference
        run: |
          docker run ***
```

-----------------------

Successful `cml.service` log
```
daniel_barnes@cml-z53bz3oz1t:~$ sudo journalctl -u cml.service -f
-- Logs begin at Tue 2021-11-09 20:03:04 UTC. --
Nov 09 20:05:47 cml-z53bz3oz1t systemd[1]: Started cml.service.
Nov 09 20:05:52 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"Preparing workdir /tmp/tmp.7PolL2jgVJ/.cml/cml-z53bz3oz1t..."}
Nov 09 20:05:52 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"Launching github runner"}
Nov 09 20:06:02 cml-z53bz3oz1t cml.sh[17039]: {"level":"warn","message":"SpotNotifier can not be started."}
Nov 09 20:06:03 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:06:03.618Z","level":"info","message":"runner status","repo":"https://github.com/yyyy/xxxx"}
Nov 09 20:06:03 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:06:03.619Z","level":"info","message":"runner status √ Connected to GitHub","repo":"https://github.com/yyyy/xxxx"}
Nov 09 20:06:04 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:06:04.057Z","level":"info","message":"runner status Listening for Jobs","repo":"https://github.com/yyyy/xxxx","status":"ready"}
Nov 09 20:06:16 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:06:15.944Z","job":4157205540,"level":"info","message":"runner status Running job: run-inference","repo":"https://github.com/yyyy/xxxx","status":"job_started"}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:18:21.355Z","job":"","level":"info","message":"runner status Job run-inference completed with result: Succeeded","repo":"https://github.com/yyyy/xxxx","status":"job_ended","success":true}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:18:21.595Z","level":"info","message":"runner status √ Removed .credentials","repo":"https://github.com/yyyy/xxxx"}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:18:21.596Z","level":"info","message":"runner status √ Removed .runner","repo":"https://github.com/yyyy/xxxx"}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"runner status","reason":"proc_exit","status":"terminated"}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"waiting 20 seconds before exiting..."}
Nov 09 20:18:41 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"Unregistering runner cml-z53bz3oz1t..."}
Nov 09 20:18:41 cml-z53bz3oz1t cml.sh[17039]: {"level":"error","message":"\tFailed: Cannot destructure property 'id' of '(intermediate value)' as it is undefined."}
Nov 09 20:18:44 cml-z53bz3oz1t systemd[1]: cml.service: Succeeded.
```

Failed `cml.service` log
```
daniel_barnes@cml-uawryesbyo:~$ sudo journalctl -u cml.service -f
-- Logs begin at Tue 2021-11-09 19:23:49 UTC. --
Nov 09 19:26:34 cml-uawryesbyo systemd[1]: Started cml.service.
Nov 09 19:26:39 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"Preparing workdir /tmp/tmp.TAz3gTOugR/.cml/cml-uawryesbyo..."}
Nov 09 19:26:39 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"Launching github runner"}
Nov 09 19:26:49 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"SpotNotifier can not be started."}
Nov 09 19:26:50 cml-uawryesbyo cml.sh[17135]: {"date":"2021-11-09T19:26:50.163Z","level":"info","message":"runner status","repo":"https://github.com/yyyy/xxxx"}
Nov 09 19:26:50 cml-uawryesbyo cml.sh[17135]: {"date":"2021-11-09T19:26:50.163Z","level":"info","message":"runner status √ Connected to GitHub","repo":"https://github.com/yyyy/xxxx"}
Nov 09 19:26:50 cml-uawryesbyo cml.sh[17135]: {"date":"2021-11-09T19:26:50.583Z","level":"info","message":"runner status Listening for Jobs","repo":"https://github.com/yyyy/xxxx","status":"ready"}
Nov 09 19:27:02 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"Failed parsing log: Reduce of empty array with no initial value"}
Nov 09 19:27:02 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"Original log bytes, as Base64: 2021-11-09 19:27:01Z: Running job: run-inference\n"}
Nov 09 19:32:51 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"runner status","reason":"timeout:360","status":"terminated"}
Nov 09 19:32:51 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"waiting 20 seconds before exiting..."}
Nov 09 19:33:11 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"Unregistering runner cml-uawryesbyo..."}
Nov 09 19:33:12 cml-uawryesbyo cml.sh[17135]: {"level":"error","message":"\tFailed: Bad request - Runner \"cml-uawryesbyo\" is still running a job\""}
Nov 09 19:33:22 cml-uawryesbyo systemd[1]: cml.service: Succeeded.
```

**Comment by dacbd** [comment]
I have run these workflows several times and they consistently pass/fail in the exact same way.

The line: 
`Nov 09 19:27:02 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"Failed parsing log: Reduce of empty array with no initial value"}`
Is the only thing that jumps out at me, 
@DavidGOrtega @0x2b3bfa0 are there any logs that I might be able to grab that would shed some more light here?

**Comment by casperdcl** [comment]
Perhaps due to both being `--single` yet using the same label/name?

**Comment by dacbd** [comment]
They are running in separate GCP projects so name collision should not be an issue, I'm going to add a separate label for the runners as I can see that happening.

In this case though while they could start at the same time when I was testing/re-running them they were not happening concurrently. I will try a few more things out single/naming/labels and we can see if that solves it.

The failed logs show that the CML service ran a job but still killed itself for a timeout.

**Comment by dacbd** [comment]
It looks like this condition failed to trigger:
https://github.com/iterative/cml/blob/c872c328550eaf581bdbd69023d19675c5306a3e/src/cml.js#L223

and I got the try clause:
https://github.com/iterative/cml/blob/c872c328550eaf581bdbd69023d19675c5306a3e/src/cml.js#L261-L264

seen above as:
```
Nov 09 19:27:02 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"Failed parsing log: Reduce of empty array with no initial value"}
Nov 09 19:27:02 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"Original log bytes, as Base64: 2021-11-09 19:27:01Z: Running job: run-inference\n"}
```

oldly that doesn't look like base64 to me and looks like it should have matched the condition 🤔

**Comment by dacbd** [comment]
Well seeing this in both workflows now, I'm going to increase the idle-timeout value to bypass this issue since the runtime isn't that long, but I've saved the state in a project branch to revisit this. I'm convinced this is from the failed log parsing error that I have outlined above.

**Comment by dacbd** [comment]
I have re-tabled looking into this until I can do https://github.com/iterative/terraform-provider-iterative/pull/255 ; open to better debugging options/ideas. I am still able to consistently reproduce this error.

**Comment by dacbd** [comment]
I double-checked that I could still reproduce this error and it seems to be resolved. 

I last tested (which failed) on `Nov 22, 2021`

@DavidGOrtega / @casperdcl feel free to re-open but it looks like I might have been the only one to have during the time this has been open.

**Comment by dacbd** [comment]
I had this reoccur.

**Comment by mikolajpabiszczak** [comment]
> @mikolajpabiszczak timeout parsing mismatch seems like a different issue: #875.
> 
> However despite the mismatch the runner should not shut down while busy. Given:
> 
> * transient issue with GH + GCP
> * transient issue with GH + AWS
> * error messages all clearly stating "The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled"

The GH issues were solved some time ago (at least judging by the reports). Let me just say that the problem I described is not incidental - it is constant, it persists from quite some time (~2 weeks, since when I started playing with CML at bigger scale) and I did not manage to have a single run without passing some high `--idle-timeout` value.

> 
> I can only surmise that GH itself has cancelled the job. This could be due to:
> 
> * someone cancelling the job via the GH interface

not the case

> * some GH API call to cancel the job

not triggered by me for sure

> * transient networking issues stopping GH from talking to the instance quick enough, thus making GH cancel the job

I believe that it is not the case, as both the logs are appearing and the runner is shown as connected/working on the GitHub self hosted runners page.

**Comment by dacbd** [comment]
I don't believe this to be true, if you look at the cml.service logs I
provided you can see a parsing error where it would normally detect that
the actions runner has received a job.

**Comment by dacbd** [comment]
@mikolajpabiszczak can you capture your cml.service logs from the instance to see if you get the same error you can see in mine from the above?

**Comment by casperdcl** [comment]
> you can see a parsing error where it would normally detect that the actions runner has received a job

That's just a warning (not an error, i.e. it shouldn't cause a termination) AFAIK /CC @DavidGOrtega @0x2b3bfa0 (incidentally, #876).

**Comment by dacbd** [comment]
It doesn't cause the termination itself but it never enters the "has job"
state from the cml perspective and so it's still counting down it's timeout
timer.

**Comment by casperdcl** [comment]
aha yes. Well the regex and the plain-text output look fine to me so with #876 perhaps could get to the bottom of this?

**Comment by casperdcl** [comment]
@mikolajpabiszczak what were the log lines *after* the ones you'd posted?

```
{"level":"info","message":"Terraform apply..."}
{"level":"info","message":"{\"awsSecurityGroup\":null,\"awsSubnetId\":null,\"cloud\":\"aws\",\"driver\":\"github\",\"id\":\"iterative-gz890wjbruo9\",\"idleTimeout\":300,\"image\":\"iterative-
```

**Comment by mikolajpabiszczak** [comment]
> @mikolajpabiszczak can you capture your cml.service logs from the instance to see if you get the same error you can see in mine from the above?

Will come back with this bit later.

> @mikolajpabiszczak what were the log lines after the ones you'd posted?

What follows is the end  of the raw log for `deploy-runner` action.

```
2022-01-20T10:30:52.0025949Z '43143f89dc9af728a7c89f09066ebb13f68d14ea'
2022-01-20T10:30:52.0217021Z ##[group]Run cml runner \
2022-01-20T10:30:52.0217824Z [36;1mcml runner \[0m
2022-01-20T10:30:52.0218291Z [36;1m    --cloud=aws \[0m
2022-01-20T10:30:52.0218790Z [36;1m    --cloud-region=eu-west-1 \[0m
2022-01-20T10:30:52.0219404Z [36;1m    --cloud-type=g5.2xlarge \[0m
2022-01-20T10:30:52.0219911Z [36;1m    --cloud-spot \[0m
2022-01-20T10:30:52.0220398Z [36;1m    --idle-timeout=-1 \[0m
2022-01-20T10:30:52.0220911Z [36;1m    --labels=training-fold[0m
2022-01-20T10:30:52.0278602Z shell: /usr/bin/bash -e {0}
2022-01-20T10:30:52.0279066Z env:
2022-01-20T10:30:52.0279706Z   AWS_ACCESS_KEY_ID: ***
2022-01-20T10:30:52.0280293Z   AWS_SECRET_ACCESS_KEY: ***
2022-01-20T10:30:52.0280923Z   REPO_TOKEN: ***
2022-01-20T10:30:52.0281364Z ##[endgroup]
2022-01-20T10:30:52.6846750Z {"level":"warn","message":"ignoring RUNNER_NAME environment variable, use CML_RUNNER_NAME or --name instead"}
2022-01-20T10:30:55.9902861Z {"level":"info","message":"Preparing workdir /home/runner/.cml/cml-wrczclxokb..."}
2022-01-20T10:30:55.9911256Z {"level":"info","message":"Deploying cloud runner plan..."}
2022-01-20T10:30:55.9912957Z {"level":"info","message":"Terraform apply..."}
2022-01-20T10:32:13.9705684Z {"level":"info","message":"{\"awsSecurityGroup\":null,\"awsSubnetId\":null,\"cloud\":\"aws\",\"driver\":\"github\",\"id\":\"iterative-gz890wjbruo9\",\"idleTimeout\":300,\"image\":\"iterative-cml\",\"instanceGpu\":null,\"instanceHddSize\":35,\"instanceIp\":\"18.203.69.174\",\"instanceLaunchTime\":\"2022-01-20T10:31:04Z\",\"instanceType\":\"g5.2xlarge\",\"instancePermissionSet\":null,\"labels\":\"training-fold\",\"metadata\":null,\"name\":\"cml-wrczclxokb\",\"region\":\"eu-west-1\",\"repo\":\"https://github.com/medsensio/abnormal-lung-sounds\",\"single\":false,\"spot\":true,\"spotPrice\":-1,\"timeouts\":null}"}
2022-01-20T10:32:13.9848301Z Post job cleanup.
2022-01-20T10:32:14.1102631Z [command]/usr/bin/git version
2022-01-20T10:32:14.1149812Z git version 2.34.1
2022-01-20T10:32:14.1187063Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-01-20T10:32:14.1228443Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-01-20T10:32:14.1462802Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-01-20T10:32:14.1490828Z http.https://github.com/.extraheader
2022-01-20T10:32:14.1500351Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-01-20T10:32:14.1538014Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-01-20T10:32:14.1932439Z Cleaning up orphan processes
```

**Comment by casperdcl** [comment]
@mikolajpabiszczak @dacbd: we just released [v0.11.0](https://github.com/iterative/cml/releases/tag/v0.11.0) with `--idle-timeout=-1` fixed + some minor logging updates so this should help.

Please do post the `sudo journalctl -u cml.service -f` output if the error still occurs.

**Comment by mikolajpabiszczak** [comment]
Hi, just writing to confirm that `--idle-timeout=-1` option works now. As for the issue described in the topic of this PR: it still occurs.

**Comment by dacbd** [comment]
@mikolajpabiszczak were you able to grab logs from journalctl? I can't get this error to consistently happen.

**Comment by mikolajpabiszczak** [comment]
Here you go (this is for the default `--idle-timout` of 300s):

```
2022-02-08T09:13:52.3568485Z ##[group]Run journalctl -u cml.service -f
2022-02-08T09:13:52.3569007Z [36;1mjournalctl -u cml.service -f[0m
2022-02-08T09:13:52.3613363Z shell: /bin/bash -e {0}
2022-02-08T09:13:52.3613758Z ##[endgroup]
2022-02-08T09:13:52.4429327Z -- Logs begin at Thu 2021-09-30 13:32:55 UTC. --
2022-02-08T09:13:52.4429921Z Feb 08 09:13:05 ip-172-31-44-49 systemd[1]: Started cml.service.
2022-02-08T09:13:52.4430656Z Feb 08 09:13:22 ip-172-31-44-49 cml.sh[2936]: {"level":"info","message":"Preparing workdir /tmp/tmp.o5uijqZHRi/.cml/cml-dswuaz80qg..."}
2022-02-08T09:13:52.4431726Z Feb 08 09:13:22 ip-172-31-44-49 cml.sh[2936]: {"level":"info","message":"Launching github runner"}
2022-02-08T09:13:52.4432494Z Feb 08 09:13:38 ip-172-31-44-49 cml.sh[2936]: {"level":"info","message":"EC2 id i-0969574de3d030438"}
2022-02-08T09:13:52.4433409Z Feb 08 09:13:39 ip-172-31-44-49 cml.sh[2936]: {"date":"2022-02-08T09:13:39.068Z","level":"info","message":"runner status","repo":"https://github.com/yyyy/xxxx"}
2022-02-08T09:13:52.4435068Z Feb 08 09:13:39 ip-172-31-44-49 cml.sh[2936]: {"date":"2022-02-08T09:13:39.069Z","level":"info","message":"runner status √ Connected to GitHub","repo":"https://github.com/yyyy/xxxx"}
2022-02-08T09:13:52.4436180Z Feb 08 09:13:39 ip-172-31-44-49 cml.sh[2936]: {"date":"2022-02-08T09:13:39.711Z","level":"info","message":"runner status Current runner version: '2.287.1'","repo":"https://github.com/yyyy/xxxx"}
2022-02-08T09:13:52.4437304Z Feb 08 09:13:39 ip-172-31-44-49 cml.sh[2936]: {"date":"2022-02-08T09:13:39.712Z","level":"info","message":"runner status Listening for Jobs","repo":"https://github.com/yyyy/xxxx","status":"ready"}
2022-02-08T09:13:52.4438094Z Feb 08 09:13:49 ip-172-31-44-49 cml.sh[2936]: {"level":"warn","message":"Failed parsing log: Resource not accessible by integration"}
2022-02-08T09:13:52.4438987Z Feb 08 09:13:49 ip-172-31-44-49 cml.sh[2936]: {"level":"warn","message":"Original log bytes, as Base64: MjAyMi0wMi0wOCAwOToxMzo0OVo6IFJ1bm5pbmcgam9iOiBkZWJ1Zy1hd3MK"}
2022-02-08T09:18:40.6884562Z Feb 08 09:18:40 ip-172-31-44-49 cml.sh[2936]: {"level":"info","message":"runner status","reason":"timeout:300","status":"terminated"}
2022-02-08T09:18:40.6888344Z Feb 08 09:18:40 ip-172-31-44-49 cml.sh[2936]: {"level":"info","message":"waiting 20 seconds before exiting..."}
2022-02-08T09:19:00.6882927Z Feb 08 09:19:00 ip-172-31-44-49 cml.sh[2936]: {"level":"info","message":"Unregistering runner cml-dswuaz80qg..."}
2022-02-08T09:19:01.4383771Z Feb 08 09:19:00 ip-172-31-44-49 cml.sh[2936]: {"level":"error","message":"\tFailed: Bad request - Runner \"cml-dswuaz80qg\" is still running a job\""}
2022-02-08T09:19:02.4762716Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2022-02-08T09:19:02.4965478Z ##[error]The operation was canceled.
2022-02-08T09:19:02.5136466Z Cleaning up orphan processes
```

[note: I anonymised the GitHub repo address]

**Comment by DavidGOrtega** [comment]
These logs are very insightful for me. Thanks!

**Comment by DavidGOrtega** [comment]
@mikolajpabiszczak what is happening in you case is that the runner is never telling us that a job has been started. Indeed the error is very interesting

```
Resource not accessible by integration
```
Then we do not have any status of starting a job nor finishing it so the timeout by idle

**Comment by mikolajpabiszczak** [comment]
Ahhh, I think that it's my bad now - I believe I found the reason for that: lack of proper permissions to self-hosted runners in `organisation` chapter. Should be ok now. Sorry for the mess!

**Comment by dacbd** [comment]
@DavidGOrtega 

> ```
> Resource not accessible by integration
> ```

where did you see this log?

**Comment by mikolajpabiszczak** [comment]
> 
> @mikolajpabiszczak in this thread? I must be blind 👓

Yes, this comment: https://github.com/iterative/cml/issues/808#issuecomment-1032390230

**Comment by 0x2b3bfa0** [comment]
> [_2022-02-08T09:13:52.4438094Z Feb 08 09:13:49 ip-172-31-44-49 cml.sh[2936]: {"level":"warn","message":"Failed parsing log: Resource not accessible by integration"}_](https://github.com/iterative/cml/issues/808#issuecomment-1032390230)

**Comment by dacbd** [comment]
I haven't been able to get this error again, but in my past logs I have not had that line, and the PAT has had the same permissions.

however, in both cases, they were prefaced with a log parsing failure.
```
Nov 09 19:27:02 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"Failed parsing log: Reduce of empty array with no initial value"}
```
for the one that I was able to capture.

**Comment by mikolajpabiszczak** [comment]
> Ahhh, I think that it's my bad now - I believe I found the reason for that: lack of proper permissions to self-hosted runners in `organisation` chapter. Should be ok now. Sorry for the mess!

Well... I was too fast to report solution. Even though the permissions were updated, the problem still occurs. 😩

**Comment by DavidGOrtega** [comment]
Can you  please share the workflow? Also what time do you expect it to be running?

**Comment by dacbd** [comment]
I think what @DavidGOrtega is working on is a defensive check to the GitHub API to verify that the runner is "idle".
It seems there isn't any single thing that causes the error to occur (from what I've seen). And the log parsing errors that seem to prefix the shutdown are strings that shouldn't be erroring out ? ... 🤔

**Comment by DavidGOrtega** [comment]
> And the log parsing errors that seem to prefix the shutdown are strings that shouldn't be erroring out ?

Correct. I have set tests to check that the parsing is happening as it should. My best guess is that the GH runner has some kind of hicups with the stdout

**Comment by DavidGOrtega** [comment]
Im also simplifying the whole architecture taking into account just the pure the exit of the native runner

**Comment by DavidGOrtega** [comment]
@dacbd @mikolajpabiszczak 
for the record

 - https://github.com/actions/runner/issues/1263
 - https://github.com/actions/runner/issues/921
 - https://github.com/actions/runner/issues/700

**Comment by dacbd** [comment]
The Phantom job canceler has struck again! going to see if I can get it to happen again get more logs.
![image](https://user-images.githubusercontent.com/1105843/156220327-82a2944c-e5bd-40e3-99d2-1879a6b4e009.png)

**Comment by 0x2b3bfa0** [comment]
> _The Phantom job canceler has struck again! going to see if I can get it to happen again get more logs._

Note: a year ago, I had exactly this issue when using a small instance type and exhausting the resources with a heavy process.
