### ISSUE TITLE
Windows version docker

### ISSUE THREAD

**Issue by hongjiedai** [iterative/cml#810]
I am trying to use CML on my windows system and observe that the released image cannot run on the windows platform.
Is there a docker image for windows?

Thank you

**Comment by DavidGOrtega** [comment]
👋  We have our [linux docker images](https://github.com/iterative/cml#docker-images) for you to be used on Windows.

**Comment by 0x2b3bfa0** [comment]
@hongjiedai, feel free to close this issue if the reply above solved your question.
