### ISSUE TITLE
`cml pr`: Merging the P.R. with `Create a merge commit` option ignores `skip c.i.`

### ISSUE THREAD

**Issue by daavoo** [iterative/cml#815]
When merging a P.R. created by `cml pr`, if the option `Create a merge commit` is selected from the GitHub interface a new commit is added. 

This triggers the C.I. on the base branch, ignoring the `skip c.i.` in the CML commit message.

**Comment by daavoo** [comment]
Example here: https://github.com/iterative/test-cml-send-comment-pr/pull/5

**Comment by casperdcl** [comment]
You will have to manually write `[skip c.i.]` in the merge commit message.

1. there's no other clean work-around (e.g. could define a workflow which doesn't run on *any* merges/pushes to `master`)
2. this is both expected and desirable behaviour in most workflows

Could document work-arounds for cases where (2) doesn't apply...

**Comment by 0x2b3bfa0** [comment]
Specially relevant for GitLab; see [gitlab-org/gitlab#232602](https://gitlab.com/gitlab-org/gitlab/-/issues/232602) and [this message on our Discord server](https://discord.com/channels/485586884165107732/728693131557732403/918262802219696180).

**Comment by 0x2b3bfa0** [comment]
Should we include `[skip-ci]` in the pull/merge request title?

**Comment by daavoo** [comment]
> Should we include `[skip-ci]` in the pull/merge request title?

Or #792 + example in docs for this case 👼

**Comment by casperdcl** [comment]
Fixed by #1035 I think. Some follow-up issues are #1017 & #1056.
