### ISSUE TITLE
The ability to keep a cloud instance alive

### ISSUE THREAD

**Issue by TrungKhoaLe** [iterative/cml#819]
Dear owners,

Thanks for the effort to create a great tool!
I have a question related to a possibility that is *are we able to keep cloud instances alive?*. At the moment, I observe that the created instances will be destroyed after a certain period of time.

**Comment by dacbd** [comment]
I have thought of this before, depending on what you are trying to do you have options you can use in the interim if this idea gets traction to be implemented.

- Have a dummy step that is basically a sleep to hold the door open for you to connect and do whatever inspection you want.
- You can have a final snapshot step that you can clone and later mount onto another VM for more inspection.

What is your use case?

**Comment by casperdcl** [comment]
Cloud instances can be kept alive. The relevant runner options (https://cml.dev/doc/ref/runner#options) are `--idle-timeout=-1` and perhaps `--reuse`. Also make sure *not* to use `--cloud-spot` or `--single`.

**Comment by DavidGOrtega** [comment]
As @casperdcl greatly said do not use spot instances (`--cloud-spot`) because they are going to get disposed by the cloud.
`--single` means that it will only execute one task and leave.

**Comment by DavidGOrtega** [comment]
Hopefully this is resolved. @TrungKhoaLe please feel free to reopen it if further clarification needs to be done
