### ISSUE TITLE
CML binaries to improve the node dep

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#825]
We are actually needing the host to have node at a specific version to be able to use CML, this problem can be alleviated generating CML executables.

**Comment by 0x2b3bfa0** [comment]
See also https://www.npmjs.com/package/pkg

**Comment by DavidGOrtega** [comment]
> See also https://www.npmjs.com/package/pkg

Thats the one I like the most. I use it in the Adobe extensions
