### ISSUE TITLE
cml `rerun-workflow` command

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#827]
It needs to retry the workflow given any:
 - workflowId
 - jobId

**Comment by 0x2b3bfa0** [comment]
Maybe `cml workflow run` or `cml workflow restart` following [`gh workflow run`](https://cli.github.com/manual/gh_workflow_run) name? Just a #762 nitpick.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 I feel the same, however it goes against our `send-comment` nomenclature `action-entity`

**Comment by casperdcl** [comment]
:+1: `workflow rerun` à la [gh run rerun](https://cli.github.com/manual/gh_run_rerun) think we're all agreed.

No need to be consistent with old commands that are going to be renamed as part of #762 anyway.
