### ISSUE TITLE
cml.py

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#828]
A python library that wraps CML to be used in Python env and DVCLive

**Comment by casperdcl** [comment]
would depend on #825 (so could release a Python package dependent on binaries similar to https://github.com/iterative/tpi)

**Comment by DavidGOrtega** [comment]
Started at https://github.com/iterative/pycml

**Comment by casperdcl** [comment]
Haven't decided it's a good idea (yet)?

**Comment by dacbd** [comment]
🤖
