### ISSUE TITLE
EPIC: TPI `task` <->  CI

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#830]
## Tasks within the CI

The purpose of this EPIC is introduce the usage of the new `iterative_task` within the CI with a new paradigm that:

1. Creates a task within the CI Job and leaves. The goal and responsibility of the job is just to create a `task` and its success is just merely based on the completion of such `task` creation.
2. That job is meant to be rerun in order to be able to sync the task to: 
    - check the task status and if done  at least destroy the task. 
    - Sync data back to be able to do cml pr or send-comment reports
3. We update the task status by checks api and we can also use `cml send-comment` within the training script to provide "live" metrics

### Benefits over conventional runners
 -  Using tasks we allow the user to not even having to sync intermediate data (sagemaker)
 - We avoid runner timeouts and runners net failures
 - We can do parallel experiments declaring them as tasks within a loop with HCL
 - We decouple more from the specific CI 

### Phase1:

- [x] #820
- [x] #827
- [x] #825 

### Phase2:
- [x] #828
- [ ] #824
- [x] #829
- [x] https://github.com/iterative/terraform-provider-iterative/issues/324

**Comment by dacbd** [comment]
basically done.
