### ISSUE TITLE
remove mmmagic as a dependency?

### ISSUE THREAD

**Issue by dacbd** [iterative/cml#836]
I was looking at: https://github.com/iterative/setup-cml/issues/53

How much work would it be to eliminate as a dependency? It seems to be only used in one place, I'm not familiar with this chunk: https://github.com/iterative/cml/blob/cf7bfd039bc366d781ee897f774ca394f21e3f39/src/utils.js#L27-L47

and if IIRC is the only complied cml dependency?

**Comment by dacbd** [comment]
This would only be a change of convenience.

**Comment by 0x2b3bfa0** [comment]
Duplicate of #544?

**Comment by 0x2b3bfa0** [comment]
I wonder if we _really_ need a MIME type library on the client side.

**Comment by dacbd** [comment]
I haven't seen where this utils function is being used but I'm just guessing this for publish or send-comment to make sure its a filetype that plays nice with github/gitlab comments / mardown embedding etc?

If that's the case how much protection of the user using the tool incorrectly do you really need to do?

**Comment by casperdcl** [comment]
closing as duplicate of #544
