### ISSUE TITLE
expose USER to whom CML reports belong

### ISSUE THREAD

**Issue by gennaro-tedesco** [iterative/cml#841]
I noticed that when CML produces the reports (as per in `cml-send-comment --update --pr report.md`) such reports are shown in the PR conversation as belonging to a certain user rather than GitHub actions reports. Is this intended behaviour or is there a setting/flag where we can choose which user to assign to the comments reports?

I haven't figured out how such user is chosen, I suspect it is the user that appears in the latest git blame for cml.yaml but I am not sure (however it may cause confusion to have reports assigned to users when there are other comments on the PR).

From a conversation with David Ortega:

>>> It's actually set with two variables that we should probably expose.
const GIT_USER_NAME = 'Olivaw[bot]';
const GIT_USER_EMAIL = 'olivaw@iterative.ai';

would it be possible to have more transparency on how to assign them?

**Comment by gennaro-tedesco** [comment]
Addendum: could it be that the user that appears in the report is the one who created the `GITHUB_PAT` as per 
```
env:
    REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 ```
? Such `PAT` is allowed at organisation level but nevertheless it is still a "personal access token", so it may be the personal access of the user who created it?

**Comment by DavidGOrtega** [comment]
> Addendum: could it be that the user that appears in the report is the one who created the GITHUB_PAT

We could gather in some CIs the commiter identity but unfortunately not the token's owner. The feature that you comment has been bugging me in the past.

**Comment by exotikh3** [comment]
I would like to try myself working on this issue

**Comment by casperdcl** [comment]
aren't comments attributed to the PAT user? The only way they could be attributed to a different user is to use that user's token, right?
