### ISSUE TITLE
Cannot find module 'pseudoexec'

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#843]
Tests are not passing. When executing

```
npm install -g
```

we have `Cannot find module 'pseudoexec'`

**Comment by DavidGOrtega** [comment]
Can not be reproduced locally

**Comment by casperdcl** [comment]
Assigned @0x2b3bfa0 just in case it's something that needs fixing at https://github.com/0x2b3bfa0/node-pseudoexec :)

**Comment by casperdcl** [comment]
PR where this was discovered: #842

**Comment by DavidGOrtega** [comment]
Its happening everywhere

**Comment by 0x2b3bfa0** [comment]
Apparently, it happens because the global install is just a symbolic link to the GitHub Actions workspace directory.

```console
$ ls -l /usr/local/bin/../lib/node_modules/@dvcorg/cml
lrwxrwxrwx 1 runner docker 39 Dec 14 17:03 /usr/local/bin/../lib/node_modules/@dvcorg/cml -> ../../../../../home/runner/work/cml/cml
```

Running `npm install --global && npm install` solves the issue by also downloading dependencies to the local `node_modules` but it's just a workaround, not a fix.

**Comment by 0x2b3bfa0** [comment]
I wonder if somebody at `npm` mistakenly turned `npm install` into `npm link` 🤔

**Comment by 0x2b3bfa0** [comment]
It looks like `npm install --global` is just linking the package, and does not install any dependencies from `package.json` 🤔

**Comment by 0x2b3bfa0** [comment]
Noting is inherently wrong with the `pseudoexec` module apart from being the first import in the file, by the way.

**Comment by casperdcl** [comment]
eek... [npm/cli/issues?q=symlinks](https://github.com/npm/cli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+symlinks)
