### ISSUE TITLE
CML workflow create (and UI)

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#854]
- a new command, and/or
- a web UI

to help users:

- create CI config files (`.github/workflows/cml.yml`, `.gitlab-ci.yml`, etc...)
- select CML config options (with or without runner, [machine type], etc.)

![Captura de pantalla 2021-10-05 a las 22 50 50](https://user-images.githubusercontent.com/11387611/136100690-f233b87a-b3df-4715-8484-de049d8eae6c.png)

-- image from @0x2b3bfa0 in the [machine type] comment above

[machine type]: https://github.com/iterative/terraform-provider-iterative/issues/158#issuecomment-934826522

**Comment by dacbd** [comment]
the direction was changed and this feature was created in studio.
