### ISSUE TITLE
CML image problem with OpenSSL certs when using DVC

### ISSUE THREAD

**Issue by sergeychuvakin** [iterative/cml#855]
Hi CML team! 
 
 I'm using the following CML image: docker://dvcorg/cml:0-dvc2-base0-gpu (with --gpus all)
 
 About a week ago, I started noticing that DVC cannot properly run the command `dvc metrics show` I got the error below:
 ERROR: unexpected error - OpenSSL error: failed to load certificates: error:00000000:lib(0):func(0):reason(0)
 
Then I run verbose mode` dvc metrics show -v` and I got the following output: it's huge sorry - 1.txt attached.

`dvc doctor` attached as well - 2.txt. 

I saw in the logs pygit error, so I decided to try the following:
1) set env varaible GIT_SSL_NO_VERIFY: true
2) git config http.sslVerify "false"

None of these options works. 

DVC team suggested the following thoughts:
1) do you have the ca-certificates package installed in your EC2 instance (from apt)
2) it looks like the issue is that python's ssl (openssl) cant load any default ca certs, which is why I was wondering if ca-certificates was not being installed in that image

Then, I was recommended to remove 

```yaml
  - uses: actions/setup-python@v2
    with:
      python-version: "3.9"
```
I did it, but it didn't help. 

Finally,  I re-installed DVC like this:
```bash
sudo apt remove dvc
pip install 'dvc[s3]==2.3.0'
```
And now it works.

**Comment by sergeychuvakin** [comment]
Related to https://github.com/iterative/dvc/issues/7207

**Comment by casperdcl** [comment]
Could pin to an earlier (working) `*.deb` from https://github.com/iterative/dvc/releases for now while https://github.com/iterative/dvc/issues/7207 is still open?
