### ISSUE TITLE
Get started tutorial error

### ISSUE THREAD

**Issue by gosiqueira** [iterative/cml#867]
The code in get started tutorial states the following:

```yaml
cml publish confusion_matrix.png --md >> report.md
```

however the `train.py` generates a `plot.png` file, which breaks the action workflow.

**Comment by DavidGOrtega** [comment]
@gosiqueira could you please point me which tutorial are your following?

**Comment by gosiqueira** [comment]
@DavidGOrtega I was following the getting started tutorial: https://github.com/iterative/cml#getting-started
Item 2 presents the snippet with the error aforementioned

**Comment by casperdcl** [comment]
thanks; fixed!
