### ISSUE TITLE
runner: --idle-timeout not passed to terraform

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#877]
```
cml runner --idle-timeout=-1 ...
info: Terraform apply...
info: {..., "idleTimeout":300, ...}
```

happens on e.g. `--cloud=gcp` and `--cloud=aws` but does *not* happen on-prem (local) where terraform isn't used

**Comment by DavidGOrtega** [comment]
I remember this hitting me testing a few weeks ago, however I finally determined it was correct... or almost. Happens that `-1` is not accepted in cloud instances

```
${
    typeof idleTimeout !== 'undefined' && idleTimeout >= 0
      ? `idle_timeout = ${idleTimeout}`
      : ''
  }
```

Where you trying -1 @casperdcl ?

**Comment by casperdcl** [comment]
Not sure I follow the question. `cml runner --idle-timeout=-1 --cloud=aws` results in `idle_timeout = 300` being passed to terraform.

`bin/cml/runner.js::runLocal` is fine.

`bin/cml/runner.js::runCloud` has a bug.

**Comment by 0x2b3bfa0** [comment]
_Nota bene:_ `-1` is accepted everywhere since https://github.com/iterative/cml/pull/700
