### ISSUE TITLE
`cml runner --cloud-ssh-private` not working because of a `yargs` parsing issue

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#889]
* https://github.com/yargs/yargs/issues/2128

**Comment by dacbd** [comment]
Probably the original source of the issue that led to #852

**Comment by casperdcl** [comment]
shouldn't we close this as a duplicate of #852?

**Comment by dacbd** [comment]
I think #852 should be revisited after this. Or close this and track the
upstream issue from 852?

**Comment by 0x2b3bfa0** [comment]
Closing in favor of #852 🙈
