### ISSUE TITLE
`cml-runner` shut down due to idle timeout while still busy. 

### ISSUE THREAD

**Issue by thatGreekGuy96** [iterative/cml#923]
Hey everyone, started getting this error a couple of weeks ago, where jobs on GHA are failing with `143` error codes. Did a little digging and it seems like the error is because of the `--idle-timeout` parameter, which is by default set to `300`. 
Seems like the job _thinks_ it's idle and gets shut down, but in fact it is actually still running! 
Not sure why this is happening, setting `--idle-timeout=-1` resolves the issue, but I don't want to do that for obvious reasons. 

I'm using cml version `0.12.0` (which addressed a similar issue from what I can see? -> https://github.com/iterative/cml/issues/808 ). 

Here are the logs from the runners: 
```
root@ip-172-31-43-163:~# sudo journalctl -u cml.service -f
-- Logs begin at Tue 2022-02-22 16:02:55 UTC. --
Mar 24 17:10:29 ip-172-31-43-163 cml.sh[1869]: sshd override added, restarting daemon
Mar 24 17:10:30 ip-172-31-43-163 sudo[2799]: pam_unix(sudo:session): session closed for user root
Mar 24 17:10:37 ip-172-31-43-163 cml.sh[1869]: {"level":"info","message":"Preparing workdir /tmp/tmp.NZ4U6HZb1S/.cml/cml-wdw16iotk7..."}
Mar 24 17:10:37 ip-172-31-43-163 cml.sh[1869]: {"level":"info","message":"Launching github runner"}
Mar 24 17:10:50 ip-172-31-43-163 cml.sh[1869]: {"level":"info","message":"EC2 id i-0c767456d3e8c3eec"}
Mar 24 17:10:50 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:10:50.327Z","level":"info","message":"runner status","repo":"https://github.com/continuum-industries/Pareto"}
Mar 24 17:10:50 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:10:50.328Z","level":"info","message":"runner status √ Connected to GitHub","repo":"https://github.com/continuum-industries/Pareto"}
Mar 24 17:10:50 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:10:50.910Z","level":"info","message":"runner status Current runner version: '2.289.1'","repo":"https://github.com/continuum-industries/Pareto"}
Mar 24 17:10:50 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:10:50.911Z","level":"info","message":"runner status Listening for Jobs","repo":"https://github.com/continuum-industries/Pareto","status":"ready"}
Mar 24 17:11:18 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:11:18.401Z","job":"gh","level":"info","message":"runner status Running job: Run Optimisations (BASELINE_GREENLINK_ME_CASE_04, 0)","repo":"https://github.com/continuum-industries/Pareto","status":"job_started"}
Mar 24 17:15:50 ip-172-31-43-163 cml.sh[1869]: {"level":"error","message":"Runner should be idle. Resetting jobs. Retrying in 300 secs"}
Mar 24 17:16:40 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:16:40.360Z","job":"gh","level":"info","message":"runner status Job Run Optimisations (BASELINE_GREENLINK_ME_CASE_04, 0) completed with result: Succeeded","repo":"https://github.com/continuum-industries/Pareto","status":"job_ended","success":true}
Mar 24 17:16:42 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:16:42.954Z","job":"gh","level":"info","message":"runner status Running job: Run Optimisations (OFFSHORE_PIPELINE, 0)","repo":"https://github.com/continuum-industries/Pareto","status":"job_started"}
Mar 24 17:20:51 ip-172-31-43-163 cml.sh[1869]: {"level":"error","message":"Runner should be idle. Resetting jobs. Retrying in 300 secs"}
Mar 24 17:21:09 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:21:09.794Z","job":"gh","level":"info","message":"runner status Job Run Optimisations (OFFSHORE_PIPELINE, 0) completed with result: Succeeded","repo":"https://github.com/continuum-industries/Pareto","status":"job_ended","success":true}
Mar 24 17:21:15 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:21:15.077Z","job":"gh","level":"info","message":"runner status Running job: Run Optimisations (REAL_PIPELINE_MOATA_430, 0)","repo":"https://github.com/continuum-industries/Pareto","status":"job_started"}
Mar 24 17:25:43 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:25:43.309Z","job":"gh","level":"info","message":"runner status Job Run Optimisations (REAL_PIPELINE_MOATA_430, 0) completed with result: Succeeded","repo":"https://github.com/continuum-industries/Pareto","status":"job_ended","success":true}
Mar 24 17:25:46 ip-172-31-43-163 cml.sh[1869]: {"date":"2022-03-24T17:25:46.246Z","job":"gh","level":"info","message":"runner status Running job: Run Optimisations (SCOTWIND_2, 0)","repo":"https://github.com/continuum-industries/Pareto","status":"job_started"}
Mar 24 17:25:51 ip-172-31-43-163 cml.sh[1869]: {"level":"error","message":"Runner should be idle. Resetting jobs. Retrying in 300 secs"}
Mar 24 17:30:51 ip-172-31-43-163 cml.sh[1869]: {"level":"info","message":"runner status","reason":"timeout:300","status":"terminated"}
Mar 24 17:30:51 ip-172-31-43-163 cml.sh[1869]: {"level":"info","message":"waiting 10 seconds before exiting..."}
Mar 24 17:31:01 ip-172-31-43-163 cml.sh[1869]: {"level":"info","message":"Unregistering runner cml-wdw16iotk7..."}
Mar 24 17:31:03 ip-172-31-43-163 cml.sh[1869]: {"level":"error","message":"\tFailed: Bad request - Runner \"cml-wdw16iotk7\" is still running a job\""}
```

Any idea what might be going on here?

**Comment by thatGreekGuy96** [comment]
@0x2b3bfa0 any luck on this? It's causing a lot of problems with our CI pipeline so would be great to fix asap!

**Comment by dacbd** [comment]
the Ghost is back! 😢 

> @0x2b3bfa0 any luck on this? It's causing a lot of problems with our CI pipeline so would be great to fix asap!

@thatGreekGuy96 
My immediate bypass that has worked in the past is to extend the timeout in a different way, use `--idle-timeout=21600`  / 6h ie greater than what your expected runtime will be. Previously this issue has been intermittent and extremely hard to find what the root cause is. you can take a [look here as well for the previous context of something similar](https://github.com/iterative/cml/issues/808)

**Comment by 0x2b3bfa0** [comment]
Tentative fix on #925; still not tested.

**Comment by 0x2b3bfa0** [comment]
Sorry for the late reply, @thatGreekGuy96. If you're still able to reproduce this issue, can you please run your workflows with the latest CML version v0.12.1 and post the logs?

We're unable to reproduce the issue, but have added some new logs that may help to find the causes of this issue.

**Comment by thatGreekGuy96** [comment]
No worries @0x2b3bfa0, i'll do that asap. I'll get you the logs asap but from what I can tell the issue is still occurring.

**Comment by DavidGOrtega** [comment]
@thatGreekGuy96 
> from what I can tell the issue is still occurring.

Does this happen to you often?

**Comment by 0x2b3bfa0** [comment]
`listWorkflowRunsForRepo` returns **zero** results
https://github.com/iterative/cml/blob/35eea8415a0e838077c9863b91658bc81ffa8d06/src/drivers/github.js#L628-L634

**Comment by 0x2b3bfa0** [comment]
### Cause

```node
> const { Octokit } = require('@octokit/rest');
undefined
> const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
undefined
> (await octokit.actions.listWorkflowRunsForRepo({ owner: '0x2b3bfa0', repo: 'test', status: 'in_progress' })).data
{ total_count: 0, workflow_runs: [] }
> > (await octokit.actions.listWorkflowRunsForRepo({ owner: '0x2b3bfa0', repo: 'test' })).data.workflow_runs.map(({ status }) => status)
[
  'in_progress', 'completed', 'completed',
  'completed',   'completed', 'completed',
  'completed',   'completed', 'completed',
  'completed',   'completed', 'completed',
  'completed',   'completed', 'completed',
  'completed',   'completed', 'completed',
  'completed',   'completed', 'completed',
  'completed',   'completed', 'completed',
  'completed',   'completed', 'completed',
  'completed',   'completed', 'completed'
]
```

**Comment by DavidGOrtega** [comment]
Im very sure that this is a new issue. I had the runner working for hours as a test.

**Comment by 0x2b3bfa0** [comment]
Sent [#1673336](https://support.github.com/ticket/personal/0/1583336) to GitHub support 😅

**Comment by 0x2b3bfa0** [comment]
Apologies for the delay. It was hard to reproduce and it was indeed a deep rabbit hole; https://github.com/iterative/cml/issues/923#issuecomment-1097007837.

**Comment by 0x2b3bfa0** [comment]
### GitHub Response

> _Apologies for the trouble here._
> 
> _Engineering is reporting that the underlying problem (which is related to Elasticsearch) has been fixed but the results returned from the filter might not be complete until we have a new index. This could take a couple of days, sorry._
> 
> _There is a discussion about this in the community and Engineering has responded - https://github.community/t/workflow-call-has-an-inconsistent-status-in-github-rest-api/244164. A banner will also be displayed in the UI to alert you of this issue when you try to filter the workflow runs. Accessing the endpoint without any filter should return all the workflow runs correctly._
> 
> _I'll let you know once the index fully rebuilds._

@DavidGOrtega, this will interest you for sure. 😄

**Comment by thatGreekGuy96** [comment]
Maybe I shouldn't be posting this on here but right after the fix was deploying, it is now taking much longer for cml runner to deploy ec2 instances. 
I guess this is something for another issue?

**Comment by 0x2b3bfa0** [comment]
@thatGreekGuy96, are you still experiencing those unexpected delays? If so, please open a new issue with the details. 🙏🏼

**Comment by thatGreekGuy96** [comment]
Opened here: https://github.com/iterative/cml/issues/973
@0x2b3bfa0 

I guess you can mark this issue as closed now.

**Comment by 0x2b3bfa0** [comment]
### GitHub follow–up
> _Engineering is reporting that the index is now fully rebuilt. Could you try this again and let me know if you are now getting the expected results for workflow runs? (the banner in the UI may still display but the results should be updated)_
