### ISSUE TITLE
Revert client–side GitHub Actions job filtering

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#952]
Sent [#1673336](https://support.github.com/ticket/personal/0/1583336) to GitHub support. Once they solve the bug described in https://github.com/iterative/cml/issues/923#issuecomment-1097007837, we should reconsider partially reverting #948 & #950, merged to mitigate #923.

**Comment by 0x2b3bfa0** [comment]
Another good reason to consider reverting or refactoring #948 is the time it takes to paginate & retrieve every run since the inception of the repository. I wrote that code in a rush, but it's probably a bad decision at many levels.

**Comment by 0x2b3bfa0** [comment]
GitHub says that the issue is going to be fixed in a couple of days: see https://github.com/iterative/cml/issues/923#issuecomment-1097651573.

**Comment by DavidGOrtega** [comment]
> Another good reason to consider reverting or refactoring https://github.com/iterative/cml/pull/948 is the time it takes to paginate & retrieve every run

Exactly, thats was my consideration when I wrote it. normally you are not having such a big amount of workflows, in any case the pagination of the `running` workflows is OK just in case

**Comment by 0x2b3bfa0** [comment]
GitHub says that the index has been updated: https://github.com/iterative/cml/issues/923#issuecomment-1102865603

**Comment by 0x2b3bfa0** [comment]
Closing with #980
