### ISSUE TITLE
Node 16 change is controversial

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#965]
### Why  
- Its breaking workflows 

### Solutions
 - transpile
 - revert (not possible due to the new publish feature in BB
 - write a line of code uglier

**Comment by 0x2b3bfa0** [comment]
🔔 @iterative/cml, it would be nice to sort this out sooner rather than later

**Comment by dacbd** [comment]
> ```js
> solutions.push('use standalone binaries everywhere')
> ```

I agree, but this can also have a weird set of issues, as we have seen.

I would argue to 
- revert the "fancy" optional chaining
- push standalone binaries
- deprecate node 12 inline with [github actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing) / keep an eye out for when they decide to drop `node12`

**Comment by 0x2b3bfa0** [comment]
> _revert (not possible due to the new publish feature in BB_

Maybe we can write a heap of ternary operators if there is not other remedy? 🤔 🤢

**Comment by 0x2b3bfa0** [comment]
@dacbd & @iterative/cml: #966
