### ISSUE TITLE
Could not load dynamic library 'libcusolver.so.10'; dlerror 

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#972]
Coming from [here](https://discord.com/channels/485586884165107732/728693131557732403/965430882758426706)

> Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

**Comment by 0x2b3bfa0** [comment]
It's not a bug; it's a feature. 😉 Our images use CUDA 11, not CUDA 10.

```console
$ docker run --rm -it iterativeai/cml:0-dvc2-base1-gpu find / -name libcusolver.so.*
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcusolver.so.11
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcusolver.so.11.1.0.152
```

**Comment by 0x2b3bfa0** [comment]
Alternatively, you can use the official [`nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04`](https://hub.docker.com/layers/cuda/nvidia/cuda/10.1-cudnn7-runtime-ubuntu18.04/images/sha256-cd36b6d0798a3ce0b96621f33bbe4cde4c74642d536cb0290ddb6c7ad80a0b3f?context=explore) container image and install our tools separately.

**Comment by 0x2b3bfa0** [comment]
We've seen a few requests in the past regarding CUDA versions:
* https://github.com/iterative/cml/issues/766
* https://github.com/iterative/cml/issues/685
Should we take another look at packaging?

**Comment by mevatron** [comment]
Upgrading to `tensorflow~=2.6.0` does the trick! Thanks again!
