### ISSUE TITLE
ci: --fetch-depth

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml#975]
Backtracking on [not doing this earlier](https://github.com/iterative/cml.dev/pull/222#issuecomment-1098111701) - `cml ci --fetch-depth=<int>` is a [good idea](https://github.com/iterative/cml.dev/pull/222#issuecomment-1098206616)

- `depth=0` could be an alias for `--unshallow`
- could thus deprecate (hide) `--unshallow`
- things like `depth=2` is useful for e.g. `dvc metrics diff HEAD~1` CC @shcheklein @dberenbaum @pmrowla
- `cml ci --fetch-depth=2` is more trustworthy than manually running `git fetch --depth=2` because the latter may not work as expected (?) if the repo was checked out weirdly (vis `actions/checkout@v3` breaking changes)
- `cml ci --fetch-depth=2` is cross-CI compatible unlike `actions/checkout.with.fetch-depth: 2`

**Comment by casperdcl** [comment]
btw just to confirm @dberenbaum does `--fetch-depth` also obtain DVC exp's hidden reflog?

**Comment by dberenbaum** [comment]
Hm, good question. I think not since those refs will likely not be part of the linear history of the branch being fetched (plus it seems a bit DVC-specific). cc @pmrowla

**Comment by pmrowla** [comment]
> btw just to confirm @dberenbaum does `git fetch --depth=2` also obtain DVC exp's hidden reflog?

No, this just sets the depth of whatever refs have already been cloned/fetched to 2. So by default it will only include git branches and tags (and if `actions/checkout` uses `--single-branch` it would only include the PR branch)

**Comment by casperdcl** [comment]
ok so I assume only `git fetch --unshallow` will work? Is there no other way? What if the repo is massive and a full unshallow is undesirable?

**Comment by dberenbaum** [comment]
The experiment refs aren't needed, so usually fetch depth of 2 or so on the cloned branch will be enough. They are needed to merge the head and the experiment changed afaik.

**Comment by pmrowla** [comment]
> ok so I assume only `git fetch --unshallow` will work? Is there no other way? What if the repo is massive and a full unshallow is undesirable?

This won't fetch exp refs either, git commands only fetch branches/tags by default. You have to either be specifying the full exp refs with `git fetch <options> refs/exps/...` or using the `dvc exp pull` commands

**Comment by dberenbaum** [comment]
To be clear, fetching exp refs is unnecessary for many exp operations, like exp run. Having fetch depth is still useful for exp run.

**Comment by deepyaman** [comment]
Hello! I've been curious about CML for some time, and Hacktoberfest seems like a good opportunity to dive in. Can I take a stab at this issue?

Based on a quick look, I think this would involve modifying similar code as in https://github.com/iterative/cml/pull/957/files. @casperdcl Just to confirm, based on your description, should the fix deprecate `--unshallow` at the same time?

**Comment by casperdcl** [comment]
thanks @deepyaman! Yes feel free to have a go. [`--unshallow`](https://github.com/iterative/cml/blob/f34a0892691e64caa8a23db96276eb8b593153c0/bin/cml/repo/prepare.js#L16) can be soft-deprecated using [`.hidden`](https://github.com/iterative/cml/blob/341f32e0dcd7a5d2f9af5d504017ac3fa8fcea6e/bin/cml/asset/publish.js#L32) :)

**Comment by deepyaman** [comment]
Sorry for the delay. This is still very much on my list of things to do; got busy, but I hope to have a PR by later this week.

**Comment by casperdcl** [comment]
no problem, looking forward to a PR @deepyaman

**Comment by casperdcl** [comment]
Ah don't worry about testing locally - a lot of functionality needs actual CI to test effectively.

Don't worry if PR tests also fail, we can fix them :)
