### ISSUE TITLE
cml binary do not recognise cml-{command}

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#979]
CML binary do not recognise `cml-{command}`

This error while definitely not very important it might affect some workflows if we do the final transition to binary everywhere.

**Comment by 0x2b3bfa0** [comment]
Of course it doesn't

**Comment by 0x2b3bfa0** [comment]
If the binary supported link–based single entrypoint like `busybox` you would need to create the links anyway. 🙃

**Comment by DavidGOrtega** [comment]
Im not  saying that the binary needs to do it. It's obviously impossible. What I try to expose is that if we change `setup-cml` or cml itself within the image workflows are going to be broken. Maybe scripts? Not to do anything?
I have added the `discussion` tag

**Comment by 0x2b3bfa0** [comment]
> _Im not saying that the binary needs to do it. It's obviously impossible._

It's _not_ impossible, as long as somebody creates a few soft links: 😄 

```bash
package main

import (
	"log"
	"os"
	"path"
)

func main() {
	switch base := path.Base(os.Args[0]); base {
	case "one":
		log.Println("one")
	case "two":
		log.Println("two")
	default:
		log.Fatalf("unknown: %s", base)
	}
}
```

> _What I try to expose is that if we change `setup-cml` or `cml` itself within the image workflows are going to be broken._

Unless we modify `setup-cml` and any other installation methods to create a dummy wrapper:

```bash
#!/bin/sh
exec cml "$(basename "$0" | sed 's/^cml-\(.*\)$/\1/')" "$@"
```

This can be saved as `cml-legacy.sh` and then linked:

```bash
ln -s /path/to/cml-legacy.sh /usr/local/bin/cml-pr
ln -s /path/to/cml-legacy.sh /usr/local/bin/cml-runner
···
```

> _Not to do anything?_

Perhaps. It's tempting, but we may break existing workflows.

**Comment by casperdcl** [comment]
`cml-command` is deprecated in favour of `cml command`. If people upgrade to using the latest binary package they can definitely upgrade their command syntax at the same time.

**Comment by 0x2b3bfa0** [comment]
* Voting to close in favor of https://github.com/iterative/setup-cml/issues/57, which is probably subject to the same considerations.

**Comment by dacbd** [comment]
[There is also this not so beautiful line to consider](https://github.com/iterative/terraform-provider-iterative/blob/b31ed6b63ea55f1a620d5386bbfdcb02217055ee/iterative/resource_runner.go#L346)

**Comment by 0x2b3bfa0** [comment]
Won't fix as per https://github.com/iterative/cml/issues/979#issuecomment-1104175802
