### ISSUE TITLE
Image upload with retina 

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#99]
It's possible to control Retina or resize images?

**Comment by shcheklein** [comment]
I guess a couple options:

- use `<img src="https://github.com/favicon.ico" width="48">` - it should support it. Width should be 1/2 of the actual image width. We'll have to use `-s 2` for vl2png (which apparently doesn't properly work).
- use SVG, which breaks the cml-publish unfortunately at the moment.

**Comment by DavidGOrtega** [comment]
We have added SVG support.
