### ISSUE TITLE
`send-comment --pr --update` not working without specifying `--commit-sha=HEAD`

### ISSUE THREAD

**Issue by RCdeWit** [iterative/cml#991]
This workflow threw the following error:

```
- name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          set -x
          cml ci
          pip install -r requirements.txt
          python get_data.py
          python train.py

          # Create pull request
          cml pr model/random_forest.joblib

          # Create CML report
          cat model/metrics.txt > report.md
          cml publish model/confusion_matrix.png --md >> report.md
          cml send-comment --pr --update report.md
```
```
{"level":"error","message":"PR for commit sha \"54e32ca98b5faa1f7982a682e0f6de07347a7531\" not found","stack":"Error: PR for commit sha \"54e32ca98b5faa1f7982a682e0f6de07347a7531\" not found\n    at CML.commentCreate (/snapshot/cml/src/cml.js:185:15)\n    at async Object.exports.handler (/snapshot/cml/bin/cml/send-comment.js:13:15)"}
Error: Process completed with exit code 1.
```

After some back and forth on Slack, we came to the following:

:x: Do not work:
- `cml send-comment --pr --update report.md`
- `cml send-comment --commit-sha --pr --update report.md`

:white_check_mark: Do work:
- `cml send-comment --update report.md`
- `cml send-comment --commit-sha=HEAD --pr --update report.md`

I am currently unsure of the precise intended workings; is `send-comment --pr --update` a valid use case or not? Different views in Slack, so creating a ticket here for further discussion.

**Comment by casperdcl** [comment]
- `--commit-sha` and `--pr` should raise a `conflict` error
- `send-comment --pr [--update]` failing is definitely a bug

**Comment by RCdeWit** [comment]
Just noticed that my latest working script does not actually update the PR with the `report.md`;

```
cml ci
        pip install -r requirements.txt
        python get_data.py
        python train.py

        # Create pull request
        cml pr model/random_forest.joblib

        # Create CML report
        cat model/metrics.txt > report.md
        cml publish model/confusion_matrix.png --md >> report.md
        cml send-comment --update report.md
```

Here's the relevant run:
https://github.com/RCdeWit/example_model_export_cml/pull/9

**Comment by 0x2b3bfa0** [comment]
> `--commit-sha` and `--pr` should raise a conflict error

On second thought, it's a valid use case. What if users want to comment on a pull request other than the current one?

**Comment by 0x2b3bfa0** [comment]
> _Just noticed that my latest working script does not actually update the PR_

@RCdeWit, feel free to open another issue if you still experience the same problem after we release #992
